'use strict';
const G=Growth,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state,blocked=false,child='brother',page='today',parent=false,mood='開心',intensity=1,tool='深呼吸',timer;
function load(){try{const raw=localStorage.getItem(G.KEY);state=raw?JSON.parse(raw):G.fresh();if(!G.valid(state))throw Error('資料格式無法讀取');if(!raw)localStorage.setItem(G.KEY,JSON.stringify(state));blocked=false;$('#notice').textContent='';}catch(e){blocked=true;state=state&&G.valid(state)?state:G.fresh();$('#notice').textContent='⚠️ 無法讀取或保存資料，已暫停記錄。請確認瀏覽器允許儲存；原資料未被重置。';}}
load();
function change(fn){if(blocked){toast('目前無法保存，請先確認瀏覽器儲存設定');return false}try{let raw=localStorage.getItem(G.KEY);let next=raw?JSON.parse(raw):G.fresh();if(!G.valid(next))throw Error();const result=fn(next.children[child]);if(result===false||result===null)return false;localStorage.setItem(G.KEY,JSON.stringify(next));state=next;return result??true}catch(e){blocked=true;$('#notice').textContent='⚠️ 儲存失敗，這次操作沒有完成。請確認可用空間與瀏覽器設定。';return false}}
function toast(s){clearTimeout(timer);$('#toast').textContent=s;timer=setTimeout(()=>$('#toast').textContent='',3500)}
function close(){const d=$('#modal');if(d.open)d.close();d.innerHTML=''}
function modal(html){close();$('#modal').innerHTML=html;$('#modal').showModal()}
function c(){return state.children[child]}function profile(){return G.profiles.find(p=>p.id===child)}
function history(items){return items.length?`<div class="history">${items.slice().reverse().map(x=>`<div class="entry"><strong>${esc(x.title)}</strong><small>${esc(x.date)}${x.skill?' · '+esc(x.skill):''}</small>${x.text?`<p>${esc(x.text)}</p>`:''}</div>`).join('')}</div>`:'<div class="empty">這裡等著收藏你的第一個故事 🌱</div>'}
function render(){const p=profile();$('#app').innerHTML=`<main class="shell"><header><div class="brand">🌱 小小成長島 <span class="tag">MVP v0.2</span></div><div class="children" aria-label="選擇孩子">${G.profiles.map(p=>`<button data-child="${p.id}" class="${p.id===child?'active':''}" aria-pressed="${p.id===child}">${p.icon} ${p.name}</button>`).join('')}</div><button data-action="parent">${parent?'🔓 離開家長模式':'🔒 家長'}</button></header><div class="intro row"><div><div class="eyebrow">${parent?'一起陪伴，慢慢長大':G.day()+' · 每天一點點就很好'}</div><h1>${parent?'家長的小幫手':p.icon+' '+p.name+'的成長島'}</h1></div><div class="balance">⭐ ${c().stars} <small>　🌱 ${c().growth}</small></div></div><section id="view">${parent?parentView():views[page]()}</section><p class="footer">資料只保存在這個瀏覽器，不會跨裝置同步。清除網站資料會遺失紀錄。${parent?'可在下方備份資料。':'漏做也沒關係，已經累積的成長一直都在。'}</p>${parent?'<button data-action="backup">下載家庭資料備份</button>':''}</main>${parent?'':`<nav aria-label="主要導覽">${[['today','🏠','今天'],['growth','📖','成長'],['emotion','😊','心情'],['reward','🎁','獎勵'],['world','🌳','世界']].map(([id,icon,label])=>`<button data-page="${id}" class="${id===page?'active':''}" ${id===page?'aria-current="page"':''}><span>${icon}</span>${label}</button>`).join('')}</nav>`}`}
const views={today(){let data=c();return `<div class="hero"><h2>☀️ 今天，想從哪件事開始？</h2><p>做完一件，就留下一個小小的成長。</p></div>${['每日','支線','冒險'].map(type=>`<div class="section"><h2>${type==='每日'?'☀️ 每日小習慣':type==='支線'?'✨ '+profile().side+'支線':'🧭 一次小冒險'}</h2><p class="muted">${type==='冒險'?'每個冒險完成一次，新的冒險由家長加入。':'每天可以完成一次，不用補做昨天的。'}</p><div class="grid">${data.tasks.filter(t=>t.type===type).map(t=>{let s=G.status(data,t);return `<article class="card"><span class="icon">${esc(t.icon)}</span><span class="pill">${esc(t.skill)}</span>${t.approval?'<span class="pill">家長陪你確認</span>':''}<h3>${esc(t.title)}</h3><p>⭐ ${t.stars}　🌱 ${t.growth}</p><button class="wide ${s?'':'primary'}" data-task="${esc(t.id)}" ${s?'disabled':''}>${s?(s.status==='pending'?'⏳ 等家長確認':'✓ 已完成'):'開始看看 →'}</button></article>`}).join('')}</div></div>`).join('')}`},
growth(){return `<div class="hero"><h2>📖 我的成長護照</h2><p>每一次嘗試，都有自己的故事。已收藏 ${c().records.length} 則故事。</p></div>${history(c().records)}`},
emotion(){return `<div class="hero"><h2>現在的我，感覺怎麼樣？</h2><p>每一種感受都可以，不需要分好壞。</p></div><div class="card"><h3>1. 選一個感覺</h3><div class="choices">${[['😄','開心'],['😢','難過'],['😠','生氣'],['😟','擔心'],['😌','平靜'],['😴','累累']].map(([icon,m])=>`<button data-mood="${m}" class="${m===mood?'active':''}" aria-pressed="${m===mood}"><span class="face">${icon}</span>${m}</button>`).join('')}</div><h3>2. 有多強烈？</h3><div class="choices">${[1,2,3].map(n=>`<button data-intensity="${n}" class="${n===intensity?'active':''}" aria-pressed="${n===intensity}">${n} · ${['','一點點','有一些','很強烈'][n]}</button>`).join('')}</div><h3>3. 我想試試</h3><div class="choices">${['深呼吸','安靜一下','找人說說'].map((t,i)=>`<button data-tool="${t}" class="${t===tool?'active':''}" aria-pressed="${t===tool}">${['🌬️','🍃','🫶'][i]} ${t}</button>`).join('')}</div><div class="hero"><h3>${tool}</h3><p>${{'深呼吸':'像聞花一樣慢慢吸氣，再像吹蠟燭一樣慢慢吐氣。照自己的速度做 3 次。','安靜一下':'找一個舒服、安全的地方坐一下。看看周圍，讓身體休息。','找人說說':'找信任的大人，試著說：「我現在覺得'+esc(mood)+'，可以陪我一下嗎？」'}[tool]}</p><strong>${learnEmotion()}</strong></div><button class="primary" data-action="emotion">記下現在的我</button><p class="muted">心情不用換星星，每種感受都值得被聽見。</p></div><div class="section"><h2>我的心情足跡</h2>${history(c().emotions.map(x=>({title:x.mood+' · 強度 '+x.intensity,date:x.date,text:x.tool+'：'+x.learn})))}</div>`},
reward(){let available=c().stars-G.reserved(c());return `<div class="hero"><h2>🎁 一起期待的小事</h2><p>可以使用 ⭐ ${available} ${G.reserved(c())?' · 等確認的星星 '+G.reserved(c()):''}</p><p>提出兌換 → 家長確認 → 一起安排。只有確認兌換才會使用星星。</p></div><div class="grid">${G.rewards.map(r=>`<article class="card"><span class="icon">${r.icon}</span><h3>${r.name}</h3><p>⭐ ${r.cost}</p><button class="wide primary" data-reward="${r.id}" ${available<r.cost?'disabled':''}>${available<r.cost?'再累積 '+(r.cost-available)+' 顆星':'我想兌換'}</button></article>`).join('')}</div><div class="section"><h2>兌換紀錄</h2>${history(c().redemptions.map(r=>({title:r.icon+' '+r.name,date:r.date,text:`⭐ ${r.cost} · ${r.status==='pending'?'等家長確認（尚未使用星星）':r.status==='approved'?'已確認，和家長安排時間':'已取消，沒有使用星星'}`})))}</div>`},
world(){let value=c().growth,level=value>=200?3:value>=80?2:value>=20?1:0,next=[20,80,200][level];return `<div class="hero"><h2>🌳 這是我的小小世界</h2><p>成長會留在這裡。休息一天，島嶼也會好好等你。</p></div><div class="grid two"><div class="island"><span class="cloud">☁️　☀️</span><span class="tree">${['🌱','🌿','🌳','🌳'][level]}</span><div class="animals">${['🪨','🌼 🪨','🌷 🐦 🌼','🌷 🐦 🏡 🦋'][level]}</div><h2>${['一顆新芽','綠意發芽','樹下的朋友','溫暖的小島'][level]}</h2></div><div class="card"><span class="icon">✨</span><h2>每個小步，都在長大</h2><p>已累積 🌱 ${value} 成長值</p>${next?`<div class="progress"><div style="width:${Math.min(100,value/next*100)}%"></div></div><p>再 ${next-value} 成長值，就有新的風景。</p>`:'<p>島嶼已經開花了！新的故事仍會收進成長護照。</p>'}<p class="muted">使用星星不會減少成長值。這裡沒有排名，也不用趕上任何人。</p></div></div>`}};
function learnEmotion(){return {'深呼吸':'我學會了：我可以先照顧身體，再慢慢說出感受。','安靜一下':'我學會了：需要休息時，我可以給自己一點空間。','找人說說':'我學會了：我可以找信任的人陪我一起面對。'}[tool]}
function parentView(){const d=c(),today=d.completions.filter(x=>x.date===G.day()),pending=d.completions.filter(x=>x.status==='pending'),requests=d.redemptions.filter(x=>x.status==='pending');return `<div class="hero"><h2>${profile().icon} ${profile().name} · 今日總覽</h2><p>完成 ${today.filter(x=>x.status==='approved').length} 件 · 任務待確認 ${pending.length} 件 · 兌換待確認 ${requests.length} 件</p><small>原型 PIN：1234。僅防止誤觸，並非安全帳號或隱私保護。此頁只顯示目前選擇的孩子。</small></div><h2>待確認</h2><div class="history">${pending.map(x=>`<div class="entry row"><div><strong>${esc(x.title)}</strong><small>${x.date} · ⭐ ${x.stars} / 🌱 ${x.growth}</small></div><button class="primary" data-approve-task="${x.id}">確認完成</button></div>`).join('')}${requests.map(x=>`<div class="entry row"><div><strong>${esc(x.name)}</strong><small>${x.date} · 確認將使用 ⭐ ${x.cost}</small></div><div><button data-cancel-reward="${x.id}">取消申請</button> <button class="primary" data-approve-reward="${x.id}">確認兌換</button></div></div>`).join('')}${pending.length+requests.length===0?'<div class="empty">目前沒有待確認事項 🍃</div>':''}</div><div class="section row"><h2>任務清單</h2><button class="primary" data-action="add">＋ 新增任務</button></div><div class="history">${d.tasks.map(t=>`<div class="entry row"><div><strong>${esc(t.icon)} ${esc(t.title)}</strong><small>${t.type} · ⭐ ${t.stars} · 🌱 ${t.growth} · ${t.approval?'需家長確認':'孩子自行完成'}</small></div></div>`).join('')}</div><div class="section card"><h2>❤️ 今天被我看見了</h2><p class="muted">描述你看見的具體行動，不評分、不給星星。例如：「你今天有聽妹妹把話說完。」</p><form id="seen-form"><label for="seen">我看見了……</label><textarea id="seen" maxlength="200" required placeholder="寫下一個真實的小片刻"></textarea><button class="primary" style="margin-top:16px">收進成長護照</button></form></div><div class="section"><h2>孩子的成長紀錄</h2>${history(d.records)}</div>`}
function taskDialog(id){let t=c().tasks.find(x=>x.id===id);if(!t||G.status(c(),t))return;modal(`<span class="icon" style="font-size:55px">${esc(t.icon)}</span><h2>${esc(t.title)}</h2><p>${t.id==='bag'?'看看課本、鉛筆盒、水壺，都準備好了嗎？':'先在生活裡試一試，做好了再回來告訴我。'}</p><p>⭐ ${t.stars}　🌱 ${t.growth}${t.approval?' · 家長確認後加入':''}</p><div class="actions"><button data-action="close">還沒，回去看看</button><button class="primary" data-complete="${esc(id)}">✓ 我完成了</button></div>`)}
function addDialog(){modal(`<h2>新增給${profile().name}的任務</h2><label for="preset">從預設開始</label><select id="preset"><option value="custom">自訂任務</option><option value="clothes">準備明天的衣服</option><option value="nature">認識一種植物</option><option value="side">${profile().side}新練習</option></select><form id="task-form"><label for="title">任務名稱</label><input id="title" required maxlength="50"><label for="type">任務種類</label><select id="type"><option>每日</option><option>支線</option><option>冒險</option></select><div class="grid two"><div><label for="stars">星星（0–50）</label><input id="stars" type="number" value="10" min="0" max="50" required></div><div><label for="growth">成長值（0–50）</label><input id="growth" type="number" value="10" min="0" max="50" required></div></div><label for="skill">學習方向</label><select id="skill"><option>生活自理</option><option>探索學習</option><option>練習與耐心</option><option>品格與關懷</option></select><p class="muted">品格與關懷只留故事，不增加星星或成長數值。</p><label for="learn">我學會了</label><input id="learn" maxlength="100" value="我可以一步一步練習。" required><label class="checkline"><input id="important" type="checkbox" checked>完成時顯示學習句</label><label class="checkline"><input id="approval" type="checkbox" checked>需要家長確認</label><div class="actions"><button type="button" data-action="close">取消</button><button class="primary">新增任務</button></div></form>`)}
document.addEventListener('click',e=>{let b=e.target.closest('button');if(!b||b.disabled)return;let d=b.dataset;
if(d.child){child=d.child;mood='開心';intensity=1;tool='深呼吸';close();render();return}if(d.page){page=d.page;render();window.scrollTo(0,0);return}if(d.mood){mood=d.mood;render();return}if(d.intensity){intensity=Number(d.intensity);render();return}if(d.tool){tool=d.tool;render();return}
if(d.task){taskDialog(d.task);return}if(d.complete){let x=change(c=>G.complete(c,d.complete));if(!x)return;render();modal(`<div class="celebrate"><div class="icon">${x.status==='pending'?'🌿':'✨'}</div><h2>${x.status==='pending'?'已記下你的努力！':'做到了！'}</h2><p>${x.status==='pending'?'等家長確認後，星星與成長值就會加入。':`⭐ +${x.stars}　🌱 +${x.growth}`}</p>${x.important?`<div class="hero"><h3>我學會了</h3><p>${esc(x.learn)}</p><strong>${esc(x.skill)}</strong></div>`:''}<div class="actions"><button data-action="close">回到今天</button><button class="primary" data-action="passport">看看成長護照</button></div></div>`);return}
if(d.reward){let r=G.rewards.find(x=>x.id===d.reward);modal(`<h2>${r.icon} ${r.name}</h2><p>需要 ⭐ ${r.cost}。送出後先保留可用額度，家長確認才會使用星星。</p><div class="actions"><button data-action="close">再想一下</button><button class="primary" data-request="${r.id}">確定申請</button></div>`);return}
if(d.request){let ok=change(c=>G.requestReward(c,d.request));close();render();toast(ok?'已送給家長確認':'星星不足，請重新確認');return}
if(parent&&d.approveTask){if(change(c=>G.approveTask(c,d.approveTask))){render();toast('已確認，星星與成長紀錄已加入')}return}
if(parent&&(d.approveReward||d.cancelReward)){const id=d.approveReward||d.cancelReward;if(d.approveReward){let r=c().redemptions.find(x=>x.id===id);modal(`<h2>確認兌換${esc(r.name)}？</h2><p>將使用 ⭐ ${r.cost}，並留下兌換紀錄。請和孩子約好兌換時間。</p><div class="actions"><button data-action="close">返回</button><button class="primary" data-final-reward="${id}">確認使用星星</button></div>`)}else{change(c=>G.resolveReward(c,id,false));render();toast('已取消，星星沒有減少')}return}
if(parent&&d.finalReward){let ok=change(c=>G.resolveReward(c,d.finalReward,true));close();render();toast(ok?'兌換完成，和孩子一起安排吧':'未完成，請檢查星星與紀錄');return}
switch(d.action){case 'close':close();break;case 'passport':close();page='growth';render();break;case 'parent':if(parent){parent=false;render()}else modal('<h2>🔒 家長模式</h2><p>原型預設 PIN：<strong>1234</strong><br>僅防誤觸，不是安全帳號。</p><form id="pin-form"><label for="pin">輸入 PIN</label><input id="pin" type="password" inputmode="numeric" maxlength="4" required autocomplete="off"><p id="pin-error" class="error" role="alert"></p><div class="actions"><button type="button" data-action="close">返回</button><button class="primary">進入</button></div></form>');break;case 'emotion':{let learn=learnEmotion();if(change(c=>{c.emotions.push({id:G.uid(),date:G.day(),mood,intensity,tool,learn});c.records.push({id:G.uid(),date:G.day(),kind:'emotion',title:'我越來越懂自己',skill:'情緒覺察',text:mood+' · '+tool+'。'+learn})})){render();toast('已收好你的感受，謝謝你照顧自己')}break}case 'add':if(parent)addDialog();break;case 'backup':if(parent){let a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.href=url;a.download='成長島備份-'+G.day()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}break;}
});
document.addEventListener('submit',e=>{e.preventDefault();if(e.target.id==='pin-form'){if($('#pin').value==='1234'){parent=true;close();render()}else $('#pin-error').textContent='PIN 不正確，再試一次。';return}if(!parent)return;if(e.target.id==='seen-form'){let text=$('#seen').value.trim();if(!text)return;if(change(c=>c.records.push({id:G.uid(),date:G.day(),kind:'seen',title:'今天被我看見了 ❤️',skill:'被看見的成長',text}))){render();toast('這個片刻已收進成長護照')}return}if(e.target.id==='task-form'){let title=$('#title').value.trim(),learn=$('#learn').value.trim(),skill=$('#skill').value,stars=Number($('#stars').value),growth=Number($('#growth').value);if(!title||!learn||![stars,growth].every(x=>Number.isInteger(x)&&x>=0&&x<=50))return;let t={id:G.uid(),title,learn,skill,stars:skill==='品格與關懷'?0:stars,growth:skill==='品格與關懷'?0:growth,type:$('#type').value,important:$('#important').checked,approval:$('#approval').checked,icon:'✨'};if(change(c=>c.tasks.push(t))){close();render();toast('任務已加入')}}});
document.addEventListener('change',e=>{if(e.target.id==='preset'){let p={clothes:['準備明天的衣服','每日','生活自理','我可以為明天的自己做好準備。'],nature:['認識一種植物','冒險','探索學習','仔細觀察，就能發現新的事物。'],side:[profile().side+'新練習','支線','練習與耐心','多試一次，就多認識自己一點。']}[e.target.value];if(p){['title','type','skill','learn'].forEach((id,i)=>$('#'+id).value=p[i]);$('#stars').disabled=$('#growth').disabled=false;$('#stars').value=$('#growth').value=10}}if(e.target.id==='skill'){let zero=e.target.value==='品格與關懷';$('#stars').disabled=$('#growth').disabled=zero;if(zero)$('#stars').value=$('#growth').value=0}});
window.addEventListener('storage',e=>{if(e.key===G.KEY){load();close();render();toast('已更新另一個分頁的紀錄')}});
let lastDay=G.day();setInterval(()=>{if(G.day()!==lastDay){lastDay=G.day();close();render()}},30000);
render();


