'use strict';
const G=Growth,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state,blocked=false,child=null,page='today',parent=false,timer,celebration=null;
const newDraft=()=>({step:1,mood:'',intensity:1,cause:'',toolId:'',practiced:false,after:''});
let emotion=newDraft();
function readState(){const raw=localStorage.getItem(G.KEY);if(!raw){const s=G.fresh();localStorage.setItem(G.KEY,JSON.stringify(s));return s}const old=JSON.parse(raw);if(!G.valid(old))throw Error('資料無法讀取');if(old.rulesVersion!==3){const backup=G.KEY+'-before-rules-v3';if(!localStorage.getItem(backup))localStorage.setItem(backup,raw);const next=G.migrate(old);localStorage.setItem(G.KEY,JSON.stringify(next));return next}return old}
function load(){try{state=readState();blocked=false;$('#notice').textContent=''}catch(e){blocked=true;state=state&&G.valid(state)?state:G.fresh();$('#notice').textContent='⚠️ 無法讀取或保存資料，已暫停記錄。請確認瀏覽器儲存設定；原資料未被重置。'}}
function change(fn){if(blocked){toast('目前無法保存，請先確認瀏覽器儲存設定');return false}try{const next=readState(),result=fn(child?next.children[child]:null,next);if(result===false||result===null)return false;localStorage.setItem(G.KEY,JSON.stringify(next));state=next;return result??true}catch(e){blocked=true;$('#notice').textContent='⚠️ 儲存失敗，這次操作沒有完成。請確認可用空間與瀏覽器設定。';return false}}
function toast(s){clearTimeout(timer);$('#toast').textContent=s;timer=setTimeout(()=>$('#toast').textContent='',4000)}
function close(){if($('#modal').open)$('#modal').close();$('#modal').innerHTML='';celebration=null}
function modal(html){close();const dialog=$('#modal');dialog.innerHTML=html;const exits=[...dialog.querySelectorAll('[data-action="close"],[data-s="close"]')];if(exits.length){exits.forEach(b=>{if(!b.hasAttribute('data-keep-label'))b.textContent='返回';b.type='button'})}else{const back=document.createElement('button');back.type='button';back.dataset.action='close';back.className='dialog-return';back.textContent='返回';dialog.prepend(back)}dialog.showModal()}
function c(){return state.children[child]}function profile(){return G.profiles.find(p=>p.id===child)}
function button(label,action,extra=''){return `<button data-action="${action}" ${extra}>${label}</button>`}
function history(items){return items.length?`<div class="history">${items.slice().reverse().map(x=>`<div class="entry"><strong>${esc(x.title)}</strong><small>${esc(x.date)}${x.skill?' · '+esc(x.skill):''}</small>${x.text?`<p>${esc(x.text)}</p>`:''}${x.autonomy?`<small>這次：${esc(x.autonomy)}</small>`:''}${x.abilities?.length?`<small>正在練習：${G.educationFor(x).map(id=>esc(G.educationMap.find(a=>a.id===id).name)).join('、')}</small>`:''}</div>`).join('')}</div>`:'<div class="empty">這裡等著收藏你的第一個故事 🌱</div>'}
function entry(){return `<main class="shell welcome"><div class="brand">🌱 小小成長島 <span class="tag">v0.4</span></div><div class="welcome-title"><div class="island-icon">🏝️</div><h1>今天是誰來到成長島？</h1><p class="muted">選自己的圖案，一起慢慢長大。</p></div><div class="grid">${G.profiles.map(p=>`<button class="card role" data-child="${p.id}"><span class="icon">${p.icon}</span><h2>我是${p.name}</h2><p>${p.sideIcon} ${p.side}</p><span>進入我的島 →</span></button>`).join('')}</div><div class="welcome-parent">${button('🔒 我是家長','parent')}<p class="muted">陪孩子一起探索與成長</p></div></main>`}
function render(){if(!child){$('#app').innerHTML=entry();return}$('#app').innerHTML=`<main class="shell"><header><div class="brand">🌱 小小成長島 <span class="tag">v0.4</span></div>${parent?`<div class="children">${G.profiles.map(p=>`<button data-child="${p.id}" class="${p.id===child?'active':''}">${p.icon} ${p.name}</button>`).join('')}</div>`:button('↩ 換使用者','users')} ${button(parent?'🔓 離開家長模式':'🔒 家長','parent')}</header><div class="intro row"><div><div class="eyebrow">${parent?'一起陪伴，慢慢長大':G.day()+' · 每天一點點就很好'}</div><h1>${parent?profile().name+'的陪伴小幫手':profile().icon+' '+profile().name+'的成長島'}</h1></div><div class="balance">⭐ ${c().stars}　🪙 ${c().coins}<small>　🌱 ${c().growth}</small></div></div><section id="view">${parent?parentView():views[page]()}</section><p class="footer">資料只保存在這個瀏覽器，不跨裝置同步。漏做不扣分，休息不倒退。${parent?'原型 PIN：1234，僅防誤觸，不是安全帳號。':''}</p>${parent?button('下載家庭資料備份','backup'):''}</main>${parent?'':`<nav aria-label="主要導覽">${[['today','🏠','今天'],['growth','📖','成長'],['emotion','😊','心情'],['reward','🎁','獎勵'],['world','🌳','世界']].map(([id,icon,label])=>`<button data-page="${id}" class="${id===page?'active':''}" ${id===page?'aria-current="page"':''}><span>${icon}</span>${label}</button>`).join('')}</nav>`}`}
const views={
 today(){return `<div class="hero"><h2>☀️ 今天，想從哪件事開始？</h2><p>先試一試，發現自己學會了什麼。</p></div>${['每日','支線','冒險'].map(type=>`<div class="section"><h2>${type==='每日'?'☀️ 每日小習慣':type==='支線'?'✨ '+profile().side+'支線':'🧭 一次小冒險'}</h2><div class="grid">${c().tasks.filter(t=>t.type===type).map(t=>{const s=G.status(c(),t);return `<button class="card task-tile" data-task="${esc(t.id)}" aria-haspopup="dialog" ${s?'disabled':''}><span class="task-icon">${esc(t.icon)}</span><span class="task-copy"><strong>${esc(t.title)}</strong><small>${s?(s.status==='pending'?'⏳ 等家長確認':'✓ 已完成'):esc(t.skill)}</small></span><span aria-hidden="true">${s?'':'›'}</span></button>`}).join('')}</div></div>`).join('')}`},
 growth(){return `<div class="hero"><h2>📖 我的成長護照</h2><p>已收藏 ${c().records.length} 則自己的故事。</p></div>${history(c().records)}`},
 emotion(){let body='';const step=emotion.step,t=G.emotionTools.find(t=>t.id===emotion.toolId);if(step===1)body=`<h2>現在的我，感覺怎麼樣？</h2><p>每一種感受都可以，也可以還不知道。</p><div class="choices mood-grid">${G.moods.map(([icon,name])=>`<button data-mood="${name}" class="${emotion.mood===name?'active':''}" aria-pressed="${emotion.mood===name}"><span class="face">${icon}</span>${name}</button>`).join('')}</div><h3>有多強烈？</h3><div class="choices">${[1,2,3].map(n=>`<button data-intensity="${n}" class="${emotion.intensity===n?'active':''}">${n} · ${['','一點點','有一些','很強烈'][n]}</button>`).join('')}</div>${button('接著看看 →','emotion-next',`class="primary" ${!emotion.mood?'disabled':''}`)}`;
 if(step===2)body=`<h2>發生了什麼事？</h2><p>選最接近的就好，不想說也可以。</p><div class="choices mood-grid">${G.causes.map(([icon,name])=>`<button data-cause="${name}" class="${emotion.cause===name?'active':''}"><span class="face">${icon}</span>${name}</button>`).join('')}</div>${button('我想試試 →','emotion-next',`class="primary" ${!emotion.cause?'disabled':''}`)}`;
 if(step===3)body=`<h2>我想試試……</h2><p>可以換方法，不需要立刻讓感受消失。</p>${['照顧身體','給自己空間','表達與陪伴'].map(group=>`<h3>${group}</h3><div class="choices">${G.emotionTools.filter(t=>t.group===group).map(t=>`<button data-tool="${t.id}" class="${emotion.toolId===t.id?'active':''}"><span class="face">${t.icon}</span>${t.name}</button>`).join('')}</div>`).join('')}${t?`<div class="hero"><h3>${t.icon} ${t.name}</h3><p>${t.steps}</p><p><strong>我學會了：${t.learn}</strong></p>${button('🔊 聽聽看','speak')}</div><div class="choices">${button('我試過了，記一下','tried','class="primary"')}${button('先記下，還沒想試','not-tried')}</div>`:'<div class="empty">選一個方法，就能看到怎麼做。</div>'}`;
 if(step===4)body=`<h2>現在的感受呢？</h2><p>沒有變好也沒關係，你已經有照顧自己。</p><div class="choices">${['有一點變化','差不多','更強烈了','還不知道'].map(a=>`<button data-after="${a}" class="${emotion.after===a?'active':''}">${a}</button>`).join('')}</div>${emotion.after==='更強烈了'?'<div class="hero">可以先停下來，請信任的大人陪著你，不用自己撐著。</div>':''}${button('收進我的心情足跡','save-emotion',`class="primary" ${!emotion.after?'disabled':''}`)}`;
 return `<div class="hero"><div class="row"><h2>😊 我的心情小旅程</h2><span class="pill">${step} / 4</span></div><p>感受 → 原因 → 試一試 → 回頭看看</p></div><div class="card">${step>1?button('← 上一步','emotion-back'):''}${body}</div><div class="section"><h2>🫶 我的能力徽章</h2><p class="muted">收藏願意發現、表達與嘗試的小步，不評分心情、不換星星。</p><div class="grid">${G.badges(c()).map(b=>`<div class="card"><span class="icon">${b.icon}</span><h3>${b.name}</h3><p>${b.text}</p><span class="pill">${b.earned?'已收藏':'慢慢探索，不用趕'}</span></div>`).join('')}</div></div><div class="section"><h2>心情足跡</h2>${history(c().emotions.map(x=>({title:x.mood+' · 強度 '+x.intensity,date:x.date,text:[x.cause,x.tool,x.practiced===false?'還沒試，先記下來':'',x.after].filter(Boolean).join(' · ')})))}</div>`},
 reward(){const goal=state.rewards.find(r=>r.id===c().goal),available=G.available(c());return `<div class="hero"><h2>🎁 我的選擇與期待</h2><p>⭐ 星星：現實獎勵　🪙 金幣：世界收藏　🌱 成長值：一直累積</p><p>每個家的約定不同，品項與星星由家長設定。</p></div><div class="grid two"><div class="card"><h2>⭐ 我的星星</h2><p>總共有 ${c().stars} · 現在可用 ${available}</p><p>目標裡 ${c().savings} · 等家長確認 ${G.reserved(c())}</p><small>存進目標只是分配自己的星星，不會增加或扣掉總數。</small></div><div class="card"><h2>🐷 我的目標</h2>${goal?`<h3>${esc(goal.icon)} ${esc(goal.name)}</h3><p>已存 ${c().savings} / ${goal.cost} ⭐ ${goal.active===false?'· 家長已暫停兌換':''}</p><div class="progress"><div style="width:${Math.min(100,c().savings/goal.cost*100)}%"></div></div>${button('存一些星星','save-stars',available<=0?'disabled':'')}${c().savings?button('拿回可用星星','release-stars'):''}<p class="muted">準備兌換時，先拿回可用星星，再提出申請。</p>`:'<p>在下方選「設為目標」，練習為期待的事情存星星。</p>'}</div></div><div class="section"><h2>現實獎勵</h2><div class="grid">${state.rewards.filter(r=>r.active!==false).map(r=>`<article class="card"><span class="icon">${esc(r.icon)}</span><h3>${esc(r.name)}</h3><p>⭐ ${r.cost}</p><button data-goal="${r.id}" class="wide">${c().goal===r.id?'✓ 我的目標':'🐷 設為目標'}</button><button data-reward="${r.id}" class="wide primary" ${available<r.cost?'disabled':''}>${available<r.cost?'可用星星還差 '+(r.cost-available):'申請兌換'}</button></article>`).join('')||'<div class="empty">家長正在準備家裡的獎勵約定。</div>'}</div></div><div class="section"><h2>兌換紀錄</h2>${history(c().redemptions.map(r=>({title:r.icon+' '+r.name,date:r.date,text:`⭐ ${r.cost} · ${r.status==='pending'?'等家長確認（尚未使用）':r.status==='approved'?'已確認，和家長安排時間':'已取消，沒有使用星星'}`})))}</div>`},
 world(){const value=c().growth,level=value>=200?3:value>=80?2:value>=20?1:0;return `<div class="hero"><h2>🌳 我的小小世界</h2><p>🌱 成長不會花掉。🪙 金幣可以邀請朋友、添一點風景。</p></div><div class="island"><span class="cloud">☁️　☀️</span><span class="tree">${['🌱','🌿','🌳','🌳'][level]}</span><div class="animals">${c().worldItems.map(id=>G.worldItems.find(x=>x.id===id)?.icon||'').join(' ')}</div><h2>${['一顆新芽','綠意發芽','樹下的朋友','溫暖的小島'][level]}</h2><p>已累積 🌱 ${value} · 休息也不會倒退</p></div><div class="section"><h2>🪙 世界收藏 · 可用 ${c().coins} 金幣</h2><div class="grid">${G.worldItems.map(x=>`<article class="card"><span class="icon">${x.icon}</span><h3>${x.name}</h3><p>🪙 ${x.cost}</p><button class="wide primary" data-world="${x.id}" ${c().worldItems.includes(x.id)||c().coins<x.cost?'disabled':''}>${c().worldItems.includes(x.id)?'✓ 已在我的世界':c().coins<x.cost?'慢慢累積金幣':'加入我的世界'}</button></article>`).join('')}</div></div>`}
};
function parentView(){const d=c(),pending=d.completions.filter(x=>x.status==='pending'),requests=d.redemptions.filter(x=>x.status==='pending');return `<div class="hero"><h2>今日陪伴</h2><p>今天完成 ${d.completions.filter(x=>x.date===G.day()&&x.status==='approved').length} 件 · 任務待確認 ${pending.length} · 兌換待確認 ${requests.length}</p><small>只看目前選擇的孩子，不做兄弟姊妹比較。</small></div><h2>待確認</h2><div class="history">${pending.map(x=>`<div class="entry row"><div><strong>${esc(x.title)}</strong><small>${x.date} · ⭐ ${x.stars}　🪙 ${x.coins||0}　🌱 ${x.growth}</small></div><button class="primary" data-approve-task="${x.id}">確認完成</button></div>`).join('')}${requests.map(x=>`<div class="entry row"><div><strong>${esc(x.name)}</strong><small>${x.date} · 申請時約定 ⭐ ${x.cost}</small></div><div><button data-cancel-reward="${x.id}">取消申請</button> <button class="primary" data-approve-reward="${x.id}">確認兌換</button></div></div>`).join('')}${!pending.length&&!requests.length?'<div class="empty">目前沒有待確認事項 🍃</div>':''}</div><div class="section row"><h2>任務與點數</h2>${button('＋ 新增任務','add','class="primary"')}</div><p class="muted">調整只影響下一次完成；已取得的點數與已送出的申請保持原約定。</p><div class="history">${d.tasks.map(t=>`<div class="entry row"><div><strong>${esc(t.icon)} ${esc(t.title)}</strong><small>${t.type} · ⭐ ${t.stars} · 🪙 ${t.coins||0} · 🌱 ${t.growth}</small></div><button data-edit-task="${t.id}">編輯</button></div>`).join('')}</div><div class="section row"><h2>家庭獎勵約定</h2>${button('＋ 新增獎勵','add-reward','class="primary"')}</div><p class="muted">適用三位孩子。預設品項只是範例，可以改名稱、星星或暫停。不設定星星與現金的通用換算。</p><div class="history">${state.rewards.map(r=>`<div class="entry row"><div><strong>${esc(r.icon)} ${esc(r.name)}</strong><small>⭐ ${r.cost} · ${r.active===false?'已暫停':'可兌換'}</small></div><button data-edit-reward="${r.id}">編輯約定</button></div>`).join('')}</div><div class="section card"><h2>❤️ 今天被我看見了</h2><p>寫下具體行動，不評分、不給星星。</p><form id="seen-form"><label for="seen">我看見了……</label><textarea id="seen" maxlength="200" required></textarea><button class="primary">收進成長護照</button></form></div><div class="section"><h2>陪伴的小提醒</h2><div class="hero">先聽孩子的感受，再一起想辦法。不要求立刻平靜，也不以獎勵交換情緒。</div><h2>孩子的成長紀錄</h2>${history(d.records)}</div>`}
function pinDialog(){modal('<h2>🔒 家長模式</h2><p>原型預設 PIN：<strong>1234</strong>。僅防誤觸。</p><form id="pin-form"><label for="pin">輸入 PIN</label><input id="pin" type="password" inputmode="numeric" maxlength="4" required autocomplete="off"><p id="pin-error" class="error" role="alert"></p><div class="actions"><button type="button" data-action="close">返回</button><button class="primary">進入</button></div></form>')}
function taskDialog(id){let t=c().tasks.find(x=>x.id===id);if(!t||G.status(c(),t))return;modal(`<div class="celebrate"><div class="icon">${esc(t.icon)}</div><h2>${esc(t.title)}</h2><p>${t.id==='bag'?'課本、鉛筆盒、水壺，都準備好了嗎？':'先在生活裡試一試，做好再回來告訴我。'}</p><div class="actions">${button('還沒，回去看看','close')}<button class="primary" data-complete="${id}">✓ 我完成了</button></div></div>`)}
function finishDialog(x,learn){modal(`<div class="celebrate"><div class="icon">${learn?'💡':x.status==='pending'?'🌿':'✨'}</div><h2>${learn?'我學會了':x.status==='pending'?'已記下你的努力！':'做到了！'}</h2>${learn?`<div class="hero"><p>${esc(x.learn)}</p><strong>${esc(x.skill)}</strong></div>${button('看看我的收穫 →','show-reward','class="primary"')}`:`<p>${x.status==='pending'?'等家長確認後，獎勵就會加入。':`⭐ +${x.stars}　🪙 +${x.coins||0}　🌱 +${x.growth}`}</p><div class="actions">${button('回到今天','close')}${button('看看成長護照','passport','class="primary"')}</div>`}</div>`);if(learn)celebration=x}
function taskForm(id){const t=id?c().tasks.find(x=>x.id===id):{title:'',type:'每日',stars:10,coins:5,growth:10,skill:'生活自理',learn:'我可以一步一步練習。',important:false,approval:true};if(!t)return;modal(`<h2>${id?'編輯':'新增'}${profile().name}的任務</h2>${!id?'<label for="preset">從預設開始</label><select id="preset"><option value="custom">自訂任務</option><option value="clothes">準備明天的衣服</option><option value="nature">認識一種植物</option><option value="side">專屬支線練習</option></select>':''}<form id="task-form" data-id="${id||''}"><label for="title">名稱</label><input id="title" value="${esc(t.title)}" required maxlength="50"><label for="type">種類${id?'（既有任務不改週期，避免重複領取）':''}</label><select id="type" ${id?'disabled':''}>${['每日','支線','冒險'].map(v=>`<option ${t.type===v?'selected':''}>${v}</option>`).join('')}</select><div class="grid"><div><label for="stars">星星</label><input id="stars" type="number" min="0" max="10000" step="1" value="${t.stars}" required></div><div><label for="coins">金幣</label><input id="coins" type="number" min="0" max="10000" step="1" value="${t.coins||0}" required></div><div><label for="growth">成長值</label><input id="growth" type="number" min="0" max="10000" step="1" value="${t.growth}" required></div></div><label for="skill">學習方向</label><select id="skill">${[...new Set(['生活自理','探索學習','練習與耐心','品格與關懷',t.skill])].map(v=>`<option ${t.skill===v?'selected':''}>${v}</option>`).join('')}</select><p class="muted">品格與關懷不給星星、金幣或成長數值。</p><label for="learn">我學會了</label><input id="learn" value="${esc(t.learn)}" maxlength="100" required><label class="checkline"><input id="important" type="checkbox" ${t.important?'checked':''}>重要成長時刻，每次顯示學習句</label><small>其他任務第一次顯示；冒險任務也會顯示。</small><label class="checkline"><input id="approval" type="checkbox" ${t.approval?'checked':''}>需家長確認</label><div class="actions">${button('取消','close','type="button"')}<button class="primary">儲存任務</button></div></form>`)}
function rewardForm(id){const r=id?state.rewards.find(x=>x.id===id):{name:'',icon:'🎁',cost:100,active:true};if(!r)return;modal(`<h2>${id?'編輯':'新增'}家庭獎勵</h2><form id="reward-form" data-id="${id||''}"><label for="reward-name">獎勵名稱</label><input id="reward-name" value="${esc(r.name)}" maxlength="50" required><label for="reward-icon">圖示</label><select id="reward-icon">${[...new Set([r.icon,'🎁','🍦','🎮','🎡','🍿','🧱','🚲','📚','🧺'])].map(v=>`<option ${v===r.icon?'selected':''}>${v}</option>`).join('')}</select><label for="reward-cost">需要星星（1–100000）</label><input id="reward-cost" type="number" min="1" max="100000" step="1" required value="${r.cost}"><label class="checkline"><input id="reward-active" type="checkbox" ${r.active!==false?'checked':''}>開放兌換</label><p class="muted">新價格適用之後的申請。已送出申請與紀錄保留原價格。</p><div class="actions">${button('取消','close','type="button"')}<button class="primary">儲存約定</button></div></form>`)}
document.addEventListener('click',e=>{
 const b=e.target.closest('button');if(!b||b.disabled)return;const d=b.dataset;
 if(d.child){child=d.child;page='today';emotion=newDraft();close();render();window.scrollTo(0,0);return}
 if(d.page){page=d.page;render();window.scrollTo(0,0);return}
 if(d.mood){emotion.mood=d.mood;render();return}if(d.intensity){emotion.intensity=Number(d.intensity);render();return}if(d.cause){emotion.cause=d.cause;render();return}if(d.tool){emotion.toolId=d.tool;render();return}if(d.after){emotion.after=d.after;render();return}
 if(d.task){taskDialog(d.task);return}
 if(d.complete){const x=change(c=>G.complete(c,d.complete));if(x){if(!x.showLearn)render();finishDialog(x,x.showLearn)}return}
 if(parent&&d.editTask){taskForm(d.editTask);return}if(parent&&d.editReward){rewardForm(d.editReward);return}
 if(d.goal){if(c().goal!==d.goal&&c().savings){modal(`<h2>換一個目標？</h2><p>原本存的 ${c().savings} 顆星會先回到可用星星，總數不變。</p><div class="actions">${button('先不要','close')}<button class="primary" data-confirm-goal="${d.goal}">換這個目標</button></div>`)}else{change(c=>{c.goal=d.goal});render();toast('已設定目標')}return}
 if(d.confirmGoal){change(c=>{c.savings=0;c.goal=d.confirmGoal});close();render();return}
 if(d.reward){const r=state.rewards.find(x=>x.id===d.reward);modal(`<h2>${esc(r.icon)} ${esc(r.name)}</h2><p>申請使用 ⭐ ${r.cost}。家長確認後才使用星星。</p><div class="actions">${button('再想一下','close')}<button class="primary" data-request="${r.id}" data-cost="${r.cost}">確定申請</button></div>`);return}
 if(d.request){let changedPrice=false;const ok=change((c,s)=>{let r=s.rewards.find(x=>x.id===d.request);if(!r||r.cost!==Number(d.cost)){changedPrice=true;return false}return G.requestReward(c,d.request,s.rewards)});close();render();toast(ok?'已送給家長確認':changedPrice?'約定已更新，請重新查看':'可用星星不足或品項已暫停');return}
 if(parent&&d.approveTask){if(change(c=>G.approveTask(c,d.approveTask))){render();toast('已確認，收穫與故事已加入')}return}
 if(parent&&(d.approveReward||d.cancelReward)){const id=d.approveReward||d.cancelReward;if(d.approveReward){const r=c().redemptions.find(x=>x.id===id);modal(`<h2>確認兌換${esc(r.name)}？</h2><p>依申請時約定使用 ⭐ ${r.cost}。請和孩子安排時間。</p><div class="actions">${button('返回','close')}<button class="primary" data-final-reward="${id}">確認使用星星</button></div>`)}else{change(c=>G.resolveReward(c,id,false));render();toast('已取消，沒有使用星星')}return}
 if(parent&&d.finalReward){let ok=change(c=>G.resolveReward(c,d.finalReward,true));close();render();toast(ok?'兌換完成，和孩子一起安排吧':'未完成，請檢查星星與紀錄');return}
 if(d.world){const item=G.worldItems.find(x=>x.id===d.world);modal(`<h2>${item.icon} ${item.name}</h2><p>使用 🪙 ${item.cost} 金幣加入世界。星星與成長值不變。</p><div class="actions">${button('返回','close')}<button class="primary" data-buy-world="${item.id}" ${c().worldItems.includes(item.id)||c().coins<item.cost?'disabled':''}>${c().worldItems.includes(item.id)?'已在我的世界':c().coins<item.cost?'金幣還不夠':'加入我的世界'}</button></div>`);return}
 if(d.buyWorld){let ok=change(c=>G.buyWorld(c,d.buyWorld));close();render();toast(ok?'新的朋友與風景來了！':'目前無法加入，請確認金幣');return}
 switch(d.action){
 case 'close':close();render();break;
 case 'users':parent=false;child=null;emotion=newDraft();close();render();break;
 case 'parent':if(parent){parent=false;child=null;close();render()}else pinDialog();break;
 case 'passport':close();page='growth';render();break;
 case 'show-reward':if(celebration){const x=celebration;render();finishDialog(x,false)}break;
 case 'emotion-next':if(emotion.step===1&&!emotion.mood||emotion.step===2&&!emotion.cause)return;emotion.step++;render();window.scrollTo(0,0);break;
 case 'emotion-back':emotion.step=Math.max(1,emotion.step-1);emotion.after='';render();break;
 case 'tried':case 'not-tried':emotion.practiced=d.action==='tried';emotion.step=4;render();window.scrollTo(0,0);break;
 case 'save-emotion':if(change(c=>G.recordEmotion(c,emotion))){emotion=newDraft();render();toast('已收藏這一小步。不需要立刻變得開心。')}break;
 case 'speak':{const t=G.emotionTools.find(x=>x.id===emotion.toolId);if(!('speechSynthesis'in window)){toast('這個瀏覽器沒有朗讀功能，可以請家人一起讀。');break}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t.name+'。'+t.steps);u.lang='zh-TW';u.rate=.85;speechSynthesis.speak(u);break}
 case 'save-stars':modal(`<h2>🐷 存進我的目標</h2><p>可用 ⭐ ${G.available(c())}。總星星不變，隨時可以拿回。</p><form id="savings-form"><label for="amount">這次存幾顆？</label><input id="amount" type="number" min="1" max="${G.available(c())}" step="1" required value="${Math.min(10,G.available(c()))}"><div class="actions">${button('返回','close','type="button"')}<button class="primary">存好了</button></div></form>`);break;
 case 'release-stars':if(change(c=>G.releaseSavings(c))){render();toast('已回到可用星星，總數不變')}break;
 case 'add':if(parent)taskForm();break;
 case 'add-reward':if(parent)rewardForm();break;
 case 'backup':if(parent){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(state,null,2)],{type:'application/json'}));a.href=url;a.download='成長島備份-'+G.day()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}break;
 }
});
document.addEventListener('submit',e=>{
 e.preventDefault();
 if(e.target.id==='pin-form'){if($('#pin').value==='1234'){parent=true;if(!child)child='brother';close();render()}else $('#pin-error').textContent='PIN 不正確，再試一次。';return}
 if(e.target.id==='savings-form'){const amount=Number($('#amount').value);let ok=change(c=>G.saveForGoal(c,amount));close();render();toast(ok?'星星已存進目標':'沒有存入，請確認可用星星');return}
 if(!parent)return;
 if(e.target.id==='seen-form'){const text=$('#seen').value.trim();if(text&&change(c=>c.records.push({id:G.uid(),date:G.day(),kind:'seen',title:'今天被我看見了 ❤️',skill:'被看見的成長',text}))){render();toast('這個片刻已收進成長護照')}return}
 if(e.target.id==='task-form'){const id=e.target.dataset.id,title=$('#title').value.trim(),learn=$('#learn').value.trim(),skill=$('#skill').value,values=['stars','coins','growth'].map(k=>Number($('#'+k).value));if(!title||!learn||!values.every(n=>Number.isSafeInteger(n)&&n>=0&&n<=10000))return;const t={id:id||G.uid(),title,learn,skill,stars:values[0],coins:values[1],growth:values[2],type:$('#type').value,important:$('#important').checked,approval:$('#approval').checked,icon:c().tasks.find(x=>x.id===id)?.icon||'✨'};if(skill==='品格與關懷')t.stars=t.coins=t.growth=0;if(change(c=>{if(id){const old=c.tasks.find(x=>x.id===id);if(!old)return false;t.type=old.type;Object.assign(old,t)}else c.tasks.push(t)})){close();render();toast('任務已儲存，已取得的點數不變')}return}
 if(e.target.id==='reward-form'){const id=e.target.dataset.id,name=$('#reward-name').value.trim(),cost=Number($('#reward-cost').value);if(!name||!Number.isSafeInteger(cost)||cost<1||cost>100000)return;const r={id:id||G.uid(),name,cost,icon:$('#reward-icon').value,active:$('#reward-active').checked};if(change((c,s)=>{if(id){const old=s.rewards.find(x=>x.id===id);if(!old)return false;Object.assign(old,r)}else s.rewards.push(r)})){close();render();toast('家庭約定已更新，舊申請維持原價格')}}
});
document.addEventListener('change',e=>{
 if(e.target.id==='preset'){const p={clothes:['準備明天的衣服','每日','生活自理','我可以為明天的自己做好準備。'],nature:['認識一種植物','冒險','探索學習','仔細觀察，就能發現新的事物。'],side:[profile().side+'新練習','支線','練習與耐心','多試一次，就多認識自己一點。']}[e.target.value];if(p){['title','type','skill','learn'].forEach((id,i)=>$('#'+id).value=p[i]);['stars','coins','growth'].forEach(id=>{$('#'+id).disabled=false;$('#'+id).value=id==='coins'?5:10})}}
 if(e.target.id==='skill'){const zero=e.target.value==='品格與關懷';['stars','coins','growth'].forEach(id=>{$('#'+id).disabled=zero;if(zero)$('#'+id).value=0})}
});
$('#modal').addEventListener('cancel',()=>{celebration=null;render()});
window.addEventListener('storage',e=>{if(e.key===G.KEY){load();close();render();toast('已更新另一個分頁的紀錄')}});
let lastDay=G.day();setInterval(()=>{if(G.day()!==lastDay){lastDay=G.day();close();render()}},30000);
load();render();
