'use strict';
// Group existing records at display time: no history rewrite or balance migration.
views.growth=function(){return `<div class="hero"><h2>📖 我的成長護照</h2><p>點選一個區塊，看看自己的成長故事。</p></div><div class="grid two passport-grid">${G.passportCategories.map(group=>{const count=c().records.filter(r=>G.categoryOf(r)===group.id).length;return `<button class="card passport-section" data-category="${group.id}" data-passport="${group.id}" aria-haspopup="dialog"><span class="icon">${group.icon}</span><span class="passport-copy"><strong>${group.name}</strong><small>${count} 則故事</small></span><span class="passport-arrow" aria-hidden="true">›</span></button>`}).join('')}</div>`};
const originalRewardView=views.reward;
views.reward=function(){const old=originalRewardView(),ledger=G.starLedger(c()),earned=ledger.filter(x=>x.amount>0).reduce((n,x)=>n+x.amount,0),spent=-ledger.filter(x=>x.amount<0).reduce((n,x)=>n+x.amount,0);return `<div class="hero"><h2>🐷 財商與獎勵</h2><p>獲得 → 儲蓄 → 選擇 → 消費 → 回頭看看</p><small>練習照顧自己的資源。花掉或等待都可以，不用和別人比較。</small></div><section class="section" aria-label="財商小學堂"><h2>💡 財商小學堂</h2><div class="grid">${G.financeLessons.map(l=>{const done=c().records.some(r=>r.sourceKey==='lesson:'+l.id);return `<article class="card"><span class="icon">${l.icon}</span><h3>${l.title}</h3><p>${{resources:'星星、金幣、成長值，各自做什麼？',needs:'我需要它，還是很想要它？',choices:'現在使用，或為更想要的目標等待。'}[l.id]}</p><button class="wide ${done?'':'primary'}" data-lesson="${l.id}">${done?'✓ 再看看':'一起想一想 →'}</button></article>`}).join('')}</div><p class="muted">練習會收進財商護照，不發放星星或金幣。</p></section><section class="section"><h2>📒 星星從哪裡來、用到哪裡？</h2><div class="grid two"><div class="card"><h3>🌟 已記錄的獲得</h3><p class="stat">+${earned} ⭐</p><small>來自已確認完成的任務。情緒與關懷不計價。</small></div><div class="card"><h3>🎁 已確認的使用</h3><p class="stat">${spent} ⭐</p><small>只計家長確認的兌換；儲蓄與申請保留不是支出。</small></div></div><details class="section card"><summary>查看星星收支明細</summary>${ledger.length?`<div class="history">${ledger.slice().reverse().map(x=>`<div class="entry row"><div><strong>${esc(x.title)}</strong><small>${esc(x.date)}</small></div><strong>${x.amount>0?'+':''}${x.amount} ⭐</strong></div>`).join('')}</div>`:'<p>還沒有已確認的星星收支。</p>'}<p class="muted">明細只顯示已有紀錄，不替舊資料猜測來源。實際餘額以「我的星星」為準。</p></details></section><div class="section"><h2>🧺 分配我的資源</h2>${old.slice(old.indexOf('</div>')+6)}</div>`};
let selectedLesson=null;
function lessonDialog(id){const l=G.financeLessons.find(x=>x.id===id);if(!l)return;selectedLesson=id;modal(`<div class="icon" style="font-size:48px">${l.icon}</div><h2>${l.title}</h2><p>${l.question}</p><div class="lesson-options">${l.options.map((o,i)=>`<button data-lesson-choice="${i}">${o}</button>`).join('')}</div><p class="muted">這是想一想的練習，不會動到你的星星。</p><div class="actions">${button('先回去','close')}</div>`)}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;const d=b.dataset;if(d.lesson){lessonDialog(d.lesson);return}if(d.lessonChoice!==undefined){const l=G.financeLessons.find(x=>x.id===selectedLesson),choice=Number(d.lessonChoice);if(!l||!l.options[choice])return;const done=c().records.some(r=>r.sourceKey==='lesson:'+l.id);modal(`<h2>💡 我想到了</h2><p>${l.responses[choice]}</p><div class="hero">${l.id==='resources'?'⭐ 現實獎勵　🪙 世界收藏　🌱 只累積、不花掉':'每個選擇都有得到與暫時放下的事。可以慢慢想，也可以和家人討論。'}</div><div class="actions">${button('返回','close')}${done?'<span class="pill">已收進財商護照</span>':`<button class="primary" data-save-lesson="${l.id}" data-choice="${choice}">收進財商護照</button>`}</div>`);return}if(d.saveLesson){const ok=change(c=>G.finishFinanceLesson(c,d.saveLesson,Number(d.choice)));close();render();toast(ok?'已收進財商護照，點數不變':'這個練習已經收藏過了');return}if(d.passport){const group=G.passportCategories.find(x=>x.id===d.passport);modal(`<h2>${group.icon} ${group.name}成長</h2>${history(c().records.filter(r=>G.categoryOf(r)===group.id))}<div class="actions">${button('回到護照','close')}</div>`)}
});
// Explain the trade-off using the current child's actual available balance before requesting a reward.
document.addEventListener('click',e=>{const b=e.target.closest('[data-reward]');if(!b||b.disabled||parent)return;e.stopImmediatePropagation();const r=state.rewards.find(x=>x.id===b.dataset.reward),available=G.available(c()),goal=state.rewards.find(x=>x.id===c().goal);if(!r)return;modal(`<h2>${esc(r.icon)} ${esc(r.name)}</h2><h3>先想一想我的選擇</h3><div class="hero"><p>現在可用 ⭐ ${available}</p><p>這次使用 ⭐ ${r.cost}</p><strong>確認兌換後可用 ⭐ ${available-r.cost}</strong></div><p>${goal?`目標「${esc(goal.name)}」已存的 ${c().savings} 顆星會保留。`:'現在使用後，留給下一個目標的可用星星會變少。'}</p><p>這是我現在需要的，還是想要的？現在換、先等等，都可以。</p><div class="actions">${button('先等等，繼續存','close')}<button class="primary" data-request="${r.id}" data-cost="${r.cost}">想好了，申請兌換</button></div>`)
},true);
render();
