'use strict';
/* UI for approved scope of specification bundle v0.2.1. */
let parentTab='today',moodDraft=null,rewardEvent=null,depositPreview=null,taskPreview=null;
const oldReadState=readState;
readState=function(){const old=oldReadState();if(old.specVersion>=2&&old.educationVersion===1){G.upgradeEducation(old);localStorage.setItem(G.KEY,JSON.stringify(old));return old;}const raw=JSON.stringify(old),key=G.KEY+(old.specVersion>=2?'-before-education-20261008':old.specVersion===1?'-before-spec-030':'-before-spec-021');if(!localStorage.getItem(key))localStorage.setItem(key,raw);const next=G.upgrade(old);localStorage.setItem(G.KEY,JSON.stringify(next));return next};
profile=function(){return c().profile};
const sb=(label,action,attrs='')=>`<button data-s="${action}" ${attrs}>${label}</button>`;
const optionList=(xs,value)=>xs.map(x=>`<option ${x===value?'selected':''}>${esc(x)}</option>`).join('');
const input=(id,label,value='',attrs='')=>`<label for="${id}">${label}</label><input id="${id}" value="${esc(value)}" ${attrs}>`;
const actions=(html,label='返回')=>`<div class="actions">${button(label,'close','data-keep-label="true"')}${html}</div>`;
function speakText(text){if(!window.speechSynthesis){toast('這個裝置沒有朗讀功能，可以請家人一起讀。');return}speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='zh-TW';u.rate=.85;speechSynthesis.speak(u)}
function userEntry(){return `<main class="shell welcome"><header class="welcome-header"><div class="brand">🏝️ 家庭共同成長系統 <span class="tag">v0.3</span></div>${button('🔒 我是家長','parent')}</header><div class="welcome-title"><div class="island-icon">🏝️</div><h1>今天是誰來到成長島？</h1></div><div class="grid">${G.profiles.map(p=>{const q=state.children[p.id].profile;return `<button class="card role" data-child="${p.id}"><span class="icon">${q.icon}</span><h2>${esc(({brother:"哥哥Ryder",sister:"妹妹Zoe",little:"弟弟Malin"})[p.id])}</h2></button>`}).join('')}</div><p class="footer">規格 v0.3</p></main>`}
render=function(){if(!child){$('#app').innerHTML=userEntry();return}const p=profile();$('#app').innerHTML=`<main class="shell ${page==='today'&&!parent?'today-shell':''}"><header><div class="brand">🏝️ 家庭共同成長系統 <span class="tag">v0.3</span></div><div class="header-actions">${!parent&&page==='world'?sb('✏️ 我的角色','profile'):''}${parent?`<div class="children">${G.profiles.map(x=>`<button data-child="${x.id}" class="${x.id===child?'active':''}">${state.children[x.id].profile.icon} ${esc(state.children[x.id].profile.name)}</button>`).join('')}</div>`:button('↩ 換使用者','users')}${button(parent?'離開家長模式':'🔒 家長','parent')}</div></header><div class="intro row"><div><h1>${parent?(parentTab==='today'?'一起陪孩子長大':esc(p.name)+'的陪伴小幫手'):p.icon+' '+esc(p.name)+'的成長島'}</h1></div>${['world','reward'].includes(page)&&!parent||parent&&parentTab!=='today'?`<div class="balance">⭐ ${parent?c().stars:G.available(c())}${parent?'':' 可用'}　🪙 ${c().coins}　🌱 ${c().growth}${!parent?'　💌 '+c().wishCards:''}</div>`:''}</div><section id="view">${parent?parentScreen():page==='emotion'?emotionScreen():views[page]()}</section><p class="footer">規格 v0.3 · 資料保存在這個瀏覽器，尚未跨裝置同步。${parent?'原型 PIN：1234，僅防誤觸。':''}</p></main><nav aria-label="主要導覽">${(parent?[['today','🏠','今天'],['tasks','🎯','任務'],['growth','📖','成長'],['manage','⚙️','管理']]:[['today','🏠','今天'],['growth','📖','成長'],['accumulation','📈','累積'],['reward','🎁','獎勵'],['world','🌱','世界']]).map(([id,icon,label])=>`<button ${parent?`data-parent-tab="${id}"`:`data-page="${id}"`} class="${(parent?parentTab:page)===id?'active':''}"><span>${icon}</span>${label}</button>`).join('')}</nav>`;const strip=document.querySelector('.mood-scroll');if(strip){const dot=strip.querySelector('.is-today');strip.scrollLeft+=dot.getBoundingClientRect().left-strip.getBoundingClientRect().left-(strip.clientWidth-dot.clientWidth)/2}};
function weekRow(){const today=G.day(),dates=Array.from({length:15},(_,i)=>G.plusDays(today,i-7));return `<div class="mood-scroll" tabindex="0" aria-label="今天及前後各7天心情，可左右滑動"><div class="week-row">${dates.map(d=>{const last=c().emotions.filter(e=>e.date===d).at(-1),can=last||d===today||d===G.plusDays(today,-1);return `<button data-mood-date="${d}" class="day-dot ${d===today?'is-today':''}" ${can?'':'disabled'} aria-label="${d}${last?' 查看心情':' 情緒覺察'}"><small>${d===today?'今天':['日','一','二','三','四','五','六'][new Date(d+'T12:00:00').getDay()]}</small><span>${last?(G.moods.find(x=>x[1]===last.mood)?.[0]||'😊'):'·'}</span><small>${Number(d.slice(5,7))}/${Number(d.slice(-2))}</small></button>`}).join('')}</div></div>`}

views.today=function(){const date=new Date(),daily=c().tasks.filter(t=>t.type==='每日'&&!t.proposed);return `<div class="date-title">${date.toLocaleDateString('zh-TW',{month:'long',day:'numeric',weekday:'long'})}</div>${weekRow()}<p class="quote">每一次小小的嘗試，都在讓你更認識自己。</p>${daily.length&&daily.every(t=>G.status(c(),t)?.status==='approved')?'<p>🌟 今天的事情完成啦！</p>':''}${['每日','每週','每月','支線','冒險'].map(type=>`<section class="task-group"><h2>${{'每日':'☀️ 今天','每週':'🗓️ 這週','每月':'🌙 這個月','支線':'✨ 我的支線','冒險':'🧭 小冒險'}[type]}</h2><div class="compact-tasks">${c().tasks.filter(t=>t.type===type&&!t.proposed).map(t=>{const done=G.status(c(),t);return `<button class="task-tile ${done?'task-done':''}" data-s-task="${t.id}"><span class="task-icon">${esc(t.icon)}</span><span class="task-copy"><strong>${esc(t.title)}</strong>${done?`<small>${done.status==='pending'?'⏳ 等家長確認':'✓ 已完成'}</small>`:''}</span></button>`}).join('')||'<small class="muted">家長可以一起加入適合的任務。</small>'}</div></section>`).join('')}<div class="choices">${sb('＋ 我想做一件事','propose')}<button disabled>🏠 家庭共同成長 · 待開發</button></div>`};
function taskDetail(id){const t=c().tasks.find(t=>t.id===id),done=G.status(c(),t);if(done){modal(`<h2>${esc(t.title)}</h2><p>${done.status==='pending'?'等待家長確認':'這個週期已完成'}</p>${done.date===G.day()&&!done.parentConfirmed&&!(done.approval&&done.status==='approved')?`<p>取消只用來修正誤按，會收回這次獎勵和次數。</p>${actions(`<button data-undo="${done.id}">確認取消完成</button>`,'我再檢查一下')}`:actions('','我再檢查一下')}`);return}modal(`<h2>${esc(t.icon)} ${esc(t.title)}</h2><p>${esc(t.steps||'在生活裡試一試，需要時可以請大人陪你。')}</p>${G.educationFor(t).includes('life')?`<label>這次怎麼做到的？<select id="autonomy-stage"><option value="">先不記錄也可以</option>${optionList(G.autonomyStages,'')}</select></label><small>需要幫忙也是學習，不影響獎勵。</small>`:''}${sb('🔊 聽任務','read-task',`data-id="${id}"`)}<div class="actions">${button(t.type==='冒險'||t.type==='支線'?'我在想想':'我再檢查一下','close','data-keep-label="true"')}<button class="primary" data-s-complete="${id}">✓ 我完成了</button></div>`)}
function learningPopup(title,text,next='close'){modal(`<div class="celebrate"><div class="icon">💡</div><h2>我學會了！</h2><h3>${esc(title)}</h3><p id="learning-sentence">${esc(text)}</p>${sb('🔊 聽聽看','read-learning')}<div class="actions">${sb('知道了！',next,'class="primary"')}</div></div>`)}
function showTaskReward(x){rewardEvent=null;render();modal(`<div class="celebrate"><div class="icon">${x.status==='pending'?'🌿':'✨'}</div><h2>${x.status==='pending'?'已記下你的努力':'做到了！'}</h2><p>${x.status==='pending'?'等家長確認後加入收穫。':`⭐ +${x.stars}　🪙 +${x.coins||0}　🌱 +${x.growth}`}</p>${actions(sb('看看累積','accumulation','class="primary"'))}</div>`)}
views.accumulation=function(){const medals=c().medals,chests=c().chests;return `<div class="page-heading"><h2>📈 每個小步都留下來</h2><p>累積次數與最佳連續紀錄，休息也不會抹掉過去。</p></div>${chests.some(x=>!x.opened)?`<section class="card"><h2>🎁 我的寶箱</h2><div class="choices">${chests.filter(x=>!x.opened).map(x=>`<button data-chest="${x.id}">🎁 打開${x.size==='small'?'小':'大'}寶箱</button>`).join('')}</div></section>`:''}<div class="accumulation-list section">${c().tasks.filter(t=>!t.proposed&&t.skill!=='品格與關懷').map(t=>{const s=G.stats(c(),t),next=G.thresholds(t).find(n=>n>s.count),own=medals.filter(m=>m.taskId===t.id);const target=next||G.thresholds(t).at(-1);return `<article class="accumulation-row"><div class="accumulation-name"><strong>${esc(t.icon)} ${esc(t.title)}</strong><small>最佳連續 ${s.best} ${t.type==='每週'?'週':t.type==='每月'?'月':'天'}</small></div><div class="accumulation-track"><div class="progress-caption"><span>${next?'再 '+(next-s.count)+' 次就到下一枚勳章':'所有里程碑都完成了！'}</span><strong>${s.count} / ${target}</strong></div><progress value="${Math.min(s.count,target)}" max="${target}" aria-label="${esc(t.title)}：累積 ${s.count} 次，里程碑 ${target} 次"></progress></div><span class="accumulation-medals" title="${own.map(m=>esc(m.title)).join('、')}">${own.length?'🏅 '+own.length:'🌱'}</span></article>`}).join('')}</div><p class="muted">勳章不另外給星星。情緒不設次數勳章，品格由家人看見與品格練習共同累積。</p>`};
views.growth=function(){const tile=(icon,name,detail,attrs)=>`<button class="card passport-section" ${attrs} aria-haspopup="dialog"><span class="icon">${icon}</span><span class="passport-copy"><strong>${name}</strong><small>${detail}</small></span><span class="passport-arrow" aria-hidden="true">›</span></button>`;return `<div class="page-heading"><h2>📖 我的成長護照</h2><p>點選一個區塊，看看自己的成長故事。</p></div><div class="grid two passport-grid">${tile('😊','心情紀錄','看看自己的感受','data-s="mood-history"')}${G.passportCategories.map(group=>tile(group.icon,group.name,(group.id==='emotion'?emotionLearningRecords().length:c().records.filter(r=>G.categoryOf(r)===group.id).length)+(group.id==='emotion'?' 個學習':' 則故事'),`data-category="${group.id}" data-passport="${group.id}"`)).join('')}${tile('📚','成長書','收藏一年的故事','data-s="yearbook"')}</div>`};
function emotionScreen(){if(!moodDraft){moodDraft={date:G.day(),step:1,intensity:1,loop_count:0,body_cue:'',cause:'',need:'',strategy:'',after:'',exit_type:'complete'}}const d=moodDraft,short=['開心','平靜','興奮'].includes(d.mood),back=d.date!==G.day();let content='';const picks=(list,key)=>`<div class="choices">${list.map(x=>`<button data-em-key="${key}" data-value="${esc(x)}" class="${d[key]===x?'active':''}">${esc(x)}</button>`).join('')}</div>`;
if(d.step===1)content=`<h2>現在感覺怎麼樣？</h2><div class="choices mood-grid">${G.moods.map(([icon,name])=>`<button data-em-key="mood" data-value="${name}" class="${d.mood===name?'active':''}"><span class="face">${icon}</span>${name}</button>`).join('')}</div>${d.mood==='不知道'?`<h3>身體在告訴我什麼？</h3>${picks(['肚子緊緊的','心跳很快','想哭','身體沒力氣','臉熱熱的','還不知道'],'body_cue')}<small>可以回去選感受，也可以保持「不知道」。</small>`:''}${sb('接著看看','em-next',`class="primary" ${!d.mood?'disabled':''}`)}`;
if(d.step===2)content=`<h2>感覺有多強烈？</h2>${picks(['1','2','3'],'intensity')}<p>1 一點點 · 2 有一些 · 3 很強烈</p>${sb('接著看看','em-next','class="primary"')}`;
if(d.step===3)content=`<h2>發生了什麼？</h2>${picks(G.causes.map(x=>x[1]),'cause')}${sb(short||back?'記下今天的我':'接著看看','em-next',`class="primary" ${!d.cause?'disabled':''}`)}`;
if(d.step===4)content=`<h2>我需要什麼？</h2><p>調節不等於消除情緒。你可以說不要；別人說不要時也要停下來。不舒服時可以離開並找信任的大人。</p>${picks([...G.emotionOptions[d.mood].needs,'找大人說'],'need')}${sb('我可以怎麼做','em-next',`class="primary" ${!d.need?'disabled':''}`)}`;
if(d.step===5)content=`<h2>我可以怎麼做？</h2>${picks([...G.emotionOptions[d.mood].strategies,'找大人說'],'strategy')}${d.strategy?`<div class="hero"><h3>${esc(d.strategy)}</h3><p>${strategyText(d.strategy)}</p></div>`:''}<div class="choices">${sb('我試過了','em-next',`class="primary" ${!d.strategy?'disabled':''}`)}${sb('先這樣就好','em-neutral')}</div>`;
if(d.step===6)content=`<h2>現在感覺如何？</h2>${picks(['好多了','好一點','還是一樣','更強烈'],'after')}<p>還是一樣或更強烈也沒關係，可以直接結束。</p>${['還是一樣','更強烈'].includes(d.after)?d.loop_count<2?sb('再看看我需要什麼','em-loop'):'<div class="hero">🫶 找大人幫忙：請信任的大人陪你，不用自己撐著。</div>':''}${sb('記下這一小步','em-save',`class="primary" ${!d.after?'disabled':''}`)}`;
return `<div class="row"><p>${d.date}${back?' · 補記昨天':''}</p>${sb('先回今天','em-exit')}</div><div class="card">${d.step>1?sb('← 上一步','em-back'):''}${content}</div>`}
function strategyText(s){if(s==='深呼吸')return '照自己的速度慢慢吸氣、吐氣，試幾次，不必立刻平靜。';if(s.includes('跑')||s.includes('離開'))return '先告訴大人，在安全的地方活動或休息。';if(s.includes('抱'))return '可以抱玩偶；抱別人之前，先問彼此願不願意。';if(s.includes('身體'))return '留意肚子、心跳、臉和手，看看身體現在的感覺。';return '照自己的步調試一試，說不清楚也可以找信任的大人陪你。'}
function saveMood(neutral=false){const d={...moodDraft,intensity:Number(moodDraft.intensity),exit_type:neutral?'neutral':moodDraft.date!==G.day()?'backfill':'complete',strategy:moodDraft.strategy||(neutral?'先這樣就好':'')};const x=change(c=>G.recordEmotion(c,d));if(x){moodDraft=null;page='today';render();learningPopup('認識自己的感受',x.learn)}else toast('這一天已有紀錄，或資料尚未填完。')}
function moodHistory(date){const xs=c().emotions.filter(x=>!date||x.date===date);modal(`<h2>😊 ${date||'我的心情紀錄'}</h2>${history(xs.map(x=>({title:x.mood+' · '+x.intensity,date:x.date,text:[x.body_cue,x.cause,x.after?'後來：'+x.after:''].filter(Boolean).join(' · ')})))}${actions('')}`)}
function financeLessonsHTML(){return `<details class="card section" open><summary>💡 財商小學堂</summary><div class="choices">${G.financeLessons.map(l=>`<button data-lesson="${l.id}">${l.icon} ${l.title}</button>`).join('')}</div></details>`}
views.reward=function(){const d=c(),w=G.activeWish(d),target=w?.status==='approved'?w:state.rewards.find(r=>r.id===d.goal),vouchers=d.redemptions.filter(x=>['pending','voucher'].includes(x.status));return `${financeLessonsHTML()}<section class="section"><h2>🎁 我的選擇</h2><p>可用 ⭐ ${G.available(d)} · 願望保留 ${d.savings} · 定期儲蓄 ${G.held(d)}</p><div class="choice-grid">${sb('💌 使用願望卡','choice-wish','class="choice-tile"')}${sb('⭐ 願望保留','choice-reserve','class="choice-tile"')}${sb('🐷 定期儲蓄','choice-deposit','class="choice-tile"')}</div>${vouchers.length?`<section class="section"><h2>🎟️ 我的獎勵券</h2><div class="grid">${vouchers.map(r=>`<div class="card"><h3>${esc(r.icon)} ${esc(r.name)}</h3><p>${r.status==='pending'?'等家長核准':'待使用 · 請家長實際提供後確認'}</p>${!r.wishId?`<button data-refund="${r.id}">${r.status==='pending'?'取消申請':'取消並退還 '+r.cost+' 顆星'}</button>`:''}</div>`).join('')}</div></section>`:''}</section><details class="card section star-shop"><summary>⭐ 星星商店</summary><div class="catalog-grid">${state.rewards.filter(r=>r.active!==false&&(!r.children||r.children.includes(child))).map(r=>`<button class="catalog-item" data-shop="${r.id}"><span class="icon">${esc(r.icon)}</span><strong>${esc(r.name)}</strong><small>⭐ ${r.cost}</small></button>`).join('')}</div></details><details class="card section"><summary>📒 收支及兌換紀錄</summary><div class="grid two"><section><h3>收到星星</h3>${history(G.starLedger(d).filter(x=>x.amount>0).map(x=>({date:x.date,title:x.title,text:'+'+x.amount+' ⭐'+(x.transfer?' · 回到可用星星':'')})))}</section><section><h3>兌換星星</h3>${history(G.starLedger(d).filter(x=>x.transfer&&x.amount<0).map(x=>({date:x.date,title:x.title,text:x.amount+' ⭐ · 轉入保留，尚未花掉'})))}${history(d.redemptions.map(x=>({date:x.date,title:x.name,text:x.cost+' ⭐ · '+({pending:'待核准',voucher:'待使用',used:'已使用',cancelled:'已取消',refunded:'已退款'})[x.status]})))}</section></div></details>`};
views.world=function(){const stage=G.island(c()),next=G.islandStages.find(x=>x.at>Math.max(c().growth,c().worldPeak)),unread=c().mailbox.filter(x=>!x.readAt).length;return `<div class="page-heading"><h2>🏝️ 我是成長島的小主人</h2><p>探索、開拓、建設自己的島嶼。休息也不會倒退。</p></div><button class="card wide" data-s="mailbox">📬 信箱 ${unread?'· '+unread+' 封未讀':''}</button><div class="island"><span class="cloud">☀️ ☁️</span><span class="tree">${stage.scene}</span><div class="animals">${c().legacyScenery||''} ${c().worldItems.map(id=>G.worldItems.find(x=>x.id===id)?.icon||'').join(' ')}</div></div><h2>${stage.name}</h2><p>已累積 🌱 ${c().growth}${next?' · 下一階 '+next.at+'：'+next.name:' · 五階都已開拓'}</p><p class="muted">既有風景與已到達的階段一直保留。</p><div class="section"><h2>🪙 島嶼收藏</h2><div class="catalog-grid">${G.worldItems.map(x=>`<button class="catalog-item" data-world="${x.id}"><span class="icon">${x.icon}</span><strong>${esc(x.name)}</strong><small>🪙 ${x.cost}</small></button>`).join('')}</div></div>`};

function parentScreen(){const d=c();if(parentTab==='tasks')return `<div class="row"><h2>🎯 任務管理</h2>${sb('＋ 新增任務','new-task','class="primary"')}</div><p>每日最多 ${G.limits(d,'每日')} 個 · 每週 ${G.limits(d,'每週')} 個 · 每月 ${G.limits(d,'每月')} 個</p><p class="muted">早晚等時段以獨立任務按鈕建立，各自計次。金幣依努力程度固定為 1／2／3／5，不依年齡。</p><div class="history">${d.tasks.map(t=>`<div class="entry row"><div><strong>${esc(t.icon)} ${esc(t.title)}</strong><small>${t.proposed?'孩子提出，等待設定':t.type} · ⭐ ${t.stars} · 🪙 ${t.coins||0}</small></div><button data-edit-spec-task="${t.id}">${t.proposed?'核准並設定':'編輯'}</button></div>`).join('')}</div>`;
if(parentTab==='growth')return `<div class="row"><h2>📖 成長與陪伴</h2>${sb('❤️ 我看見了','seen-form')}</div>${sb('📚 年度成長書','yearbook')}<h3 class="section">情緒紀錄</h3><p>只用來陪伴，不用來追問或處罰。</p>${history(d.emotions.map(x=>({date:x.date,title:x.mood+' · '+x.intensity,text:[x.cause,x.need,x.strategy||x.tool,x.after,'陪伴提示：'+(x.parentTip||'先接住情緒，再處理行為。')].filter(Boolean).join(' · ')})))}<h3 class="section">成長故事</h3>${history(d.records)}${educationGuide()}<section class="card section"><h3>🪞 今天陪孩子，我也學會了</h3><form id="parent-note"><textarea name="note" maxlength="200" required placeholder="留下一句自己的陪伴心得"></textarea><button class="primary">記下來</button></form>${history(d.parentNotes)}</section>`;
if(parentTab==='manage')return manageScreen();
return parentHome()}
function manageScreen(){const d=c(),earned=G.monthEarned(d);return `<h2>⚙️ 管理</h2><section class="card"><h3>家長定價參考與預算</h3><p>10⭐＝NT$1 僅供家長參考，孩子不顯示換算。</p><p>本月獲得 ${earned}⭐／參考預算 ${d.settings.budget*10}⭐ ${earned>d.settings.budget*10?'· 🔔 超過參考預算，僅提醒，不限制孩子':''}</p><p>目前總星星 ${d.stars}⭐（含保留與定存），現金類獎勵參考約 NT$${(d.stars/10).toFixed(0)}。孩子可能累積後一次兌換。</p><small>不花錢的特權與體驗不占實際現金支出；取得星星仍納入預算提醒。</small><form id="settings-form">${input('budget','每月預算（NT$）',d.settings.budget,'type="number" min="0" max="100000" required')}${input('cap','定期儲蓄上限（星星）',d.settings.depositCap,'type="number" min="200" max="100000" step="100" required')}<label class="checkline"><input id="requires" type="checkbox" ${d.settings.requireApproval?'checked':''}>所有商店兌換需要家長核准</label><p class="muted">定期儲蓄每週單利 1%，是家長負擔的遊戲獎勵成本；5000⭐ 存 12 週多 600⭐。調整上限不影響既有定存。</p><details><summary>寶箱測試值</summary>${['smallStars','smallGrowth','bigStars','bigGrowth'].map((k,i)=>input(k,['小寶箱星星','小寶箱成長','大寶箱星星','大寶箱成長'][i],d.settings[k],'type="number" min="0" max="10000" required')).join('')}</details><button class="primary">儲存設定</button></form></section><section class="section"><div class="row"><h2>獎勵管理</h2>${sb('＋ 新增獎勵','new-reward')}</div>${state.rewards.map(r=>`<div class="entry row"><span>${esc(r.icon)} ${esc(r.name)} · ⭐ ${r.cost} ${r.cash?'· 定價參考 NT$'+r.cost/10:'· 非現金獎勵'} ${r.active===false?'（暫停）':''}</span><button data-edit-spec-reward="${r.id}">編輯</button></div>`).join('')}</section><section class="card section"><h2>資料與角色</h2>${sb('編輯角色','profile')}${button('匯出全部資料','backup')}<label for="import-file">匯入先前匯出的 JSON</label><input id="import-file" type="file" accept="application/json,.json"><p>匯入會取代本機資料；先驗證並預覽，確認前保留目前資料備份。</p></section>`}
function taskEditor(id){const t=id?c().tasks.find(x=>x.id===id):{title:'',type:'每日',effort:1,stars:G.effort(c(),1).stars,coins:2,steps:'',learn:'我可以一步一步練習。',skill:'生活自理',approval:false,icon:'✨'};modal(`<h2>${id?'編輯':'新增'}任務</h2><form id="spec-task-form" data-id="${id||''}">${!id?'<label>預設任務<select id="spec-preset"><option value="">自訂</option><option>早上刷牙</option><option>晚上刷牙</option><option>整理房間</option><option>檢查文具</option><option>閱讀</option><option>到家先洗手</option></select></label>':''}${input('task-name','任務名稱／時段',t.title,'required maxlength="50"')}<label>頻率<select id="task-type" ${id&&!t.proposed?'disabled':''}>${optionList(['每日','每週','每月','支線','冒險'],t.type)}</select></label><label>努力程度<select id="effort">${['很容易','需要一些努力','有挑戰','大挑戰'].map((x,i)=>`<option value="${i}" ${t.effort===i?'selected':''}>${x}</option>`).join('')}</select></label>${input('task-stars','星星（家長可調整）',t.stars,'type="number" min="0" max="10000" required')}${input('task-coins','金幣（依努力程度）',[1,2,3,5][t.effort||0],'type="number" readonly')}<label>學習方向<select id="task-skill">${optionList([...new Set(['生活自理','探索學習','練習與耐心','品格與關懷',t.skill])],t.skill)}</select></label><fieldset><legend>這件事練習什麼？（可複選）</legend>${G.educationMap.map(a=>`<label class="checkline"><input type="checkbox" name="task-ability" value="${a.id}" ${G.educationFor(t).includes(a.id)?'checked':''}>${a.name}</label>`).join('')}</fieldset><label>品格標籤（品格任務使用）<select id="task-value">${optionList(G.characterTags,t.valueTag||'責任')}</select></label>${input('task-learn','學習句',t.learn,'required maxlength="100"')}<label for="task-steps">必要步驟</label><textarea id="task-steps" maxlength="300" required>${esc(t.steps||'先試一試，需要時請家人陪你。')}</textarea><label class="checkline"><input id="task-approval" type="checkbox" ${t.approval?'checked':''}>需要家長確認</label><label class="checkline"><input id="task-important" type="checkbox" ${t.important?'checked':''}>重要成長時刻，每次顯示學習句</label><p>成長值依努力程度 5／10／20／40，重要學習另加 10。品格練習給成長值、金幣及品格進度，不給星星。</p><button class="primary">預覽孩子任務</button></form>`)}
function rewardEditor(id){const r=id?state.rewards.find(x=>x.id===id):{name:'',icon:'🎁',cost:100,active:true,cash:false,children:G.profiles.map(p=>p.id)};modal(`<h2>獎勵設定</h2><form id="spec-reward-form" data-id="${id||''}">${input('r-name','名稱',r.name,'required maxlength="50"')}${input('r-icon','圖示',r.icon,'required maxlength="8"')}${input('r-cost','星星',r.cost,'type="number" min="1" max="100000" required')}<label>類型<select id="r-category">${optionList(['小獎勵','特權','體驗','物品'],r.category||'小獎勵')}</select></label><label><input id="r-active" type="checkbox" ${r.active?'checked':''}>開放兌換</label><label><input id="r-cash" type="checkbox" ${r.cash?'checked':''}>需要現金支出</label><p>哪些孩子看得到</p>${G.profiles.map(p=>`<label><input name="r-child" type="checkbox" value="${p.id}" ${!r.children||r.children.includes(p.id)?'checked':''}>${esc(state.children[p.id].profile.name)}</label>`).join('')}<button class="primary">儲存</button></form>`)}
function profileForm(){const p=profile();modal(`<h2>我的角色</h2><form id="profile-form">${input('p-name','暱稱',p.name,'required maxlength="20"')}<label>頭像<select id="p-icon">${optionList(['🐯','🐰','🐻','🐼','🦊','🐨','🐸','🐱'],p.icon)}</select></label>${input('p-birthday','西元出生年月日（未填時沿用目前年齡段）',p.birthday,'type="date" max="'+G.day()+'" min="2000-01-01"')}<label>興趣<select id="p-side">${optionList(['跆拳道','街舞','滑步車','畫畫','音樂','球類','閱讀','探索'],p.side)}</select></label><p>目前${p.birthday?'年齡 '+G.age(c())+' 歲':p.ageBand==='young'?'沿用大班年齡段':'沿用國小三／四年級年齡段'}。頭像只用預設圖案。</p><button class="primary">儲存角色</button></form>`)}
function depositForm(){if(G.available(c())<200){modal(`<h2>🐷 定期儲蓄</h2><p>還差${200-G.available(c())}星星就可以進行儲蓄囉！</p>`);return}modal(`<h2>🐷 定期儲蓄</h2><p>可用 ⭐ ${G.available(c())} · 可再存 ${Math.max(0,c().settings.depositCap-G.held(c()))}</p><p>願望保留不會變多；定期儲蓄約好等待，到期獲得額外星星。</p><form id="deposit-form">${input('deposit-amount','存入星星（至少 200、每次 100 的倍數）',200,'type="number" min="200" step="100" required')}<label>約定週數<select id="deposit-weeks"><option value="1">1 週</option><option value="2">2 週</option><option value="4">4 週</option><option value="custom">自訂</option></select></label>${input('custom-weeks','自訂週數（1–12）',1,'type="number" min="1" max="12" hidden')}<button class="primary">看看約定內容</button></form>`)}
let importPreview=null;
function download(name,content,type='application/json'){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
function finishMutation(result,message){if(result){close();render();if(message)toast(message)}else toast('沒有完成，請檢查目前資料與可用資源。')}
function showMedals(){const pending=c().medals.filter(m=>!m.announced);if(!pending.length)return;const names=pending.map(m=>m.title);change(c=>{c.medals.forEach(m=>m.announced=true)});modal(`<div class="celebrate"><div class="icon">🏅</div><h2>一步一步，做到了！</h2>${names.map(n=>`<p>${esc(n)}</p>`).join('')}<p>這些努力一直都在。</p>${actions('')}</div>`)}
document.addEventListener('click',e=>{
const b=e.target.closest('button');if(!b||b.disabled)return;const d=b.dataset;
if(d.owner){if(!parent||!G.linkedChildren(state).includes(d.owner)){e.stopImmediatePropagation();return}child=d.owner;}
const handled=['s','sTask','sComplete','undo','chest','moodDate','emKey','shop','refund','parentRedeem','use','editSpecTask','editSpecReward','settle','parentTab'].some(k=>k in d);if(!handled)return;e.stopImmediatePropagation();
if(d.parentTab){if(parent){parentTab=d.parentTab;render();window.scrollTo(0,0)}return}
if(d.sTask){taskDetail(d.sTask);return}
if(d.sComplete){const x=change(c=>G.complete(c,d.sComplete,G.day(),$('#autonomy-stage')?.value||null));if(x){if(x.showLearn){learningPopup(x.title,x.learn+' 正在練習：'+G.educationFor(x).map(id=>G.educationMap.find(a=>a.id===id).name).join('、')+(x.autonomy?'。這次：'+x.autonomy:''),'reward-after-learn');rewardEvent=x}else showTaskReward(x)}return}
if(d.undo){let message='';const ok=change(c=>{const r=G.undo(c,d.undo);message=r.message||'已修正這次誤按';return r.ok});if(ok){close();render()}toast(message);return}
if(d.chest){const x=change(c=>G.openChest(c,d.chest));if(x){render();modal(`<div class="celebrate"><div class="icon">🎁</div><h2>打開寶箱了！</h2><p>⭐ +${x.stars}　🌱 +${x.growth}${x.size==='big'?'　💌 願望卡 +1':''}</p>${actions('')}</div>`)}return}
if(d.moodDate){if(c().emotions.some(x=>x.date===d.moodDate)){moodHistory(d.moodDate);return}if(![G.day(),G.plusDays(G.day(),-1)].includes(d.moodDate))return;moodDraft={date:d.moodDate,step:1,intensity:1,loop_count:0,body_cue:'',cause:'',need:'',strategy:'',after:''};page='emotion';render();return}
if(d.emKey&&moodDraft){const k=d.emKey;if(!['mood','intensity','body_cue','cause','need','strategy','after'].includes(k))return;moodDraft[k]=d.value;if(k==='mood'){moodDraft.need='';moodDraft.strategy='';moodDraft.after=''}render();return}
if(d.shop){const r=state.rewards.find(r=>r.id===d.shop);modal(`<h2>${esc(r.icon)} ${esc(r.name)}</h2><p>現在可用 ⭐ ${G.available(c())}</p><p>${G.available(c())>=r.cost?'使用 ⭐ '+r.cost+'，之後可用 ⭐ '+(G.available(c())-r.cost):'需要 ⭐ '+r.cost+'，目前星星還不夠。'}</p><p>現在換，或再等等，都可以。</p>${actions(sb('想好了，確認兌換','confirm-shop',`class="primary" data-id="${r.id}" data-price="${r.cost}" ${G.available(c())<r.cost?'disabled':''}`))}`);return}
if(d.refund){const r=c().redemptions.find(x=>x.id===d.refund);modal(`<h2>取消${esc(r.name)}？</h2><p>${r.status==='pending'?'取消申請不會扣星。':'尚未使用，可以退還 '+r.cost+' 顆星。'}</p>${actions(sb('確認取消','confirm-refund',`data-id="${r.id}"`))}`);return}
if(d.parentRedeem&&parent){const r=c().redemptions.find(x=>x.id===d.parentRedeem);modal(`<h2>核准兌換？</h2><p>${esc(r.name)} · 使用 ⭐ ${r.cost}</p>${actions(sb('核准並產生獎勵券','confirm-parent-redeem',`data-id="${r.id}" class="primary"`))}`);return}
if(d.use&&parent){modal(`<h2>已實際提供獎勵？</h2><p>確認使用後，這張券不能退款。</p>${actions(sb('確認已使用','confirm-use',`data-id="${d.use}" class="primary"`))}`);return}
if(d.editSpecTask&&parent){taskEditor(d.editSpecTask);return}if(d.editSpecReward&&parent){rewardEditor(d.editSpecReward);return}
if(d.settle){const x=c().deposits.find(x=>x.id===d.settle),mature=G.day()>=x.due;modal(`<h2>${mature?'到期了，接下來呢？':'提前取出？'}</h2><p>本金 ${x.principal} ⭐ 全部回到可用。</p><p>${mature?'這次額外得到 '+x.bonus+' 顆星。':'尚未取得的 '+x.bonus+' 顆成長獎勵不會發放，本金不受影響。'}</p>${actions(sb('取回可用星星','settle-confirm',`data-id="${x.id}" class="primary"`)+(mature?sb('取回後再規劃存多久','settle-renew',`data-id="${x.id}"`):''))}`);return}
switch(d.s){
case 'mailbox':showMailbox();break;
case 'received':showReceived();break;
case 'close':close();render();break;
case 'profile':profileForm();break;
case 'read-task':speakText(c().tasks.find(t=>t.id===d.id)?.steps||'');break;
case 'read-learning':speakText($('#learning-sentence')?.textContent||'');break;
case 'reward-after-learn':if(rewardEvent){const x=rewardEvent;showTaskReward(x)}break;
case 'accumulation':close();page='accumulation';render();showMedals();break;
case 'em-next':if(!moodDraft)break;if(moodDraft.step===3&&(moodDraft.date!==G.day()||['開心','平靜','興奮'].includes(moodDraft.mood))){saveMood();break}moodDraft.step++;render();break;
case 'em-back':moodDraft.step=Math.max(1,moodDraft.step-1);render();break;
case 'em-neutral':saveMood(true);break;
case 'em-save':saveMood();break;
case 'em-loop':if(moodDraft.loop_count<2){moodDraft.loop_count++;moodDraft.step=4;moodDraft.need='';moodDraft.strategy='';moodDraft.after='';render()}break;
case 'em-exit':moodDraft=null;page='today';render();break;
case 'mood-history':moodHistory();break;
case 'propose':modal(`<h2>我想做一件事</h2><p>先告訴家長，一起討論做法與收穫。</p><form id="proposal-form">${input('proposal','我想做……','','required maxlength="50"')}<div class="actions">${button('關閉','close','type="button"')}<button class="primary">送給家長看看</button></div></form>`);break;
case 'new-task':if(parent)taskEditor();break;
case 'save-task-preview':if(parent&&taskPreview){const t=taskPreview;const ok=change(c=>{const old=c.tasks.find(x=>x.id===t.id);if(old){if(old.proposed&&c.tasks.filter(x=>x.type===t.type&&!x.proposed).length>=G.limits(c,t.type))return false;Object.assign(old,t);return true}return G.addTask(c,t)});if(ok){taskPreview=null;close();render();toast('任務已儲存')}else toast('這個週期已達任務上限，請先調整其他任務。')}break;
case 'new-reward':if(parent)rewardEditor();break;
case 'confirm-shop':{const ok=change((c,s)=>{const r=s.rewards.find(x=>x.id===d.id);if(!r||r.cost!==Number(d.price))return false;return G.requestReward(c,d.id,s.rewards)});finishMutation(ok,ok?.status==='pending'?'已送家長確認':'獎勵券已放好');break}
case 'confirm-parent-redeem':if(parent)finishMutation(change(c=>G.resolveReward(c,d.id,true)),'已產生待使用獎勵券');break;
case 'confirm-refund':finishMutation(change(c=>{const r=c.redemptions.find(x=>x.id===d.id);return r?.status==='pending'?G.resolveReward(c,d.id,false):G.refund(c,d.id)}),'已取消，星星已解除保留或退還');break;
case 'confirm-use':if(parent)finishMutation(change(c=>G.useVoucher(c,d.id)),'已確認使用');break;
case 'choice-wish':choiceDialog('wish');break;
case 'choice-reserve':choiceDialog('reserve');break;
case 'choice-deposit':choiceDialog('deposit');break;
case 'wish-form':modal(`<h2>💌 我的願望</h2><form id="wish-form"><label>圖示<select id="wish-icon">${optionList(['🎁','🧱','🚲','🎨','🎡','📚'],'🎁')}</select></label>${input('wish-name','我的願望','','required maxlength="50"')}${input('wish-reason','想要這個願望的原因','','required maxlength="200"')}<p>送出後使用一張願望卡，一次專心規劃一個。</p><button class="primary">送給家長</button></form>`);break;
case 'wish-approve':if(parent)modal(`<h2>設定願望目標</h2><form id="wish-approve-form">${input('wish-cost','需要星星',500,'type="number" min="1" max="100000" required')}<button class="primary">核准並設為目標</button></form>`);break;
case 'wish-discuss':if(parent)finishMutation(change(c=>{const w=G.activeWish(c);if(!w)return false;w.status='discuss';return true}),'已留待一起討論');break;
case 'wish-redeem':modal(`<h2>兌換我的願望？</h2><p>使用保留與可用星星，成為待使用獎勵券。</p>${actions(sb('確認兌換願望','wish-redeem-confirm','class="primary"'))}`);break;
case 'wish-redeem-confirm':finishMutation(change(c=>G.redeemWish(c)),'願望獎勵券已放好');break;
case 'reserve-form':modal(`<h2>留給我的願望</h2><p>保留不會變多，不計入定存上限，隨時可以取消保留。</p><form id="reserve-form">${input('reserve-amount','保留幾顆星',10,'type="number" min="1" step="1" required')}<button class="primary">確認保留</button></form>`);break;
case 'unreserve':modal(`<h2>取消願望保留？</h2><p>${c().savings} 顆星回到可用，總星星不變。</p>${actions(sb('確認拿回','unreserve-confirm'))}`);break;
case 'unreserve-confirm':finishMutation(change(c=>G.releaseSavings(c)),'已回到可用星星');break;
case 'deposit-form':depositForm();break;
case 'deposit-confirm':if(depositPreview){const {amount,weeks}=depositPreview;finishMutation(change(c=>G.deposit(c,amount,weeks)),'儲蓄約定已開始');depositPreview=null}break;
case 'settle-confirm':case 'settle-renew':{const ok=change(c=>G.settle(c,d.id));finishMutation(ok,'本金已回到可用星星'+(ok?.awarded?'，成長獎勵已加入':''));if(ok&&d.s==='settle-renew')depositForm();break}
case 'seen-form':if(parent)modal(`<h2>❤️ 今天被我看見了</h2><form id="spec-seen-form">${input('seen-author','誰看見的','家長','required maxlength="20"')}<label>價值標籤<select id="seen-tag">${optionList(G.characterTags,'善良')}</select></label><label>關聯品格（最多一個，可不選）<select id="seen-related"><option value="">不選</option>${optionList(G.characterTags,'')}</select></label><label>具體發生什麼？<textarea id="seen-text" required maxlength="300"></textarea></label><p>留下故事與 20 成長值，不給星星。</p><button class="primary">傳送卡片並記下成長</button></form>`);break;
case 'adjust-form':if(parent)modal(`<h2>額外星星／修正誤差</h2><p>不用扣星處罰。負值只供修正記帳誤差，不能動用已保留的星星。</p><form id="adjust-form">${input('adjust-amount','增加／修正星星',10,'type="number" min="-100000" max="100000" step="1" required')}${input('adjust-reason','具體原因','','required maxlength="100"')}<button class="primary">預覽調整</button></form>`);break;
case 'adjust-confirm':if(parent)finishMutation(change(c=>G.adjust(c,Number(d.amount),d.reason)),'已記錄調整');break;
case 'yearbook':showYearbook();break;
case 'import-confirm':if(parent&&importPreview){try{const old=localStorage.getItem(G.KEY);localStorage.setItem(G.KEY+'-before-import-'+Date.now(),old);localStorage.setItem(G.KEY,JSON.stringify(importPreview));state=importPreview;importPreview=null;close();render();toast('匯入完成，原資料已另存本機備份')}catch(e){toast('匯入失敗，原資料未取代')}}break;
}
},true);
document.addEventListener('submit',e=>{
const form=e.target,ids=['profile-form','spec-task-form','spec-reward-form','proposal-form','wish-form','wish-approve-form','reserve-form','deposit-form','spec-seen-form','settings-form','adjust-form','yearbook-form','parent-note'];if(!ids.includes(form.id))return;e.preventDefault();e.stopImmediatePropagation();const parentOnly=['spec-task-form','spec-reward-form','wish-approve-form','spec-seen-form','settings-form','adjust-form','parent-note'];if(parentOnly.includes(form.id)&&!parent)return;
if(form.id==='profile-form'){const name=$('#p-name').value.trim(),birthday=$('#p-birthday').value,icon=$('#p-icon').value,side=$('#p-side').value;if(!name||birthday>G.day())return;finishMutation(change(c=>{Object.assign(c.profile,{name,birthday,icon,side});return true}),'角色已更新');return}
if(form.id==='proposal-form'){const title=$('#proposal').value.trim();if(!title)return;finishMutation(change(c=>{if(c.tasks.filter(t=>t.proposed).length>=10)return false;c.tasks.push({id:G.uid(),title,icon:'✨',type:'每日',proposed:true,stars:0,coins:0,effort:1,skill:'生活自理',learn:'我可以練習自己規劃。',steps:'和家長討論怎麼開始。'});return true}),'已送給家長');return}
if(form.id==='spec-task-form'){const id=form.dataset.id,old=c().tasks.find(t=>t.id===id),effort=Number($('#effort').value),skill=$('#task-skill').value,t={id:id||G.uid(),title:$('#task-name').value.trim(),icon:old?.icon||'✨',type:old&&!old.proposed?old.type:$('#task-type').value,effort,stars:Number($('#task-stars').value),coins:Number($('#task-coins').value),growth:[5,10,20,40][effort],skill,steps:$('#task-steps').value.trim(),learn:$('#task-learn').value.trim(),approval:$('#task-approval').checked,important:$('#task-important').checked,proposed:false};if(!t.title||!t.steps||!t.learn||![t.stars,t.coins].every(x=>Number.isSafeInteger(x)&&x>=0&&x<=10000))return;t.coins=[1,2,3,5][effort];t.abilities=[...document.querySelectorAll('[name="task-ability"]:checked')].map(x=>x.value);if(!t.abilities.length)t.abilities=G.educationFor(t);t.valueTag=$('#task-value').value;if(skill==='品格與關懷'){t.stars=0;t.abilities=[...new Set([...t.abilities,'values'])];}taskPreview=t;modal(`<h2>孩子會看到</h2><button class="task-tile">${t.icon} ${esc(t.title)}</button><p>${esc(t.steps)}</p><p>${esc(t.learn)}</p>${actions(sb('確認儲存','save-task-preview','class="primary"'))}`);return}
if(form.id==='spec-reward-form'){const id=form.dataset.id,r={id:id||G.uid(),name:$('#r-name').value.trim(),icon:$('#r-icon').value,cost:Number($('#r-cost').value),category:$('#r-category').value,cash:$('#r-cash').checked,active:$('#r-active').checked,children:[...document.querySelectorAll('[name="r-child"]:checked')].map(x=>x.value)};if(!r.name||!Number.isSafeInteger(r.cost)||r.cost<1||r.cost>100000)return;finishMutation(change((c,s)=>{const old=s.rewards.find(x=>x.id===id);if(old)Object.assign(old,r);else s.rewards.push(r);return true}),'獎勵已儲存');return}
if(form.id==='wish-form'){finishMutation(change(c=>G.makeWish(c,$('#wish-name').value,$('#wish-reason').value,$('#wish-icon').value)),'已送出願望');return}
if(form.id==='wish-approve-form'){finishMutation(change(c=>G.approveWish(c,G.activeWish(c)?.id,Number($('#wish-cost').value))),'願望已設為目標');return}
if(form.id==='reserve-form'){finishMutation(change(c=>G.saveForGoal(c,Number($('#reserve-amount').value))),'星星已留給願望');return}
if(form.id==='deposit-form'){const amount=Number($('#deposit-amount').value),weeks=$('#deposit-weeks').value==='custom'?Number($('#custom-weeks').value):Number($('#deposit-weeks').value);if(!Number.isInteger(amount)||amount<200||amount%100||!Number.isInteger(weeks)||weeks<1||weeks>12||G.held(c())+amount>c().settings.depositCap||amount>G.available(c())){toast('請確認金額、週數、可用星星與儲蓄上限。');return}depositPreview={amount,weeks};const threshold=G.age(c())<8?2:4;modal(`<h2>我的儲蓄約定</h2><p>存 ${amount} ⭐ · 等 ${weeks} 週</p><p>到期多 ${amount/100*weeks} ⭐，可取回 ${amount+amount/100*weeks} ⭐。</p>${weeks>threshold?`<div class="hero">這要${G.age(c())<8?'睡 '+weeks*7+' 個晚上':'等 '+weeks+' 週，約 '+weeks*7+' 天'}。你想等這麼久嗎？</div>`:''}<p>提前取出，本金完整拿回，這次尚未取得的成長獎勵不發放。這是遊戲機制。</p>${actions(sb('確認開始','deposit-confirm','class="primary"'))}`);return}
if(form.id==='spec-seen-form'){finishMutation(change(c=>G.seen(c,$('#seen-text').value,$('#seen-tag').value,$('#seen-author').value,$('#seen-related').value)),'成長故事已收好');return}
if(form.id==='settings-form'){const settings={budget:Number($('#budget').value),depositCap:Number($('#cap').value),requireApproval:$('#requires').checked};for(const k of ['smallStars','smallGrowth','bigStars','bigGrowth'])settings[k]=Number($('#'+k).value);if(!Object.entries(settings).filter(([k])=>k!=='requireApproval').every(([,v])=>Number.isSafeInteger(v)&&v>=0&&v<=100000)||settings.depositCap<200||settings.depositCap%100)return;finishMutation(change(c=>{Object.assign(c.settings,settings);return true}),'設定已儲存，現有星星與任務獎勵不變');return}
if(form.id==='adjust-form'){const amount=Number($('#adjust-amount').value),reason=$('#adjust-reason').value.trim();if(!reason||!Number.isSafeInteger(amount)||!amount)return;modal(`<h2>確認${amount>0?'增加':'修正'} ${amount} 顆星？</h2><p>${esc(reason)}</p>${actions(sb('確認調整','adjust-confirm',`data-amount="${amount}" data-reason="${esc(reason)}" class="primary"`))}`);return}
if(form.id==='parent-note'){const text=form.elements.note.value.trim();if(text)finishMutation(change(c=>{c.parentNotes.push({id:G.uid(),date:G.day(),title:'今天陪孩子，我也學會了',text});return true}),'已記下陪伴心得');return}
if(form.id==='yearbook-form'){const year=$('#book-year').value,records=c().records.filter(x=>x.date.startsWith(year));const body=G.passportCategories.map(group=>`<h2>${group.icon} ${group.name}</h2>${records.filter(r=>G.categoryOf(r)===group.id).map(r=>`<article><h3>${esc(r.title)}</h3><small>${esc(r.date)}</small><p>${esc(r.text)}</p></article>`).join('')||'<p>留白也是成長的一部分。</p>'}`).join('');download('成長書-'+year+'.html',`<!doctype html><html lang="zh-Hant"><meta charset="utf-8"><title>${year} 成長書</title><style>body{font-family:system-ui;max-width:800px;margin:40px auto;padding:20px;line-height:1.8}article{break-inside:avoid;border-bottom:1px solid #ddd;padding:12px 0}h2{margin-top:40px}</style><h1>${esc(profile().name)}的 ${year} 成長書</h1>${body}</html>`,'text/html');close();return}
},true);
document.addEventListener('change',async e=>{if(e.target.id==='effort'){const v=G.effort(c(),Number(e.target.value));$('#task-stars').value=$('#task-skill').value==='品格與關懷'?0:v.stars;$('#task-coins').value=v.coins;}if(e.target.id==='task-skill'&&e.target.value==='品格與關懷')$('#task-stars').value=0;if(e.target.id==='spec-preset'){const title=e.target.value;$('#task-name').value=title;$('#task-type').value=title==='整理房間'?'每週':title==='檢查文具'?'每月':'每日';$('#task-steps').value=title==='到家先洗手'?'用肥皂和水清潔雙手，再擦乾。':title.includes('刷牙')?'使用自己的牙刷與牙膏，仔細清潔後清洗牙刷。':'把需要的用品準備好，一步一步完成。'}if(e.target.id==='deposit-weeks'){$('#custom-weeks').hidden=e.target.value!=='custom';const label=document.querySelector('[for="custom-weeks"]');if(label)label.hidden=e.target.value!=='custom'}if(e.target.id==='import-file'&&parent){try{const file=e.target.files[0];if(!file||file.size>10000000)throw Error();const parsed=JSON.parse(await file.text());if(!G.valid(parsed))throw Error();const next=G.upgrade(parsed);if(!validateImport(next))throw Error();importPreview=next;modal(`<h2>匯入預覽</h2><p>包含 ${G.profiles.length} 位孩子、${G.profiles.reduce((n,p)=>n+next.children[p.id].records.length,0)} 則成長紀錄。</p><p>確認後取代本機目前資料，原資料先另存本機備份。</p>${actions(sb('確認取代並匯入','import-confirm','class="primary"'))}`)}catch(err){importPreview=null;toast('檔案不是可用的成長島備份，沒有修改目前資料。')}}});
function validateImport(s){const id=x=>typeof x==='string'&&/^[\w:.-]{1,150}$/.test(x),num=x=>Number.isSafeInteger(x)&&x>=0&&x<=100000000;return validateEducation(s)&&validateSync(s)&&G.valid(s)&&Array.isArray(s.rewards)&&s.rewards.every(r=>id(r.id)&&typeof r.name==='string'&&typeof r.icon==='string'&&num(r.cost)&&r.cost>0&&(!r.children||Array.isArray(r.children)&&r.children.every(x=>G.profiles.some(p=>p.id===x))))&&G.profiles.every(p=>{const d=s.children[p.id];return (!d.savingsTransfers||Array.isArray(d.savingsTransfers)&&d.savingsTransfers.every(x=>id(x.id)&&typeof x.date==='string'&&typeof x.title==='string'&&Number.isSafeInteger(x.amount)&&Math.abs(x.amount)<=100000000&&x.transfer===true))&&d.profile?.id===p.id&&['🐯','🐰','🐻','🐼','🦊','🐨','🐸','🐱'].includes(d.profile.icon)&&typeof d.profile.name==='string'&&typeof d.profile.side==='string'&&[d.stars,d.coins,d.growth,d.savings,d.wishCards,d.worldPeak].every(num)&&['deposits','wishes','medals','chests','adjustments','parentNotes','worldItems','worldPurchases'].every(k=>Array.isArray(d[k]))&&d.tasks.every(t=>id(t.id)&&typeof t.title==='string'&&num(t.stars)&&num(t.coins||0))&&d.completions.every(x=>id(x.id)&&id(x.taskId)&&/^\d{4}-\d{2}-\d{2}$/.test(x.date)&&num(x.stars)&&num(x.growth))&&d.redemptions.every(x=>id(x.id)&&num(x.cost))&&d.deposits.every(x=>id(x.id)&&num(x.principal)&&num(x.bonus)&&['active','matured','early'].includes(x.status))&&d.records.every(x=>typeof x.date==='string'&&typeof x.title==='string')&&d.emotions.every(x=>typeof x.date==='string')&&num(d.settings?.budget)&&num(d.settings?.depositCap)&&['smallStars','smallGrowth','bigStars','bigGrowth'].every(k=>num(d.settings[k]))&&G.available(d)>=0})}
// Check for newly earned medals on arrival at the dedicated accumulation page.
document.addEventListener('click',e=>{if(e.target.closest('[data-page="accumulation"]'))showMedals()});
function ownerAttr(id){return `data-owner="${esc(id)}"`;}
function parentHome(){const ids=G.linkedChildren(state),today=G.day();let todos=[],moods=[],stories=[],summaries=[];for(const id of ids){const d=state.children[id],name=esc(d.profile.name),owner=ownerAttr(id);const row=(title,buttons)=>`<div class="entry row"><div><strong>${name}</strong><p>${esc(title)}</p></div><div class="choices">${buttons}</div></div>`;
for(const x of d.completions.filter(x=>x.status==='pending'))todos.push(row(x.title,`<button ${owner} data-approve-task="${x.id}">確認完成</button>`));
for(const x of d.redemptions.filter(x=>['pending','voucher'].includes(x.status)))todos.push(row(x.name,x.status==='pending'?`<button ${owner} data-parent-redeem="${x.id}">核准</button><button ${owner} data-refund="${x.id}">取消申請</button>`:`<button ${owner} data-use="${x.id}">已實際提供，確認使用</button>`));
for(const x of d.tasks.filter(x=>x.proposed))todos.push(row('孩子想做：'+x.title,`<button ${owner} data-edit-spec-task="${x.id}">設定獎勵與核准</button>`));
const wish=G.activeWish(d);if(wish&&['pending','discuss'].includes(wish.status))todos.push(row('願望：'+wish.name,sb('設定願望目標','wish-approve',owner)+' '+sb('稍後一起討論','wish-discuss',owner)));
for(const m of d.emotions.filter(m=>m.date>=G.plusDays(today,-6)&&m.date<=today&&(!['開心','平靜','興奮'].includes(m.mood)||m.need==='找大人說'))){moods.push(`<article class="entry"><strong>${name} · ${esc(m.date)} · ${esc(m.mood)}</strong><p>${esc(m.parentTip||'先陪著孩子，問問現在需要什麼，不要求立刻改變感受。')}</p><button ${owner} data-care="${m.id}">看看情緒紀錄</button></article>`);}
for(const r of d.records.filter(r=>r.date===today&&r.kind!=='emotion').slice(-3))stories.push(`<article class="entry"><strong>${name} · ${esc(r.title)}</strong><p>${esc(r.text)}</p><button ${owner} data-response="${r.id}">❤️ 回應孩子</button></article>`);
const mood=d.emotions.find(m=>m.date===today);summaries.push(`<article class="card"><h3>${name}</h3><p>${mood?'今天的感受：'+esc(mood.mood):'今天還沒留下心情，慢慢來。'}</p><p>今天留下 ${d.records.filter(r=>r.date===today).length} 則成長故事</p><button ${owner} data-child-detail="${id}">看看孩子的成長</button></article>`);}
return `<section data-home-section="todos"><h2>① 跨孩子統一待辦</h2>${todos.join('')||'<p>目前沒有待處理事項 🍃</p>'}</section><section data-home-section="care" class="section"><h2>② 孩子的情緒照顧</h2><p>今日及近七天的陪伴線索，不評分、不比較，也不要求解釋。</p>${moods.join('')||'<p>目前沒有特別的陪伴線索，有空也可以問問孩子今天過得如何。</p>'}</section><section data-home-section="seen" class="section"><h2>③ 今天值得你看見</h2>${stories.join('')||'<p>等待生活裡真實發生的成長，不需要每天都有重大突破。</p>'}</section><section data-home-section="summary" class="section"><h2>④ 各孩子今日摘要</h2><div class="grid">${summaries.join('')}</div></section><section data-home-section="tip" class="hero section"><h2>⑤ 家長陪伴提示</h2><p>身體、物品和隱私都有界線。先問願不願意，尊重彼此的不要；不舒服可以離開求助，修復不等於強迫道歉。</p>${educationGuide()}<p>${moods.length?'先接住情緒，再處理行為。可以問：「你想要我陪著，還是先安靜一下？」':'試著說出你看見的具體努力，讓孩子知道自己的小步有被看見。'}</p></section><div class="quick-record"><button data-quick-record>＋ 快速記錄</button><span>目前：${esc(profile().name)}</span>${sb('❤️ 我看見了','seen-form')}${sb('＋ 新任務','new-task')}${sb('⭐ 額外星星／修正','adjust-form')}</div>`;}
function showMailbox(){modal(`<h2>📬 信箱</h2>${sb('接收到的卡片','received','class="wide primary"')}${actions('')}`);}
function showReceived(){modal(`<h2>📬 接收到的卡片</h2>${c().mailbox.slice().reverse().map(m=>`<button class="entry wide" data-card="${esc(m.id)}"><strong>${m.readAt?'已讀':'未讀'} · ${esc(m.author)}</strong><small>${esc(m.date)} · ${esc(m.valueTag||'成長回應')}</small><p>${esc(m.content)}</p></button>`).join('')||'<p>家人送來的心意，會留在這裡。</p>'}${actions('')}`);}
const originalAccumulation=views.accumulation;views.accumulation=function(){return '<h2>🏅 成就</h2>'+originalAccumulation()+`<section class="section"><h2>❤️ 品格</h2><p>從練習與家人的看見，慢慢認識自己。不計較數字，也不與別人比較。</p><div class="grid">${G.characterTags.map(tag=>{const badges=c().characterBadges.filter(b=>b.tag===tag);return `<article class="card"><h3>${tag}</h3><p>${badges.map(b=>esc(b.title)+(b.legacy?'（過去的成長紀念）':'')).join('、')||'正在生活裡練習'}</p></article>`;}).join('')}</div></section>`;};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b||b.disabled)return;const d=b.dataset;if(!['care','response','card','quickRecord','quickKind','childDetail'].some(k=>k in d))return;e.stopImmediatePropagation();if(d.card){const m=c().mailbox.find(x=>x.id===d.card);if(!m)return;if(!change(c=>G.markCardRead(c,d.card)))return;render();modal(`<h2>💌 ${esc(m.author)}的卡片</h2><p>${esc(m.date)} · ${esc(m.valueTag)}</p><p>${esc(m.content)}</p><small>來源：${m.sourceType==='seen'?'家人看見':'事件回應'} · ${esc(m.sourceId||'未指定事件')} · 已讀</small>${actions(sb('回到接收到的卡片','received'))}`);return;}if(!parent)return;if(d.owner){if(!G.linkedChildren(state).includes(d.owner))return;child=d.owner;}
if(d.childDetail){parentTab='growth';render();return;}
if(d.care){const m=c().emotions.find(x=>x.id===d.care);if(!m)return;modal(`<h2>${esc(profile().name)}的情緒紀錄</h2>${history([{date:m.date,title:m.mood,text:[m.cause,m.need,m.strategy,m.after,m.parentTip||'先接住情緒，再處理行為。'].filter(Boolean).join(' · ')}])}${actions('')}`);return;}
if(d.response){const r=c().records.find(x=>x.id===d.response);if(!r)return;modal(`<h2>回應${esc(profile().name)}</h2><p>${esc(r.title)} · ${esc(r.date)}</p><form id="response-form" data-source="${esc(r.id)}">${input('response-author','來自','家長','required maxlength="20"')}<label>想對孩子說<textarea id="response-content" maxlength="500" required></textarea></label><button class="primary">送到孩子的信箱</button></form>`);return;}
if('quickRecord' in d){modal(`<h2>＋ 快速記錄</h2><label>這次是哪位孩子？<select id="quick-child">${G.linkedChildren(state).map(id=>`<option value="${id}" ${id===child?'selected':''}>${esc(state.children[id].profile.name)}</option>`).join('')}</select></label><div class="choices">${[['seen','❤️ 我看見了'],['task','🎯 新任務'],['stars','⭐ 額外星星'],['achievement','🏆 重要成就'],['adventure','🔥 冒險任務']].map(([id,label])=>`<button data-quick-kind="${id}">${label}</button>`).join('')}</div>${actions('')}`);return;}
if(d.quickKind){child=$('#quick-child').value;if(d.quickKind==='task'||d.quickKind==='adventure'){taskEditor();if(d.quickKind==='adventure')$('#task-type').value='冒險';return;}if(d.quickKind==='achievement'){modal(`<h2>🏆 記下${esc(profile().name)}的重要成就</h2><form id="achievement-form">${input('achievement-title','這次做到什麼','','required maxlength="80"')}<label>具體故事<textarea id="achievement-text" maxlength="500" required></textarea></label><button class="primary">記下故事並送卡片</button></form>`);return;}close();render();document.querySelector(d.quickKind==='seen'?'[data-s="seen-form"]':'[data-s="adjust-form"]').click();}
},true);
document.addEventListener('submit',e=>{if(!['response-form','character-settings','achievement-form'].includes(e.target.id))return;e.preventDefault();e.stopImmediatePropagation();if(!parent)return;if(e.target.id==='response-form'){const id=e.target.dataset.source,r=c().records.find(x=>x.id===id);if(!r)return;finishMutation(change(c=>G.sendCard(c,{sourceType:'response',sourceId:id,valueTag:r.skill,author:$('#response-author').value,content:$('#response-content').value})),'卡片已送到孩子的信箱');}if(e.target.id==='character-settings')finishMutation(change(c=>G.setCharacterThresholds(c,[0,1,2].map(i=>Number($('#character-tier-'+i).value)))),'徽章門檻已更新');if(e.target.id==='achievement-form'){const title=$('#achievement-title').value.trim(),text=$('#achievement-text').value.trim();if(!title||!text)return;finishMutation(change(c=>{const r={id:G.uid(),date:G.day(),kind:'achievement',title,text,skill:'自信與成長',growthOutcome:'自信／自我效能',abilities:['thinking']};c.records.push(r);return G.sendCard(c,{sourceType:'response',sourceId:r.id,content:text,valueTag:r.skill});}),'重要成就已記下，卡片已送出');}},true);
function validateSync(s){const safeId=x=>typeof x==='string'&&/^[\w:.-]{1,150}$/.test(x);return s.specVersion===2&&s.parent?.id==='parent-local'&&Array.isArray(s.parent.childIds)&&s.parent.childIds.length===3&&new Set(s.parent.childIds).size===3&&s.parent.childIds.every(id=>G.profiles.some(p=>p.id===id))&&G.profiles.every(p=>{const d=s.children?.[p.id];return d&&Array.isArray(d.mailbox)&&d.mailbox.every(m=>safeId(m.id)&&m.childId===p.id&&typeof m.content==='string'&&m.content.length<=500&&typeof m.author==='string'&&typeof m.date==='string'&&(m.readAt===null||typeof m.readAt==='string'))&&Array.isArray(d.characterEvents)&&d.characterEvents.every(x=>typeof x.id==='string'&&typeof x.tag==='string'&&['seen','practice'].includes(x.source))&&Array.isArray(d.characterBadges)&&d.characterBadges.every(x=>typeof x.tag==='string'&&Number.isInteger(x.tier)&&x.tier>=1&&x.tier<=3)&&Array.isArray(d.settings?.characterThresholds)&&d.settings.characterThresholds.length===3&&d.settings.characterThresholds.every((n,i,a)=>Number.isInteger(n)&&n>0&&n<=10000&&(!i||n>a[i-1]))&&typeof d.legacyScenery==='string'&&['','🏡','🌳'].includes(d.legacyScenery);});}
load();render();

function yearbookBody(year){const records=c().records.filter(x=>x.date.startsWith(year));return G.passportCategories.map(group=>`<section class="book-chapter"><h3>${group.icon} ${group.name}</h3>${history(records.filter(r=>G.categoryOf(r)===group.id))}</section>`).join('')}
function showYearbook(year){const years=[...new Set([G.day().slice(0,4),...c().records.map(x=>x.date.slice(0,4))])].sort().reverse();year=year||years[0];modal(`<div class="row"><h2>📚 ${esc(profile().name)}的成長書</h2>${button('返回','close','type="button"')}</div><form id="yearbook-form"><label>年份<select id="book-year">${optionList(years,year)}</select></label><p>每一次嘗試，都留下了自己的故事。</p><div class="yearbook-reading">${yearbookBody(year)}</div><div class="actions">${button('返回','close','type="button"')}<button class="primary">下載成長書</button></div></form>`)}
document.addEventListener('change',e=>{if(e.target.id==='book-year')document.querySelector('.yearbook-reading').innerHTML=yearbookBody(e.target.value)});

function choiceDialog(kind){const d=c(),w=G.activeWish(d),target=w?.status==='approved'?w:state.rewards.find(r=>r.id===d.goal);let content='';if(kind==='wish')content=`<h2>💌 使用願望卡</h2><p>寫下想實現的願望，和家長一起討論。送出用一張卡，一次規劃一個願望。</p><p>還有 ${d.wishCards} 張</p>${w?`<h3>${esc(w.name)}</h3><p>${esc(w.reason)}</p><p>${{pending:'等待家長討論',discuss:'和家長再聊聊',approved:'已設定目標：⭐ '+w.cost,voucher:'等家長實際提供'}[w.status]}</p>${['pending','discuss','approved'].includes(w.status)?`<button data-revise-wish="${w.id}">我想調整願望</button>`:''}${w.status==='approved'?sb('兌換願望','wish-redeem',G.available(d)+d.savings<w.cost?'disabled':''):''}`:sb('開始寫願望','wish-form',d.wishCards<1?'disabled':'')}`;if(kind==='reserve')content=`<h2>⭐ 願望保留</h2><p>把星星留給已設定的願望，避免先花掉。保留的星星不會增加，也可以隨時取回。</p><p>目前保留 ⭐ ${d.savings}</p>${target?`<h3>${esc(target.name)}</h3>${sb('開始保留','reserve-form',G.available(d)<1?'disabled':'')}`:'<p>先使用願望卡，和家長設定目標。</p>'}${d.savings?sb('取消保留','unreserve'):''}`;if(kind==='deposit')content=`<h2>🐷 定期儲蓄</h2><p>至少存 200 星星，每次以 100 為單位。選擇等待的週數，到期取回本金與約定的額外星星；提前取出只取回本金。</p>${G.available(d)<200?`<p>還差${200-G.available(d)}星星就可以進行儲蓄囉！</p>`:sb('開始儲蓄','deposit-form')}${d.deposits.filter(x=>x.status==='active').map(x=>`<div class="entry"><strong>⭐ ${x.principal} · ${x.weeks} 週</strong><small>${x.start} → ${x.due}</small><button data-settle="${x.id}">${G.day()>=x.due?'到期取回':'提前取出'}</button></div>`).join('')}`;modal(content+actions(''))}

function emotionLearningRecords(){const items=[];if(c().emotions.length)items.push({title:'認識我的感受',text:'先說出現在的感受，再用 1、2、3 表達強度。感受沒有好壞。'});const tried=[...new Set(c().emotions.filter(x=>x.after&&x.exit_type!=='neutral').map(x=>x.strategy||x.tool).filter(x=>x&&x!=='先這樣就好'))];for(const method of tried)items.push({title:method,text:strategyText(method)});return items}
function emotionLearningHTML(){const items=emotionLearningRecords();return '<p>我的情緒工具箱：收藏曾經練習的方法，需要時可以再試試。</p>'+ (items.length?'<div class="history">'+items.map(x=>'<article class="entry"><h3>'+esc(x.title)+'</h3><p>'+esc(x.text)+'</p></article>').join('')+'</div>':'<p>從首頁記下心情、試試照顧自己的方法，這裡就會慢慢收藏起來。</p>')}

function educationGuide(){return `<details class="section"><summary>孩子正在發展什麼？我可以怎麼陪？</summary><p>5–10 歲教育地圖；年齡提示不是能力評分。自信／自我效能是能力累積後的成長結果。</p>${G.educationMap.map(a=>`<article class="entry"><h3>${a.name}</h3><p>${a.subs.join('、')}</p><p>5–7 歲：${a.young}<br>8–10 歲：${a.older}</p><p>${a.tip}</p></article>`).join('')}</details>`;}
document.addEventListener('click',e=>{const b=e.target.closest('[data-revise-wish]');if(!b)return;const w=c().wishes.find(w=>w.id===b.dataset.reviseWish);if(!w)return;modal(`<h2>重新想想願望</h2><p>星星會保留，願望保留會回到可用星星。不花新的願望卡，修改後和家長重新討論。</p><form id="revise-wish-form" data-id="${esc(w.id)}">${input('revised-name','現在想要什麼',w.name,'required maxlength="50"')}${input('revised-reason','為什麼改變',w.reason,'required maxlength="200"')}<button class="primary">保存新想法</button></form>${actions('')}`);});
document.addEventListener('submit',e=>{if(e.target.id!=='revise-wish-form')return;e.preventDefault();finishMutation(change(c=>G.reviseWish(c,e.target.dataset.id,$('#revised-name').value,$('#revised-reason').value)),'願望已調整，星星與已取得的成長都保留');});

function validateEducation(s){return s.educationVersion===1&&Object.values(s.children).every(d=>[...d.tasks,...d.completions,...d.records].every(x=>(x.autonomy==null||G.autonomyStages.includes(x.autonomy))&&(!x.abilities||Array.isArray(x.abilities)&&x.abilities.every(id=>G.educationMap.some(a=>a.id===id))))&&d.characterEvents.every(e=>!e.relatedTag||e.source==='seen'&&G.characterTags.includes(e.relatedTag)&&e.relatedTag!==e.tag));}
