/* Spec v0.2.1 domain rules. Extends the legacy model to preserve old data. */
(function(root){
const G=typeof module!=='undefined'?require('./model.js'):root.Growth;
const oldFresh=G.fresh;
const integer=(n,min=0,max=100000000)=>Number.isSafeInteger(n)&&n>=min&&n<=max;
const dateObj=d=>new Date(d+'T12:00:00');
const plusDays=(d,n)=>{const x=dateObj(d);x.setDate(x.getDate()+n);return G.day(x)};
function period(type,date){if(type==='冒險')return 'once';if(type==='每月')return date.slice(0,7);if(type==='每週'){const d=dateObj(date);return plusDays(date,-((d.getDay()+6)%7))}return date}
function age(c,date=G.day()){if(!c.profile?.birthday)return c.profile?.ageBand==='young'?6:9;const b=c.profile.birthday,d=date;return Number(d.slice(0,4))-Number(b.slice(0,4))-(d.slice(5)<b.slice(5)?1:0)}
function limits(c,type){return (age(c)<8?{'每日':5,'每週':2,'每月':1}:{'每日':7,'每週':3,'每月':2})[type]??50}
function effort(c,n){return {stars:(age(c)<8?[8,15,30,60]:[5,10,20,40])[n],growth:[5,10,20,40][n],coins:[1,2,3,5][n]}}
const rewardPresets=[['snack','🍬','小點心',150,'小獎勵',true],['ice','🍦','冰淇淋',400,'小獎勵',true],['music','🎵','選車上要聽的音樂',100,'特權',false],['story','📚','睡前多聽一個故事',100,'特權',false],['park','🛝','公園多玩 30 分鐘',150,'特權',false],['dinner','🍽️','選今天的晚餐',150,'特權',false],['bedtime','🌙','假日前一晚晚睡 15 分鐘',200,'特權',false],['game','🎮','遊戲多 30 分鐘',500,'特權',false],['movie','🎬','選全家電影之夜的電影',300,'體驗',false],['board','🎲','選全家桌遊之夜的遊戲',300,'體驗',false],['bake','🧁','一起做點心',400,'體驗',false],['weekend','🎡','選週末活動',1000,'體驗',false]].map(([id,icon,name,cost,category,cash])=>({id,icon,name,cost,category,cash,active:true,children:G.profiles.map(p=>p.id)}));
function upgrade(s){if(!G.valid(s))throw Error('Invalid source');if(s.specVersion>=1)return upgradeSync(s);const n=G.migrate(s);n.specVersion=1;n.rewards??=[];for(const r of rewardPresets){const old=n.rewards.find(x=>x.id===r.id);if(old){Object.assign(old,{category:r.category,cash:r.cash,children:old.children||r.children});if(old.id==='ice'&&old.cost===300&&old.name==='冰淇淋')old.cost=400}else n.rewards.push({...r})}for(const p of G.profiles){const c=n.children[p.id];c.profile={...p,ageBand:p.id==='little'?'young':'older',birthday:'',...(c.profile||{})};c.settings={budget:200,depositCap:5000,requireApproval:true,smallStars:50,smallGrowth:50,bigStars:100,bigGrowth:100,...c.settings};for(const key of ['deposits','wishes','medals','chests','adjustments','parentNotes'])c[key]??=[];c.wishCards??=3;c.worldPeak=Math.max(c.worldPeak||0,c.growth);c.tasks.forEach(t=>{t.effort??=t.growth<=5?0:t.growth<=10?1:t.growth<=20?2:3;t.steps??=t.id==='bag'?'準備課本、鉛筆盒與水壺，檢查明天會用到的物品。':t.id==='brush'?'用自己的牙刷與牙膏，仔細清潔牙齒，完成後清洗牙刷。':'先在生活裡試一試，需要幫忙時可以請大人陪你。'});c.redemptions.forEach(r=>{if(r.status==='approved')r.status='used'});}
return upgradeSync(n)}
function fresh(){return upgrade(oldFresh())}
function held(c){return c.deposits.filter(x=>x.status==='active').reduce((n,x)=>n+x.principal,0)}
function available(c){return c.stars-G.reserved(c)-(c.savings||0)-held(c)}
function status(c,t,date=G.day()){return c.completions.find(x=>x.status!=='cancelled'&&x.taskId===t.id&&period(t.type,x.date)===period(t.type,date))}
function stats(c,t){const xs=c.completions.filter(x=>x.taskId===t.id&&x.status==='approved'),keys=[...new Set(xs.map(x=>period(t.type,x.date)))].sort();let best=0,run=0,prev;for(const k of keys){let consecutive=prev&&(t.type==='每月'?Number(k.slice(0,4))*12+Number(k.slice(5))===Number(prev.slice(0,4))*12+Number(prev.slice(5))+1:plusDays(prev,t.type==='每週'?7:1)===k);run=consecutive?run+1:1;best=Math.max(best,run);prev=k}return {count:xs.length,best}}
function thresholds(t){return t.type==='每週'?[4,8,12,24]:t.type==='每月'?[3,6,12,24]:[10,25,50,100]}
function medalName(t,i){const match=[[/閱讀/,['小書蟲','閱讀達人','書海探險家','閱讀大師']],[/刷牙/,['亮晶晶新手','護牙小衛士','潔牙達人','護牙大師']],[/書包/,['準備新手','準備小幫手','準備達人','準備大師']],[/玩具/,['收納新手','收納小幫手','收納達人','收納大師']],[/跆拳道/,['小武者','道場新星','道場達人','道場大師']],[/街舞/,['節奏新手','節奏新星','舞台達人','舞台大師']],[/滑步車/,['小小騎士','平衡新星','風速騎士','滑步車大師']]].find(([re])=>re.test(t.title));return (match?.[1]||['起步新星','堅持達人','恆心高手','毅力大師'])[i]}
function chest(c,id,size){if(!c.chests.some(x=>x.id===id))c.chests.push({id,size,opened:false,date:G.day()})}
function milestones(c,t){if(t.skill==='品格與關懷')return [];const earned=[],count=stats(c,t).count;thresholds(t).forEach((n,i)=>{const id=t.id+':'+n;if(count>=n&&!c.medals.some(x=>x.id===id)){const m={id,taskId:t.id,title:medalName(t,i),threshold:n,date:G.day(),announced:false};c.medals.push(m);earned.push(m);if(t.type==='每月'&&i===1||t.type!=='每月'&&i===2)chest(c,id,'small');if(t.type==='每月'&&i===2||t.type!=='每月'&&i===3)chest(c,id,'big')}});return earned}
function grant(c,x){x.status='approved';c.stars+=x.stars;c.coins+=x.coins||0;c.growth+=x.growth;c.worldPeak=Math.max(c.worldPeak||0,c.growth);if(x.skill==='品格與關懷')characterEvent(c,{id:x.id,date:x.date,source:'practice',tag:x.valueTag||'責任',text:x.title});if(x.showLearn)c.records.push({id:G.uid(),sourceId:x.id,date:x.date,kind:'task',title:x.title,skill:x.skill,text:x.learn,parentTip:'描述孩子具體做到了什麼，讓孩子看見自己的努力。'});const t=c.tasks.find(t=>t.id===x.taskId);if(t)milestones(c,t)}
function complete(c,id,date=G.day()){const t=c.tasks.find(x=>x.id===id);if(!t||t.proposed||status(c,t,date))return null;const showLearn=!c.completions.some(x=>x.taskId===id&&x.status!=='cancelled')||t.important||t.type==='冒險';const x={...t,id:G.uid(),taskId:t.id,date,showLearn,baseGrowth:[5,10,20,40][t.effort||0],status:t.approval?'pending':'approved',parentConfirmed:false,spec:1};x.growth=x.baseGrowth+(showLearn?10:0);x.coins=[1,2,3,5][t.effort||0];if(t.skill==='品格與關懷')x.stars=0;c.completions.push(x);if(!t.approval)grant(c,x);return x}
function approveTask(c,id){const x=c.completions.find(x=>x.id===id);if(!x||x.status!=='pending')return false;x.parentConfirmed=true;grant(c,x);return true}
function undo(c,id,date=G.day()){const x=c.completions.find(x=>x.id===id);if(!x||x.date!==date||x.parentConfirmed||x.status==='cancelled'||x.approval&&x.status==='approved')return {ok:false,message:'這筆紀錄需要家長協助，或已不是今天的紀錄。'};if(x.status==='approved'){if(available(c)<x.stars||c.coins<(x.coins||0)||c.growth<x.growth)return {ok:false,message:'這次獎勵已保留或使用，請先解除保留／取消未使用獎勵，再請家長協助修正。'};c.stars-=x.stars;c.coins-=x.coins||0;c.growth-=x.growth;c.records=c.records.filter(r=>r.sourceId!==id)}c.characterEvents?.forEach(e=>{if(e.id===id)e.cancelled=true});x.status='cancelled';return {ok:true}}
function openChest(c,id){const b=c.chests.find(x=>x.id===id);if(!b||b.opened)return false;const prefix=b.size==='small'?'small':'big';b.stars=c.settings[prefix+'Stars'];b.growth=c.settings[prefix+'Growth'];b.opened=true;b.openedAt=G.day();c.stars+=b.stars;c.growth+=b.growth;c.worldPeak=Math.max(c.worldPeak,c.growth);if(b.size==='big')c.wishCards++;return b}
function requestReward(c,id,catalog){const r=catalog.find(x=>x.id===id&&x.active!==false&&(!x.children||x.children.includes(c.profile.id)));if(!r||available(c)<r.cost)return false;const x={...r,id:G.uid(),rewardId:id,date:G.day(),status:c.settings.requireApproval?'pending':'voucher'};c.redemptions.push(x);if(x.status==='voucher'){c.stars-=x.cost;G.financeStory(c,'redemption:'+x.id,'我做了一次選擇：'+x.name,'我使用 '+x.cost+' 顆星，保留自己的成長。')}return x}
function resolveReward(c,id,approve){const x=c.redemptions.find(x=>x.id===id);if(!x||x.status!=='pending')return false;if(approve){if(c.stars-c.savings-held(c)<G.reserved(c))return false;c.stars-=x.cost;x.status='voucher';G.financeStory(c,'redemption:'+x.id,'我做了一次選擇：'+x.name,'我使用 '+x.cost+' 顆星。')}else x.status='cancelled';return true}
function refund(c,id){const x=c.redemptions.find(x=>x.id===id);if(!x||x.status!=='voucher'||x.wishId)return false;x.status='refunded';c.stars+=x.cost;return true}
function useVoucher(c,id){const x=c.redemptions.find(x=>x.id===id);if(!x||x.status!=='voucher')return false;x.status='used';x.usedAt=G.day();if(x.wishId){const w=c.wishes.find(w=>w.id===x.wishId);w.status='fulfilled';if(c.goal===w.id)c.goal=null}return true}
function activeWish(c){return c.wishes.find(w=>w.status!=='fulfilled')}
function makeWish(c,name,reason,icon){if(activeWish(c)||c.wishCards<1||!name.trim()||!reason.trim()||name.length>50||reason.length>200)return false;const w={id:G.uid(),name:name.trim(),reason:reason.trim(),icon,date:G.day(),status:'pending'};c.wishes.push(w);c.wishCards--;return w}
function approveWish(c,id,cost){const w=c.wishes.find(x=>x.id===id);if(!w||!['pending','discuss','approved'].includes(w.status)||!integer(cost,1,100000))return false;w.cost=cost;w.status='approved';c.goal=w.id;return true}
function redeemWish(c){const w=activeWish(c);if(!w||w.status!=='approved'||c.savings+available(c)<w.cost)return false;const use=Math.min(c.savings,w.cost);c.savings-=use;c.stars-=w.cost;w.status='voucher';const x={id:G.uid(),wishId:w.id,name:w.name,icon:w.icon,cost:w.cost,date:G.day(),status:'voucher'};c.redemptions.push(x);G.financeStory(c,'redemption:'+x.id,'我靠近自己的願望：'+w.name,'我規劃並使用 '+w.cost+' 顆星。');return true}
function reserveWish(c,amount){if(!c.goal||!integer(amount,1)||available(c)<amount)return false;c.savings+=amount;G.financeStory(c,'first-saving','我開始為願望保留','我把星星留給期待的事情，保留不會增加額外星星。');return true}
function deposit(c,amount,weeks,now=G.day()){if(!integer(amount,200)||amount%100||!integer(weeks,1,12)||held(c)+amount>c.settings.depositCap||available(c)<amount)return false;const d={id:G.uid(),principal:amount,weeks,bonus:amount/100*weeks,start:now,due:plusDays(now,weeks*7),status:'active'};c.deposits.push(d);return d}
function settle(c,id,now=G.day()){const d=c.deposits.find(x=>x.id===id);if(!d||d.status!=='active')return false;const mature=now>=d.due;d.status=mature?'matured':'early';d.closedAt=now;d.awarded=mature?d.bonus:0;c.stars+=d.awarded;if(mature){G.financeStory(c,'deposit:'+id,'我完成了一次等待','我保留 '+d.principal+' 顆星等待 '+d.weeks+' 週，得到 '+d.bonus+' 顆遊戲成長獎勵。');if(d.weeks>=4)chest(c,'savings-once','big')}return d}
function adjust(c,amount,reason){if(!Number.isSafeInteger(amount)||!amount||Math.abs(amount)>100000||!reason.trim()||amount<0&&available(c)<-amount)return false;c.stars+=amount;c.adjustments.push({id:G.uid(),date:G.day(),amount,title:reason.trim()});return true}
function ledger(c){const a=[];for(const x of c.completions)if(x.status==='approved')a.push({date:x.date,title:x.title,amount:x.stars});for(const r of c.redemptions)if(['voucher','used'].includes(r.status))a.push({date:r.date,title:r.name,amount:-r.cost});for(const b of c.chests)if(b.opened)a.push({date:b.openedAt,title:'成就寶箱',amount:b.stars});for(const d of c.deposits)if(d.awarded)a.push({date:d.closedAt,title:'儲蓄成長獎勵',amount:d.awarded});a.push(...c.adjustments);return a.sort((a,b)=>a.date.localeCompare(b.date))}
const emotionOptions={
'難過':{needs:['抱抱','有人陪我','有人聽我說','哭一下','自己安靜一下'],strategies:['找人抱抱','把事情說出來','抱喜歡的玩偶','畫出來','聽喜歡的音樂']},
'生氣':{needs:['冷靜一下的時間','有人聽我說','把話說清楚','動一動','被公平對待'],strategies:['深呼吸','先離開一下','喝水','跑一跑跳一跳','冷靜後說「我覺得…因為…」']},
'害怕':{needs:['有人陪我','知道我是安全的','抱抱','亮一點的地方','知道接下來會怎樣'],strategies:['找大人','說出我在怕什麼','抱抱','深呼吸','抱喜歡的玩偶']},
'緊張':{needs:['多一點準備時間','有人鼓勵我','知道接下來要做什麼','先練習一下','慢一點'],strategies:['深呼吸','先練習一次','把擔心說出來','喝水','告訴自己「我試試看」']},
'累累':{needs:['休息','睡覺','安靜','喝水或吃東西','事情少一點'],strategies:['躺一下','喝水','告訴大人我累了','做輕鬆的事','今天早點睡']},
'不知道':{needs:['有人陪我想一想','抱抱','安靜一下','我還不知道'],strategies:['看身體感覺提示','找大人聊聊','安靜一下','畫出來']}};
function recordEmotion(c,d,now=G.day()){if(![now,plusDays(now,-1)].includes(d.date)||c.emotions.some(x=>x.date===d.date)||!G.moods.some(x=>x[1]===d.mood)||![1,2,3].includes(d.intensity)||!d.cause||!integer(d.loop_count||0,0,2))return false;const short=['開心','平靜','興奮'].includes(d.mood),back=d.date!==now;if(!short&&!back&&(!d.need||!d.strategy||d.exit_type!=='neutral'&&!['好多了','好一點','還是一樣','更強烈'].includes(d.after)))return false;const lines=short?['我可以留意生活裡讓自己舒服的小事。','我可以把今天的感受分享給信任的人。']:['情緒來的時候，我可以先照顧自己。','所有感受都可以存在，我可以選擇怎麼做。','需要陪伴時，我可以找信任的大人。'];const last=c.emotions.at(-1)?.learn,learn=lines.find(x=>x!==last);const x={...d,id:G.uid(),learn,parentTip:'先接住情緒，再處理行為。這份紀錄用來陪伴，不用來追問或處罰。'};c.emotions.push(x);c.records.push({id:G.uid(),sourceId:x.id,date:d.date,kind:'emotion',title:'我越來越懂自己',skill:'情緒覺察',text:d.mood+' · '+d.cause+'。'+learn});return x}
function seen(c,text,tag,author){if(!text.trim())return false;const id=G.uid(),date=G.day();c.growth+=20;c.worldPeak=Math.max(c.worldPeak,c.growth);c.records.push({id,date,kind:'seen',title:'今天被我看見了 ❤️',skill:tag,text:text.trim(),author,parentTip:'描述具體行為與影響，不用「乖」評價人格。'});characterEvent(c,{id,date,source:'seen',tag,text:text.trim()});sendCard(c,{sourceType:'seen',sourceId:id,valueTag:tag,author:author||'家長',content:text.trim(),date});return true}
function addTask(c,t){if(!t.title.trim()||c.tasks.filter(x=>x.type===t.type&&!x.proposed).length>=limits(c,t.type)||!integer(t.stars)||!integer(t.coins)||!integer(t.effort,0,3))return false;c.tasks.push(t);return true}
function monthEarned(c,month=G.day().slice(0,7)){return ledger(c).filter(x=>x.date.startsWith(month)&&x.amount>0).reduce((n,x)=>n+x.amount,0)}
// v0.3: retain source snapshots and balances; never retroactively grant currency.
const characterTags=['善良','同理','誠實','責任','尊重','感謝','合作','勇氣','獨立'];
const islandStages=[{at:0,name:'初來到小島',scene:'🏝️'},{at:300,name:'建立營地',scene:'⛺ 🔥'},{at:800,name:'建立家園',scene:'🏡'},{at:1500,name:'綠意成長',scene:'🏡 🌳 🌷'},{at:2500,name:'開拓新區域',scene:'🏡 🌳 🗺️'}];
function upgradeSync(s){if(s.specVersion>=2)return s;s.parent={id:'parent-local',childIds:Object.keys(s.children)};for(const c of Object.values(s.children)){c.mailbox??=[];c.characterEvents??=[];c.characterBadges??=[];c.settings.characterThresholds??=[5,10,20];c.legacyScenery??=c.worldPeak>=200?'🏡':c.worldPeak>=80?'🌳':'';for(const r of c.records.filter(r=>r.kind==='seen')){if(!r.id)r.id=G.uid();if(!c.characterEvents.some(e=>e.id===r.id))c.characterEvents.push({id:r.id,date:r.date,source:'seen',tag:r.skill==='感恩'?'感謝':r.skill,text:r.text,legacy:true});if(!c.mailbox.some(m=>m.sourceId===r.id))sendCard(c,{sourceType:'seen',sourceId:r.id,valueTag:r.skill,author:r.author||'家人（舊紀錄未記名）',content:r.text||'',date:r.date});}for(const t of c.tasks){t.previousCoins=t.coins;t.coins=[1,2,3,5][t.effort||0];if(t.skill==='品格與關懷'){t.stars=0;t.valueTag??='責任';}}refreshCharacter(c);}s.specVersion=2;return s;}
function linkedChildren(s){return (s.parent?.childIds||[]).filter(id=>s.children[id]);}
function island(c){return islandStages.filter(x=>x.at<=Math.max(c.growth,c.worldPeak||0)).at(-1);}
function characterProgress(c,tag){const xs=c.characterEvents.filter(e=>!e.cancelled&&e.tag===tag);return {count:xs.length,seen:xs.filter(e=>e.source==='seen').length,practice:xs.filter(e=>e.source==='practice').length};}
function refreshCharacter(c){for(const tag of characterTags){const n=characterProgress(c,tag).count;c.settings.characterThresholds.forEach((at,i)=>{if(n>=at&&!c.characterBadges.some(b=>b.tag===tag&&b.tier===i+1))c.characterBadges.push({id:tag+':'+(i+1),tag,tier:i+1,threshold:at,date:G.day(),title:tag+['小種子','練習家','小達人'][i]});});}}
function characterEvent(c,e){e={...e,tag:e.tag==='感恩'?'感謝':e.tag};if(!c.characterEvents.some(x=>x.id===e.id))c.characterEvents.push(e);refreshCharacter(c);}
function setCharacterThresholds(c,values){if(!Array.isArray(values)||values.length!==3||!values.every((v,i)=>integer(v,1,10000)&&(!i||v>values[i-1])))return false;c.settings.characterThresholds=values;refreshCharacter(c);return true;}
function sendCard(c,data){if(typeof data.content!=='string'||!data.content.trim()||data.content.length>500)return false;const card={id:G.uid(),childId:c.profile.id,sourceType:data.sourceType||'response',sourceId:data.sourceId||null,valueTag:data.valueTag||'',author:data.author||'家長',date:data.date||G.day(),content:data.content.trim(),readAt:null};c.mailbox.push(card);return card;}
function markCardRead(c,id){const card=c.mailbox.find(x=>x.id===id&&x.childId===c.profile.id);if(!card)return false;card.readAt??=new Date().toISOString();return true;}
Object.assign(G,{upgradeSync,linkedChildren,islandStages,island,characterTags,characterProgress,refreshCharacter,setCharacterThresholds,sendCard,markCardRead});
Object.assign(G,{upgrade,fresh,period,plusDays,age,limits,effort,rewardPresets,held,available,status,stats,thresholds,medalName,milestones,complete,approveTask,undo,openChest,requestReward,resolveReward,refund,useVoucher,activeWish,makeWish,approveWish,redeemWish,saveForGoal:reserveWish,deposit,settle,adjust,starLedger:ledger,emotionOptions,recordEmotion,seen,addTask,monthEarned});
if(typeof module!=='undefined')module.exports=G;
})(globalThis);
