/* Spec v0.2.1 domain rules. Extends the legacy model to preserve old data. */
(function(root){
const G=typeof module!=='undefined'?require('./model.js'):root.Growth;
const oldFresh=G.fresh;
const integer=(n,min=0,max=100000000)=>Number.isSafeInteger(n)&&n>=min&&n<=max;
const dateObj=d=>new Date(d+'T12:00:00');
const plusDays=(d,n)=>{const x=dateObj(d);x.setDate(x.getDate()+n);return G.day(x)};
function period(type,date){if(type==='冒險')return 'once';if(type==='每月')return date.slice(0,7);if(type==='每週'){const d=dateObj(date);return plusDays(date,-((d.getDay()+6)%7))}return date}
function age(c,date=G.day()){if(!c.profile?.birthday)return c.profile?.ageBand==='young'?6:9;const b=c.profile.birthday,d=date;return Number(d.slice(0,4))-Number(b.slice(0,4))-(d.slice(5)<b.slice(5)?1:0)}
function limits(c,type){return (age(c)<8?{'每日':5,'每週':2,'每月':1}:{'每日':7,'每週':3,'每月':2})[type]??50}
function effort(c,n){return {stars:(age(c)<8?[8,15,30,60]:[5,10,20,40])[n],growth:[5,10,20,40][n],coins:[1,2,3,5][n]}}
const rewardPresets=[['snack','🍬','小點心',150,'小獎勵',true],['ice','🍦','冰淇淋',400,'小獎勵',true],['music','🎵','選車上要聽的音樂',100,'特權',false],['story','📚','睡前多聽一個故事',100,'特權',false],['park','🛝','公園多玩 30 分鐘',150,'特權',false],['dinner','🍽️','選今天的晚餐',150,'特權',false],['bedtime','🌙','假日前一晚晚睡 15 分鐘',200,'特權',false],['game','🎮','遊戲多 30 分鐘',500,'特權',false],['movie','🎬','選全家電影之夜的電影',300,'體驗',false],['board','🎲','選全家桌遊之夜的遊戲',300,'體驗',false],['bake','🧁','一起做點心',400,'體驗',false],['weekend','🎡','選週末活動',1000,'體驗',false]].map(([id,icon,name,cost,category,cash])=>({id,icon,name,cost,category,cash,active:true,children:G.profiles.map(p=>p.id)}));
function upgrade(s){if(!G.valid(s))throw Error('Invalid source');if(s.specVersion>=1)return upgradeSync(s);const n=G.migrate(s);n.specVersion=1;n.rewards??=[];for(const r of rewardPresets){const old=n.rewards.find(x=>x.id===r.id);if(old){Object.assign(old,{category:r.category,cash:r.cash,children:old.children||r.children});if(old.id==='ice'&&old.cost===300&&old.name==='冰淇淋')old.cost=400}else n.rewards.push({...r})}for(const p of G.profiles){const c=n.children[p.id];c.profile={...p,ageBand:p.id==='little'?'young':'older',birthday:'',...(c.profile||{})};c.settings={budget:200,depositCap:5000,requireApproval:true,smallStars:50,smallGrowth:50,bigStars:100,bigGrowth:100,...c.settings};for(const key of ['deposits','wishes','medals','chests','adjustments','parentNotes'])c[key]??=[];c.wishCards??=3;c.worldPeak=Math.max(c.worldPeak||0,c.growth);c.tasks.forEach(t=>{t.effort??=t.growth<=5?0:t.growth<=10?1:t.growth<=20?2:3;t.steps??=t.id==='bag'?'準備課本、鉛筆盒與水壺，檢查明天會用到的物品。':t.id==='brush'?'用自己的牙刷與牙膏，仔細清潔牙齒，完成後清洗牙刷。':'先在生活裡試一試，需要幫忙時可以請大人陪你。'});c.redemptions.forEach(r=>{if(r.status==='approved')r.status='used'});}
return upgradeSync(n)}
function fresh(){return upgrade(oldFresh())}
function held(c){return c.deposits.filter(x=>x.status==='active').reduce((n,x)=>n+x.principal,0)}
function available(c){return c.stars-G.reserved(c)-(c.savings||0)-held(c)}
function status(c,t,date=G.day()){return c.completions.find(x=>x.status!=='cancelled'&&x.taskId===t.id&&period(t.type,x.date)===period(t.type,date))}
function stats(c,t){const xs=c.completions.filter(x=>x.taskId===t.id&&x.status==='approved'),keys=[...new Set(xs.map(x=>period(t.type,x.date)))].sort();let best=0,run=0,prev;for(const k of keys){let consecutive=prev&&(t.type==='每月'?Number(k.slice(0,4))*12+Number(k.slice(5))===Number(prev.slice(0,4))*12+Number(prev.slice(5))+1:plusDays(prev,t.type==='每週'?7:1)===k);run=consecutive?run+1:1;best=Math.max(best,run);prev=k}return {count:xs.length,best}}
function thresholds(t){return t.type==='每週'?[4,8,12,24]:t.type==='每月'?[3,6,12,24]:[10,25,50,100]}
function medalName(t,i){const match=[[/閱讀/,['小書蟲','閱讀達人','書海探險家','閱讀大師']],[/刷牙/,['亮晶晶新手','護牙小衛士','潔牙達人','護牙大師']],[/書包/,['準備新手','準備小幫手','準備達人','準備大師']],[/玩具/,['收納新手','收納小幫手','收納達人','收納大師']],[/跆拳道/,['小武者','道場新星','道場達人','道場大師']],[/街舞/,['節奏新手','節奏新星','舞台達人','舞台大師']],[/滑步車/,['小小騎士','平衡新星','風速騎士','滑步車大師']]].find(([re])=>re.test(t.title));return (match?.[1]||['起步新星','堅持達人','恆心高手','毅力大師'])[i]}
function chest(c,id,size){if(!c.chests.some(x=>x.id===id))c.chests.push({id,size,opened:false,date:G.day()})}
function milestones(c,t){if(t.skill==='品格與關懷')return [];const earned=[],count=stats(c,t).count;thresholds(t).forEach((n,i)=>{const id=t.id+':'+n;if(count>=n&&!c.medals.some(x=>x.id===id)){const m={id,taskId:t.id,title:medalName(t,i),threshold:n,date:G.day(),announced:false};c.medals.push(m);earned.push(m);if(t.type==='每月'&&i===1||t.type!=='每月'&&i===2)chest(c,id,'small');if(t.type==='每月'&&i===2||t.type!=='每月'&&i===3)chest(c,id,'big')}});return earned}
function grant(c,x){x.status='approved';c.stars+=x.stars;c.coins+=x.coins||0;c.growth+=x.growth;c.worldPeak=Math.max(c.worldPeak||0,c.growth);if(x.skill==='品格與關懷')characterEvent(c,{id:x.id,date:x.date,source:'practice',tag:x.valueTag||'責任',text:x.title});if(x.showLearn)c.records.push({id:G.uid(),sourceId:x.id,date:x.date,kind:'task',title:x.title,skill:x.skill,text:x.learn,abilities:educationFor(x),autonomy:x.autonomy,parentTip:'描述孩子具體做到了什麼，讓孩子看見自己的努力。'});const t=c.tasks.find(t=>t.id===x.taskId);if(t)milestones(c,t)}
function complete(c,id,date=G.day(),autonomy=null){if(autonomy!==null&&!autonomyStages.includes(autonomy))return null;const t=c.tasks.find(x=>x.id===id);if(!t||t.proposed||status(c,t,date))return null;const showLearn=!c.completions.some(x=>x.taskId===id&&x.status!=='cancelled')||t.important||t.type==='冒險';const x={...t,id:G.uid(),taskId:t.id,date,showLearn,baseGrowth:[5,10,20,40][t.effort||0],status:t.approval?'pending':'approved',parentConfirmed:false,spec:1,autonomy,abilities:educationFor(t)};x.growth=x.baseGrowth+(showLearn?10:0);x.coins=[1,2,3,5][t.effort||0];if(t.skill==='品格與關懷')x.stars=0;c.completions.push(x);if(!t.approval)grant(c,x);return x}
function approveTask(c,id){const x=c.completions.find(x=>x.id===id);if(!x||x.status!=='pending')return false;x.parentConfirmed=true;grant(c,x);return true}
function undo(c,id,date=G.day()){const x=c.completions.find(x=>x.id===id);if(!x||x.date!==date||x.parentConfirmed||x.status==='cancelled'||x.approval&&x.status==='approved')return {ok:false,message:'這筆紀錄需要家長協助，或已不是今天的紀錄。'};if(x.status==='approved'){if(available(c)<x.stars||c.coins<(x.coins||0)||c.growth<x.growth)return {ok:false,message:'這次獎勵已保留或使用，請先解除保留／取消未使用獎勵，再請家長協助修正。'};c.stars-=x.stars;c.coins-=x.coins||0;c.growth-=x.growth;c.records=c.records.filter(r=>r.sourceId!==id)}c.characterEvents?.forEach(e=>{if(e.id===id)e.cancelled=true});x.status='cancelled';return {ok:true}}
function openChest(c,id){const b=c.chests.find(x=>x.id===id);if(!b||b.opened)return false;const prefix=b.size==='small'?'small':'big';b.stars=c.settings[prefix+'Stars'];b.growth=c.settings[prefix+'Growth'];b.opened=true;b.openedAt=G.day();c.stars+=b.stars;c.growth+=b.growth;c.worldPeak=Math.max(c.worldPeak,c.growth);if(b.size==='big')c.wishCards++;return b}
function requestReward(c,id,catalog){const r=catalog.find(x=>x.id===id&&x.active!==false&&(!x.children||x.children.includes(c.profile.id)));if(!r||available(c)<r.cost)return false;const x={...r,id:G.uid(),rewardId:id,date:G.day(),status:c.settings.requireApproval?'pending':'voucher'};c.redemptions.push(x);if(x.status==='voucher'){c.stars-=x.cost;G.financeStory(c,'redemption:'+x.id,'我做了一次選擇：'+x.name,'我使用 '+x.cost+' 顆星，保留自己的成長。')}return x}
function resolveReward(c,id,approve){const x=c.redemptions.find(x=>x.id===id);if(!x||x.status!=='pending')return false;if(approve){if(c.stars-c.savings-held(c)<G.reserved(c))return false;c.stars-=x.cost;x.status='voucher';G.financeStory(c,'redemption:'+x.id,'我做了一次選擇：'+x.name,'我使用 '+x.cost+' 顆星。')}else x.status='cancelled';return true}
function refund(c,id){const x=c.redemptions.find(x=>x.id===id);if(!x||x.status!=='voucher'||x.wishId)return false;x.status='refunded';c.stars+=x.cost;return true}
function useVoucher(c,id){const x=c.redemptions.find(x=>x.id===id);if(!x||x.status!=='voucher')return false;x.status='used';x.usedAt=G.day();if(x.wishId){const w=c.wishes.find(w=>w.id===x.wishId);w.status='fulfilled';if(c.goal===w.id)c.goal=null}return true}
function activeWish(c){return c.wishes.find(w=>w.status!=='fulfilled')}
function makeWish(c,name,reason,icon){if(activeWish(c)||c.wishCards<1||!name.trim()||!reason.trim()||name.length>50||reason.length>200)return false;const w={id:G.uid(),name:name.trim(),reason:reason.trim(),icon,date:G.day(),status:'pending'};c.wishes.push(w);c.wishCards--;return w}
function approveWish(c,id,cost){const w=c.wishes.find(x=>x.id===id);if(!w||!['pending','discuss','approved'].includes(w.status)||!integer(cost,1,100000))return false;w.cost=cost;w.status='approved';c.goal=w.id;return true}
function redeemWish(c){const w=activeWish(c);if(!w||w.status!=='approved'||c.savings+available(c)<w.cost)return false;const use=Math.min(c.savings,w.cost);c.savings-=use;c.stars-=w.cost;w.status='voucher';const x={id:G.uid(),wishId:w.id,name:w.name,icon:w.icon,cost:w.cost,date:G.day(),status:'voucher'};c.redemptions.push(x);G.financeStory(c,'redemption:'+x.id,'我靠近自己的願望：'+w.name,'我規劃並使用 '+w.cost+' 顆星。');return true}
function reserveWish(c,amount){if(!c.goal||!integer(amount,1)||available(c)<amount)return false;c.savings+=amount;(c.savingsTransfers??=[]).push({id:G.uid(),date:G.day(),amount:-amount,title:"願望保留",transfer:true});G.financeStory(c,'first-saving','我開始為願望保留','我把星星留給期待的事情，保留不會增加額外星星。');return true}
function releaseSavings(c){if(!c.savings)return false;const amount=c.savings;c.savings=0;(c.savingsTransfers??=[]).push({id:G.uid(),date:G.day(),amount,title:'取消願望保留',transfer:true});return true}
function deposit(c,amount,weeks,now=G.day()){if(!integer(amount,200)||amount%100||!integer(weeks,1,12)||held(c)+amount>c.settings.depositCap||available(c)<amount)return false;const d={id:G.uid(),principal:amount,weeks,bonus:amount/100*weeks,start:now,due:plusDays(now,weeks*7),status:'active'};c.deposits.push(d);return d}
function settle(c,id,now=G.day()){const d=c.deposits.find(x=>x.id===id);if(!d||d.status!=='active')return false;const mature=now>=d.due;d.status=mature?'matured':'early';d.closedAt=now;d.awarded=mature?d.bonus:0;c.stars+=d.awarded;if(mature){G.financeStory(c,'deposit:'+id,'我完成了一次等待','我保留 '+d.principal+' 顆星等待 '+d.weeks+' 週，得到 '+d.bonus+' 顆遊戲成長獎勵。');if(d.weeks>=4)chest(c,'savings-once','big')}return d}
function adjust(c,amount,reason){if(!Number.isSafeInteger(amount)||!amount||Math.abs(amount)>100000||!reason.trim()||amount<0&&available(c)<-amount)return false;c.stars+=amount;c.adjustments.push({id:G.uid(),date:G.day(),amount,title:reason.trim()});return true}
function ledger(c){const a=[];for(const x of c.completions)if(x.status==='approved')a.push({date:x.date,title:x.title,amount:x.stars});for(const r of c.redemptions)if(['voucher','used'].includes(r.status))a.push({date:r.date,title:r.name,amount:-r.cost});for(const b of c.chests)if(b.opened)a.push({date:b.openedAt,title:'成就寶箱',amount:b.stars});for(const d of c.deposits)if(d.awarded)a.push({date:d.closedAt,title:'儲蓄成長獎勵',amount:d.awarded});a.push(...c.adjustments,...(c.savingsTransfers||[]));return a.sort((a,b)=>a.date.localeCompare(b.date))}
const emotionOptions={
'難過':{needs:['抱抱','有人陪我','有人聽我說','哭一下','自己安靜一下'],strategies:['找人抱抱','把事情說出來','抱喜歡的玩偶','畫出來','聽喜歡的音樂']},
'生氣':{needs:['冷靜一下的時間','有人聽我說','把話說清楚','動一動','被公平對待'],strategies:['深呼吸','先離開一下','喝水','跑一跑跳一跳','冷靜後說「我覺得…因為…」']},
'害怕':{needs:['有人陪我','知道我是安全的','抱抱','亮一點的地方','知道接下來會怎樣'],strategies:['找大人','說出我在怕什麼','抱抱','深呼吸','抱喜歡的玩偶']},
'緊張':{needs:['多一點準備時間','有人鼓勵我','知道接下來要做什麼','先練習一下','慢一點'],strategies:['深呼吸','先練習一次','把擔心說出來','喝水','告訴自己「我試試看」']},
'累累':{needs:['休息','睡覺','安靜','喝水或吃東西','事情少一點'],strategies:['躺一下','喝水','告訴大人我累了','做輕鬆的事','今天早點睡']},
'不知道':{needs:['有人陪我想一想','抱抱','安靜一下','我還不知道'],strategies:['看身體感覺提示','找大人聊聊','安靜一下','畫出來']}};
const emotionCareOptions={"難過":[{"label":"我想抱抱","hint":"可以抱抱喜歡的玩偶，或找願意抱抱你的人。"},{"label":"我想有人聽我說","hint":"想說的時候，可以找信任的人慢慢說。"},{"label":"我想安靜一下","hint":"可以到安全、舒服的地方安靜一下。"},{"label":"我想哭一下","hint":"想哭就哭一下，不用急著讓自己不難過。"},{"label":"我想畫下來","hint":"可以把心裡的感覺畫出來，怎麼畫都可以。"},{"label":"我想聽音樂","hint":"可以聽喜歡的音樂，看看自己有什麼感覺。"},{"label":"我還不知道","hint":"還不知道需要什麼也沒關係，可以慢慢來。"}],"生氣":[{"label":"我想冷靜一下","hint":"可以先到安全的地方，安靜休息一下。"},{"label":"我想有人聽我說","hint":"準備好時，可以找信任的人聽你說。"},{"label":"我想被公平對待","hint":"可以先想想，哪件事讓你覺得不公平。"},{"label":"我想把事情說清楚","hint":"準備好了，可以試著說：「我覺得……因為……」"},{"label":"我想動一動","hint":"可以走走或伸展身體，用安全的方法活動。"},{"label":"我想喝點水","hint":"可以先喝點水，讓自己休息一下。"},{"label":"我還不知道","hint":"不知道也沒關係，可以先給自己一點時間。"}],"害怕":[{"label":"我想有人陪我","hint":"可以找讓你安心、能幫助你的大人陪你。"},{"label":"我想確認自己安全","hint":"如果現在不安全，請先找能保護你的人幫忙。"},{"label":"我想抱抱","hint":"可以抱抱玩偶，或找你信任的人抱抱。"},{"label":"我想去亮一點的地方","hint":"如果周圍安全，可以到亮一點的地方。"},{"label":"我想知道接下來會怎樣","hint":"可以問信任的大人，接下來會發生什麼。"},{"label":"我想慢慢呼吸","hint":"如果現在安全，可以試著慢慢呼吸。"},{"label":"我還不知道","hint":"不知道需要什麼也沒關係。需要保護時可以找大人。"}],"緊張":[{"label":"我想慢慢準備","hint":"可以把要做的事分成幾個小步驟。"},{"label":"我想有人鼓勵我","hint":"可以找信任的人，請他陪你或鼓勵你。"},{"label":"我想知道下一步","hint":"可以先問清楚，接下來要做什麼。"},{"label":"我想先練習","hint":"可以先練習一次，不需要馬上做得很好。"},{"label":"我想慢慢呼吸","hint":"可以試著慢慢呼吸，看看有沒有幫助。"},{"label":"我想喝點水","hint":"可以先喝點水，休息一下。"},{"label":"我還不知道","hint":"還不知道也沒關係，可以先慢慢想。"}],"累累":[{"label":"我想休息一下","hint":"可以坐下或躺一下，讓身體休息。"},{"label":"我想安靜一下","hint":"可以到比較安靜的地方，減少吵雜的聲音。"},{"label":"我想喝水或吃點東西","hint":"可以喝水；如果餓了，可以吃點適合的食物。"},{"label":"我想少做一點","hint":"可以找信任的大人，商量哪些事能晚點做。"},{"label":"我想做輕鬆的事","hint":"可以選一件不太費力、自己喜歡的事。"},{"label":"我想早點睡","hint":"可以告訴照顧你的人，今天想早點休息。"},{"label":"我還不知道","hint":"可以先休息一下，慢慢留意身體的感覺。"}],"不知道":[{"label":"我想有人陪我想想","hint":"可以找信任的人，陪你慢慢想。"},{"label":"我想抱抱","hint":"可以抱抱玩偶，或找願意抱抱你的人。"},{"label":"我想安靜一下","hint":"不用現在找到答案，可以先安靜休息。"},{"label":"我想看看身體的感覺","hint":"可以留意心跳、肚子、呼吸和身體的感覺。"},{"label":"我想畫下來","hint":"可以用顏色或圖畫，畫出現在的感覺。"},{"label":"我想慢慢說說看","hint":"可以先說幾個字，不必一次說清楚。"},{"label":"我還不知道","hint":"現在還不知道也沒關係，可以先這樣就好。"}]};
Object.assign(G,{emotionCareOptions});
function recordEmotion(c,d,now=G.day()){if(d.emotionVersion===9)return recordEmotion9(c,d,now);if(![now,plusDays(now,-1)].includes(d.date)||c.emotions.some(x=>x.date===d.date)||!G.moods.some(x=>x[1]===d.mood)||![1,2,3].includes(d.intensity)||!d.cause||!integer(d.loop_count||0,0,2))return false;const short=['開心','平靜','興奮'].includes(d.mood),back=d.date!==now;if(!short&&!back&&(!d.need||!d.strategy||d.exit_type!=='neutral'&&!['好多了','好一點','還是一樣','更強烈'].includes(d.after)))return false;const lines=short?['我可以留意生活裡讓自己舒服的小事。','我可以把今天的感受分享給信任的人。']:['情緒來的時候，我可以先照顧自己。','所有感受都可以存在，我可以選擇怎麼做。','需要陪伴時，我可以找信任的大人。'];const last=c.emotions.at(-1)?.learn,learn=lines.find(x=>x!==last);const x={...d,id:G.uid(),learn,parentTip:'先接住情緒，再處理行為。這份紀錄用來陪伴，不用來追問或處罰。'};c.emotions.push(x);c.records.push({id:G.uid(),sourceId:x.id,date:d.date,kind:'emotion',title:'我越來越懂自己',skill:'情緒覺察',abilities:['emotion','thinking'],text:d.mood+' · '+d.cause+'。'+learn});return x}
const listeners=['我想跟大人說','我不想跟大人說','我想跟小白熊說'];
// Reuse existing learning sentences as the initial fixed-card choices.
const bearSentences=['情緒來的時候，我可以先照顧自己。','所有感受都可以存在，我可以選擇怎麼做。','需要陪伴時，我可以找信任的大人。'];
function recordEmotion9(c,d,now){
 if(![now,plusDays(now,-1)].includes(d.date)||c.emotions.some(x=>x.date===d.date)||!G.moods.some(x=>x[1]===d.mood)||![1,2,3].includes(d.intensity)||!Array.isArray(d.causes)||d.causes.length<1||d.causes.length>2||new Set(d.causes).size!==d.causes.length||!d.causes.every(v=>G.causes.some(x=>x[1]===v))||!listeners.includes(d.listener))return false;
 const short=['開心','平靜','興奮'].includes(d.mood),back=d.date!==now,options=emotionOptions[d.mood];
 if(!short&&!back&&d.exit_type!=='neutral'&&(!options||![...options.needs,...options.strategies,...(emotionCareOptions[d.mood]||[]).map(x=>x.label)].includes(d.careChoice)||!['好多了','好一點','還是一樣','更強烈'].includes(d.after)))return false;
 const learn=short?'我可以留意生活裡讓自己舒服的小事。':bearSentences[0];
 const x={id:G.uid(),date:d.date,emotionVersion:9,mood:d.mood,intensity:d.intensity,body_cue:d.body_cue||'',causes:[...d.causes],cause:d.causes.join('、'),listener:d.listener,careChoice:short||back?'':d.careChoice||'',strategy:short||back?'':d.careChoice||'',need:'',after:short||back?'':d.after||'',exit_type:back?'backfill':d.exit_type==='neutral'?'neutral':'complete',learn,parentTip:d.listener===listeners[1]?'靜默陪伴，不發送一般回覆；若有安全事件，先在現實中保護孩子。':'先接住情緒，再處理行為。紀錄用來陪伴，不用來追問或處罰。'};
 c.emotions.push(x);c.records.push({id:G.uid(),sourceId:x.id,date:x.date,kind:'emotion',title:'我越來越懂自己',skill:'情緒覺察',abilities:['emotion','thinking'],text:x.mood+' · '+x.cause+'。'+learn});return x;
}
function replyEmotion(c,id,{sentence,content}={}){const m=c.emotions.find(x=>x.id===id);if(!m||!listeners.includes(m.listener)||m.listener===listeners[1])return false;const bear=m.listener===listeners[2];if(bear&&!Number.isInteger(sentence))return false;const text=bear?bearSentences[sentence]:content;if(!text)return false;return sendCard(c,{sourceType:bear?'emotion-bear':'emotion-response',sourceId:id,valueTag:'我的心情',author:bear?'小白熊（家人選句）':'家長',content:text});}
Object.assign(G,{listeners,bearSentences,replyEmotion});
function seen(c,text,tag,author,relatedTag=''){tag=tag==='感恩'?'感謝':tag;if(!text.trim()||!characterTags.includes(tag)||relatedTag&&(!characterTags.includes(relatedTag)||relatedTag===tag))return false;const id=G.uid(),date=G.day();c.growth+=20;c.worldPeak=Math.max(c.worldPeak,c.growth);c.records.push({id,date,kind:'seen',title:'今天被我看見了 ❤️',skill:tag,abilities:['values','relationship'],text:text.trim(),author,parentTip:'描述具體行為與影響，不用「乖」評價人格。'});characterEvent(c,{id,date,source:'seen',tag,relatedTag,text:text.trim()});sendCard(c,{sourceType:'seen',sourceId:id,valueTag:tag,author:author||'家長',content:text.trim(),date});return true}
function addTask(c,t){if(!t.title.trim()||c.tasks.filter(x=>x.type===t.type&&!x.proposed).length>=limits(c,t.type)||!integer(t.stars)||!integer(t.coins)||!integer(t.effort,0,3))return false;c.tasks.push(t);return true}
function monthEarned(c,month=G.day().slice(0,7)){return ledger(c).filter(x=>x.date.startsWith(month)&&x.amount>0&&!x.transfer).reduce((n,x)=>n+x.amount,0)}
// v0.3: retain source snapshots and balances; never retroactively grant currency.
const characterTags=['善良','同理','誠實','責任','尊重','感謝','合作','勇氣','獨立'];
const islandStages=[{at:0,name:'初來到小島',scene:'🏝️'},{at:300,name:'建立營地',scene:'⛺ 🔥'},{at:800,name:'建立家園',scene:'🏡'},{at:1500,name:'綠意成長',scene:'🏡 🌳 🌷'},{at:2500,name:'開拓新區域',scene:'🏡 🌳 🗺️'}];
function upgradeSync(s){if(s.specVersion>=2)return upgradeEducation(s);s.parent={id:'parent-local',childIds:Object.keys(s.children)};for(const c of Object.values(s.children)){c.mailbox??=[];c.characterEvents??=[];c.characterBadges??=[];c.settings.characterThresholds??=[5,10,20];c.legacyScenery??=c.worldPeak>=200?'🏡':c.worldPeak>=80?'🌳':'';for(const r of c.records.filter(r=>r.kind==='seen')){if(!r.id)r.id=G.uid();if(!c.characterEvents.some(e=>e.id===r.id))c.characterEvents.push({id:r.id,date:r.date,source:'seen',tag:r.skill==='感恩'?'感謝':r.skill,text:r.text,legacy:true});if(!c.mailbox.some(m=>m.sourceId===r.id))sendCard(c,{sourceType:'seen',sourceId:r.id,valueTag:r.skill,author:r.author||'家人（舊紀錄未記名）',content:r.text||'',date:r.date});}for(const t of c.tasks){t.previousCoins=t.coins;t.coins=[1,2,3,5][t.effort||0];if(t.skill==='品格與關懷'){t.stars=0;t.valueTag??='責任';}}refreshCharacter(c);}s.specVersion=2;return upgradeEducation(s);}
function linkedChildren(s){return (s.parent?.childIds||[]).filter(id=>s.children[id]);}
function island(c){return islandStages.filter(x=>x.at<=Math.max(c.growth,c.worldPeak||0)).at(-1);}
const educationMap=[
{id:'life',name:'🌱生活自主力',subs:['自我照顧','物品管理','環境整理','時間流程','安全健康','主動與適當求助'],young:'和大人一起做一小步，需要時說出幫忙。',older:'規劃自己的流程，知道何時需要求助。',tip:'先問需要哪一點幫忙，再逐步減少提醒。'},
{id:'thinking',name:'🧠思考與選擇力',subs:['發現問題','想出方法','比較選擇','預想結果','做決定','規劃執行','反思調整'],young:'想兩種方法，試一種再看看。',older:'比較代價，做決定並調整方法。',tip:'問「還有什麼方法？」不以選對為目標，不用懲罰代替結果。'},
{id:'emotion',name:'😊情緒調節力',subs:['察覺','命名','強度','原因與需要','表達','調節與求助','回顧調整'],young:'說出感受，和大人找需要的陪伴。',older:'辨認需要，試方法並回顧是否有幫助。',tip:'調節不等於消除情緒，還是難過也可以。'},
{id:'relationship',name:'🤝關係與社會力',subs:['理解他人','表達自己','傾聽理解','界線與尊重','合作協調','衝突修復','求助支持'],young:'練習說不要，也停下來聽別人的不要。',older:'協商身體、物品與隱私界線；不舒服時離開並求助。',tip:'先保護安全與界線，再談修復；不強迫道歉或擁抱。'},
{id:'values',name:'❤️品格與價值力',subs:['善良','同理','誠實','責任','尊重','感謝','合作','勇氣','獨立'],young:'從具體小事認識自己在乎的價值。',older:'想想行動對自己與別人的影響。',tip:'品格不等於聽話，勇氣不等於冒險，獨立不等於不求助。'},
{id:'resources',name:'🐷資源與財務力',subs:['理解有限','選擇取捨','等待延遲','儲蓄累積','分配規劃','目標管理','結果調整'],young:'在現在用與以後用之間選擇。',older:'比較目標與代價，分配有限的時間、物品與星星。',tip:'消費不等於不好，存越多不等於越好；允許改變目標。'}];
const autonomyStages=['一起做','提醒後做','自己做','主動做'];
const characterStages=[{score:12,seen:2,weeks:0,name:'開始展現'},{score:30,seen:5,weeks:0,name:'越來越穩定'},{score:60,seen:10,weeks:8,name:'常常自然展現'}];
function educationFor(x){
 if(Array.isArray(x.abilities)&&x.abilities.length)return x.abilities.filter(id=>educationMap.some(a=>a.id===id));
 if(x.kind==='emotion')return ['emotion','thinking'];
 if(x.kind==='finance')return ['resources','thinking'];
 if(x.kind==='seen'||x.kind==='character-stage'||x.skill==='品格與關懷')return ['values','relationship'];
 if(/生活自理|獨立自主|刷牙|書包|整理|洗手/.test((x.skill||'')+(x.title||'')))return ['life','thinking'];
 return ['thinking'];
}
function upgradeEducation(s){
 for(const c of Object.values(s.children)){
  for(const x of [...c.tasks,...c.records,...c.completions]){x.abilities??=educationFor(x);if(x.skill==='自信與成長')x.growthOutcome='自信／自我效能';}
  if(s.educationVersion!==1){for(const b of c.characterBadges)if(!b.id?.startsWith('character:'))b.legacy=true;}
  refreshCharacter(c);
 }
 s.educationVersion=1;return s;
}
function characterProgress(c,tag,now=G.day()){
 const unique=new Map();for(const e of c.characterEvents)if(!e.cancelled&&e.date<=now&&!unique.has(e.id))unique.set(e.id,e);
 const xs=[...unique.values()].filter(e=>e.tag===tag||e.relatedTag===tag);
 const seen=xs.filter(e=>e.source==='seen'&&e.tag===tag).length;
 const practice=xs.filter(e=>e.source==='practice'&&e.tag===tag).length;
 const score=xs.reduce((n,e)=>n+(e.tag===tag?(e.source==='seen'?3:1):e.source==='seen'?1:0),0);
 const dates=xs.map(e=>e.date).filter(d=>/^\d{4}-\d{2}-\d{2}$/.test(d)).sort();
 const weeks=dates.length?Math.max(0,Math.floor((Date.parse(now+'T12:00:00Z')-Date.parse(dates[0]+'T12:00:00Z'))/604800000)):0;
 return {count:xs.length,seen,practice,score,weeks};
}
function refreshCharacter(c,now=G.day()){
 for(const tag of characterTags){const p=characterProgress(c,tag,now);
 characterStages.forEach((stage,i)=>{if(p.score>=stage.score&&p.seen>=stage.seen&&p.weeks>=stage.weeks&&!c.characterBadges.some(b=>!b.legacy&&b.tag===tag&&b.tier===i+1)){
 const id='character:'+tag+':'+(i+1);c.characterBadges.push({id,tag,tier:i+1,date:now,title:tag+' · '+stage.name});
 if(!c.records.some(r=>r.sourceKey===id))c.records.push({id:G.uid(),sourceKey:id,date:now,kind:'character-stage',category:'character',title:tag+' · '+stage.name,text:'我正在成為這樣的人。從生活裡的練習與家人的看見，慢慢認識自己。',skill:tag,abilities:['values']});
 }});}
}
function characterEvent(c,e){e={...e,tag:e.tag==='感恩'?'感謝':e.tag};if(!characterTags.includes(e.tag)||e.relatedTag&&(e.source!=='seen'||!characterTags.includes(e.relatedTag)||e.relatedTag===e.tag))return false;if(c.characterEvents.some(x=>x.id===e.id))return false;c.characterEvents.push(e);refreshCharacter(c);return true;}
function setCharacterThresholds(){return false;}
function reviseWish(c,id,name,reason){const w=c.wishes.find(w=>w.id===id);if(!w||!['pending','discuss','approved'].includes(w.status)||!name.trim()||name.length>50||!reason.trim()||reason.length>200)return false;(w.revisions??=[]).push({date:G.day(),name:w.name,reason:w.reason,cost:w.cost,status:w.status});releaseSavings(c);w.name=name.trim();w.reason=reason.trim();w.status='pending';delete w.cost;c.goal=null;G.financeStory(c,'wish-revision:'+G.uid(),'我重新想了想願望','改變目標也可以；我保留自己的星星，和家人重新規劃。');return true;}
Object.assign(G,{educationMap,autonomyStages,characterStages,educationFor,upgradeEducation,characterEvent,reviseWish});
function sendCard(c,data){const record=c.records.find(r=>r.id===data.sourceId),m=c.emotions.find(x=>x.id===data.sourceId||record?.kind==='emotion'&&x.id===record.sourceId);if(m){if(m.listener===listeners[1]||!listeners.includes(m.listener))return false;if(m.listener===listeners[2]&&(data.sourceType!=='emotion-bear'||!bearSentences.includes(data.content)||data.author!=='小白熊（家人選句）'))return false;}if(typeof data.content!=='string'||!data.content.trim()||data.content.length>500)return false;const card={id:G.uid(),childId:c.profile.id,sourceType:data.sourceType||'response',sourceId:data.sourceId||null,valueTag:data.valueTag||'',author:data.author||'家長',date:data.date||G.day(),content:data.content.trim(),readAt:null};c.mailbox.push(card);return card;}
function markCardRead(c,id){const card=c.mailbox.find(x=>x.id===id&&x.childId===c.profile.id);if(!card)return false;card.readAt??=new Date().toISOString();return true;}
Object.assign(G,{upgradeSync,linkedChildren,islandStages,island,characterTags,characterProgress,refreshCharacter,setCharacterThresholds,sendCard,markCardRead});
Object.assign(G,{upgrade,fresh,period,plusDays,age,limits,effort,rewardPresets,held,available,status,stats,thresholds,medalName,milestones,complete,approveTask,undo,openChest,requestReward,resolveReward,refund,useVoucher,activeWish,makeWish,approveWish,redeemWish,saveForGoal:reserveWish,releaseSavings,deposit,settle,adjust,starLedger:ledger,emotionOptions,recordEmotion,seen,addTask,monthEarned});
if(typeof module!=='undefined')module.exports=G;
})(globalThis);
