const {chromium}=require('playwright');
const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
(async()=>{
 const root=path.resolve(__dirname,'..');
 const server=http.createServer((req,res)=>{let name=req.url.split('?')[0];if(name==='/')name='/index.html';if(!['/index.html','/app.js','/model.js','/style.css','/learning.js'].includes(name)){res.writeHead(404);res.end();return}res.setHeader('Content-Type',name.endsWith('.css')?'text/css':name.endsWith('.js')?'text/javascript':'text/html; charset=utf-8');res.end(fs.readFileSync(path.join(root,name)))});
 await new Promise(r=>server.listen(0,'127.0.0.1',r));
 const browser=await chromium.launch({headless:true,channel:'msedge'});
 try{
 const context=await browser.newContext({viewport:{width:1180,height:820}}),page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(process.env.TEST_URL||`http://127.0.0.1:${server.address().port}`);
 const click=s=>page.locator(s).click(),stored=()=>page.evaluate(()=>JSON.parse(localStorage.getItem('kids-growth-v02')));
 const select=async id=>{if(!await page.locator('.welcome').count())await click('[data-action="users"]');await click(`[data-child="${id}"]`)};
 const login=async()=>{await click('[data-action="parent"]');await page.locator('#pin').fill('1234');await page.locator('#pin-form button.primary').click()};
 const finish=async id=>{await click(`[data-task="${id}"]`);await click(`[data-complete="${id}"]`);if(await page.locator('[data-action="show-reward"]').count())await click('[data-action="show-reward"]');await click('[data-action="close"]')};
 assert.equal(await page.locator('nav').count(),0);assert.equal(await page.locator('[data-child]').count(),3);await page.screenshot({path:path.join(root,'tests/entry.png'),fullPage:true});
 await select('brother');await click('[data-task="bag"]');await click('[data-complete="bag"]');assert.match(await page.locator('dialog').innerText(),/我學會了/);assert.doesNotMatch(await page.locator('dialog').innerText(),/\+10/);await click('[data-action="show-reward"]');assert.match(await page.locator('dialog').innerText(),/\+10/);await click('[data-action="close"]');assert.equal((await stored()).children.brother.stars,10);assert.equal((await stored()).children.brother.coins,5);
 await page.reload();assert.equal(await page.locator('.welcome').count(),1);await select('brother');assert.equal(await page.locator('[data-task="bag"]').isDisabled(),true);
 await select('sister');assert.match(await page.locator('#view').innerText(),/街舞/);await finish('brush');assert.equal((await stored()).children.sister.stars,5);assert.equal((await stored()).children.brother.stars,10);
 await select('little');assert.match(await page.locator('#view').innerText(),/滑步車/);await click('[data-page="emotion"]');assert.equal(await page.locator('[data-mood]').count(),9);await click('[data-mood="生氣"]');await click('[data-intensity="3"]');await click('[data-action="emotion-next"]');await click('[data-cause="暫時不想說"]');await click('[data-action="emotion-next"]');assert.equal(await page.locator('[data-tool]').count(),9);
 for(const id of ['breath','water','stretch','quiet','hug','draw','talk','words','company']){await click(`[data-tool="${id}"]`);assert.equal(await page.locator('[data-action="tried"]').count(),1)}
 await page.screenshot({path:path.join(root,'tests/emotion.png'),fullPage:true});await click('[data-action="tried"]');await click('[data-after="差不多"]');await click('[data-action="save-emotion"]');let c=(await stored()).children.little;assert.equal(c.emotions[0].cause,'暫時不想說');assert.equal(c.emotions[0].after,'差不多');assert.equal(c.stars+c.coins+c.growth,0);
 await click('[data-page="today"]');await finish('side');assert.equal((await stored()).children.little.stars,0);await login();await click('[data-approve-task]');assert.equal((await stored()).children.little.coins,8);
 await click('[data-edit-task="brush"]');await page.locator('#stars').fill('12');await page.locator('#coins').fill('7');await page.locator('#task-form button.primary').click();assert.equal((await stored()).children.little.tasks[0].stars,12);assert.equal((await stored()).children.little.stars,15);
 await click('[data-action="add"]');await page.locator('#preset').selectOption('clothes');await page.locator('#task-form button.primary').click();assert.equal((await stored()).children.little.tasks.length,6);
 await click('[data-action="add"]');await page.locator('#title').fill('聽家人說話');await page.locator('#skill').selectOption('品格與關懷');await page.locator('#task-form button.primary').click();let t=(await stored()).children.little.tasks.at(-1);assert.equal(t.stars+t.coins+t.growth,0);
 await page.locator('#seen').fill('你今天願意再試一次。');await page.locator('#seen-form button').click();
 await click('[data-edit-reward="ice"]');await page.locator('#reward-cost').fill('40');await page.locator('#reward-form button.primary').click();await click('[data-action="add-reward"]');await page.locator('#reward-name').fill('一起野餐');await page.locator('#reward-cost').fill('60');await page.locator('#reward-form button.primary').click();assert.equal((await stored()).rewards.length,4);
 await click('[data-action="parent"]');assert.equal(await page.locator('.welcome').count(),1);
 // Isolated test wallet, never the user's browser state.
 await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('kids-growth-v02'));s.children.brother.stars=100;s.children.brother.coins=100;localStorage.setItem('kids-growth-v02',JSON.stringify(s))});await page.reload();await select('brother');await click('[data-page="reward"]');await click('[data-goal="ice"]');await click('[data-action="save-stars"]');await page.locator('#amount').fill('70');await page.locator('#savings-form button.primary').click();assert.equal((await stored()).children.brother.stars,100);assert.equal(await page.locator('[data-reward="ice"]').isDisabled(),true);await click('[data-action="release-stars"]');await click('[data-reward="ice"]');await click('[data-request="ice"]');assert.equal((await stored()).children.brother.stars,100);
 await login();await click('[data-edit-reward="ice"]');await page.locator('#reward-cost').fill('80');await page.locator('#reward-form button.primary').click();await click('[data-approve-reward]');assert.match(await page.locator('dialog').innerText(),/40/);await click('[data-final-reward]');assert.equal((await stored()).children.brother.stars,60);
 await click('[data-action="parent"]');await select('brother');await click('[data-page="world"]');await click('[data-world="rabbit"]');await click('[data-buy-world="rabbit"]');assert.equal((await stored()).children.brother.coins,70);assert.equal((await stored()).children.brother.stars,60);assert.equal((await stored()).children.brother.growth,10);
 await page.setViewportSize({width:390,height:844});for(const p of ['today','growth','emotion','reward','world']){await click(`[data-page="${p}"]`);assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),p+' overflows')};await click('[data-action="users"]');await page.screenshot({path:path.join(root,'tests/mobile.png'),fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));
 // Four passport sections and the full finance-learning journey.
 await select('brother');await click('[data-page="reward"]');assert.equal(await page.locator('[data-lesson]').count(),3);const moneyBefore=(await stored()).children.brother.stars;
 for(const id of ['resources','needs','choices']){await click('[data-lesson="'+id+'"]');await click('[data-lesson-choice="1"]');await click('[data-save-lesson="'+id+'"]')}
 assert.equal((await stored()).children.brother.stars,moneyBefore);await click('[data-lesson="choices"]');await click('[data-lesson-choice="0"]');assert.equal(await page.locator('[data-save-lesson]').count(),0);await click('[data-action="close"]');
 await click('[data-page="growth"]');assert.equal(await page.locator('[data-category]').count(),4);assert.match(await page.locator('[data-category="finance"]').innerText(),/選擇與等待/);assert.match(await page.locator('[data-category="life"]').innerText(),/整理我的書包/);
 await page.reload();await select('brother');await click('[data-page="growth"]');assert.match(await page.locator('[data-category="finance"]').innerText(),/選擇與等待/);
 await page.setViewportSize({width:1180,height:820});await page.screenshot({path:path.join(root,'tests/passport.png'),fullPage:true});await click('[data-page="reward"]');await page.screenshot({path:path.join(root,'tests/finance.png'),fullPage:true});
 await select('little');await click('[data-page="growth"]');assert.match(await page.locator('[data-category="relationship"]').innerText(),/你今天願意再試一次/);assert.match(await page.locator('[data-category="emotion"]').innerText(),/我越來越懂自己/);assert.doesNotMatch(await page.locator('[data-category="finance"]').innerText(),/我學會了/);
 await page.setViewportSize({width:390,height:844});for(const p of ['growth','reward']){await click('[data-page="'+p+'"]');assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth))}
 // Legacy state upgrade with a backup and no reset of existing balances/history.
 await page.evaluate(()=>{const s=JSON.parse(localStorage.getItem('kids-growth-v02'));delete s.rulesVersion;delete s.rewards;delete s.children.brother.coins;localStorage.setItem('kids-growth-v02',JSON.stringify(s))});await page.reload();assert.equal((await stored()).children.brother.stars,60);assert.equal((await stored()).children.brother.redemptions[0].cost,40);assert.ok(await page.evaluate(()=>localStorage.getItem('kids-growth-v02-before-rules-v3')));assert.equal((await stored()).children.brother.coins,0);
 const tab=await context.newPage();await tab.goto(page.url());await tab.locator('[data-child="brother"]').click();await tab.locator('[data-task="brush"]').click();await tab.locator('[data-complete="brush"]').click();await page.waitForFunction(()=>JSON.parse(localStorage.getItem('kids-growth-v02')).children.brother.stars===65);await tab.close();
 await page.evaluate(()=>localStorage.setItem('kids-growth-v02','broken'));await page.reload();assert.match(await page.locator('#notice').innerText(),/暫停/);assert.equal(await page.evaluate(()=>localStorage.getItem('kids-growth-v02')),'broken');assert.deepEqual(errors,[]);
 console.log('PASS: entry, learned-before-reward, child isolation, persistence, 9 moods and tools, reflection, parent task/catalog editing, savings, price snapshots, coins, migration backup, responsive layouts, multi-tab and corrupt-state protection');
 }finally{await browser.close();server.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
