const {chromium}=require('playwright'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),a=require('node:assert/strict'),G=require('../spec-model');
(async()=>{const root=path.resolve(__dirname,'..'),server=http.createServer((q,s)=>{const f=q.url.split('?')[0].slice(1)||'index.html';if(!['index.html','model.js','spec-model.js','app.js','spec-app.js','learning.js','style.css'].includes(f)){s.writeHead(404);s.end();return;}s.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':'text/html;charset=utf-8');s.end(fs.readFileSync(path.join(root,f)));});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{
 browser=await chromium.launch({headless:true,channel:'msedge'});const ctx=await browser.newContext({viewport:{width:1180,height:820}}),seed=G.fresh(),d=seed.children.brother;delete seed.educationVersion;d.stars=900;
 for(let i=0;i<3;i++)d.characterEvents.push({id:'old-seen-'+i,date:G.day(),source:'seen',tag:'善良',text:'以前的故事'});
 d.characterEvents.push({id:'practice',date:G.day(),source:'practice',tag:'善良',text:'練習'});
 G.sendCard(d,{content:'原始回應：我看見你幫忙。',author:'阿嬤'});const w=G.makeWish(d,'週末活動','想出去','🎡');G.approveWish(d,w.id,800);G.saveForGoal(d,300);
 await ctx.addInitScript(data=>{if(!localStorage.getItem('seeded')){localStorage.setItem('kids-growth-v02',JSON.stringify(data));localStorage.setItem('seeded','1');}},seed);
 const p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.TEST_URL||'http://127.0.0.1:'+server.address().port);
 const click=s=>p.locator(s).click(),store=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('kids-growth-v02')));
 a.equal((await store()).educationVersion,1);a.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('kids-growth-v02-before-education-20261008')).children.brother.stars),900);
 await click('[data-child="brother"]');await click('[data-s-task="brush"]');await p.locator('#autonomy-stage').selectOption('主動做');await click('[data-s-complete="brush"]');a.match(await p.locator('dialog').innerText(),/生活自主力/);await click('[data-s="reward-after-learn"]');await click('[data-action="close"]');a.equal((await store()).children.brother.completions[0].autonomy,'主動做');
 await click('[data-action="parent"]');await p.locator('#pin').fill('1234');await p.locator('#pin-form button.primary').click();
 await click('[data-s="seen-form"]');await p.locator('#seen-text').fill('你先問願不願意，再幫忙。');await p.locator('#seen-related').selectOption('尊重');await p.locator('#spec-seen-form button.primary').click();
 let s=await store();a.equal(s.children.brother.characterBadges.length,1);a.equal(s.children.brother.characterEvents.at(-1).relatedTag,'尊重');a.equal(s.children.brother.mailbox[0].content,'原始回應：我看見你幫忙。');a.equal(s.children.sister.characterBadges.length,0);
 await click('[data-parent-tab="manage"]');a.equal(await p.locator('#character-settings').count(),0);
 const snapshot=await store(),bad=structuredClone(snapshot);bad.children.brother.characterEvents.at(-1).relatedTag=['尊重','勇氣'];await p.locator('#import-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});a.deepEqual(await store(),snapshot);
 await click('[data-parent-tab="today"]');await p.locator('details summary').click();a.match(await p.locator('#view').innerText(),/身體、物品和隱私/);a.match(await p.locator('#view').innerText(),/資源與財務力/);
 await click('[data-action="parent"]');await click('[data-child="brother"]');await click('nav [data-page="accumulation"]');const text=await p.locator('#view').innerText();a.match(text,/善良 · 開始展現/);a.doesNotMatch(text,/家人看見 \d|品格練習 \d|12|30|60/);
 await click('nav [data-page="growth"]');await click('[data-passport="character"]');a.match(await p.locator('dialog').innerText(),/開始展現/);await click('[data-action="close"]');await p.screenshot({path:path.join(root,'tests/education-passport.png'),fullPage:true});
 await click('nav [data-page="reward"]');await click('[data-s="choice-wish"]');await click('[data-revise-wish]');await p.locator('#revised-name').fill('桌遊');await p.locator('#revised-reason').fill('想一起玩');await p.locator('#revise-wish-form button.primary').click();s=await store();a.equal(s.children.brother.stars,905);a.equal(s.children.brother.savings,0);a.equal(s.children.brother.wishCards,2);a.equal(s.children.brother.wishes[0].status,'pending');
 await p.reload();a.equal((await store()).children.brother.characterBadges.length,1);a.equal((await store()).children.brother.records.filter(x=>x.kind==='character-stage').length,1);
 await click('[data-child="brother"]');for(const size of [[320,568],[390,844],[1180,820]]){await p.setViewportSize({width:size[0],height:size[1]});for(const pg of ['today','growth','accumulation','reward','world']){await click('nav [data-page="'+pg+'"]');a.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),`${pg} overflow`);}}
 a.deepEqual(errors,[]);console.log('PASS: education migration backup, autonomy, related character, hidden UI, passport unlock, original mailbox, malformed import, boundary guidance, wish revision, reload deduplication, 320/390/1180 layouts');
}finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1});
