const test=require('node:test'),a=require('node:assert/strict'),G=require('../src/site/spec-model');
const today='2026-10-09',time='2026-10-09T04:00:00.000Z',ms=Date.parse(time),fresh=()=>G.fresh().children.brother;
const draft=(x={})=>({emotionVersion:25,date:today,mood:'生氣',intensity:3,causes:['有人拿我的東西','我覺得不公平'],listener:G.listeners[0],rounds:[{choices:[{label:'我想冷靜一下',tried:true},{label:'我想喝點水',tried:false}],after:'還是一樣'}],...x});
test('111 exact causes /36 groups /42 hints and grouped validation',()=>{a.equal(Object.values(G.emotionData.causes).flat().length,36);a.equal(Object.values(G.emotionData.causes).flat().flatMap(g=>g.items).length,111);a.equal(Object.values(G.emotionData.care).flat().length,42);a.equal(G.recordEmotion(fresh(),draft({causes:['not-real']}),today,time),false);a.equal(G.recordEmotion(fresh(),draft({causes:['我覺得不公平','我覺得不公平']}),today,time),false);});
test('three rounds maximum, per-item attempts and unknown exclusive; no economy rewards',()=>{const c=fresh(),balances=[c.stars,c.coins,c.growth];const r=draft().rounds[0];a.equal(G.recordEmotion(c,draft({rounds:[r,r,r,r]}),today,time),false);a.equal(G.recordEmotion(c,draft({rounds:[{choices:[{label:'我還不知道',tried:false},{label:'我想喝點水',tried:false}],after:'好一點'}]}),today,time),false);const x=G.recordEmotion(c,draft({rounds:[r,r,{...r,after:'好一點'}]}),today,time);a.ok(x);a.equal(x.rounds[0].choices[1].tried,false);a.deepEqual([c.stars,c.coins,c.growth],balances);a.equal(c.records.length,0);});
test('silent and backfill cannot receive replies; backfill edit immutable creation and event date',()=>{for(const listener of [G.listeners[1],G.listeners[2]]){const c=fresh(),d=draft({date:'2026-10-08',listener,rounds:[]}),x=G.recordEmotion(c,d,today,time);a.ok(x);a.equal(G.replyEmotion(c,x.id,{sentence:0,content:'hello'}),false);a.equal(G.sendCard(c,{sourceId:x.id,content:'hello'}),false);a.ok(G.editBackfill(c,x.id,{...d,intensity:1},today,'2026-10-09T05:00:00.000Z'));a.equal(x.createdAt,time);a.equal(G.editBackfill(c,x.id,{...d,date:today},today),false);a.equal(G.editBackfill(c,x.id,d,'2026-10-10'),false);}const c=fresh(),x=G.recordEmotion(c,draft({listener:G.listeners[1]}),today,time);a.equal(G.replyEmotion(c,x.id,{content:'bypass'}),false);});
test('one transparent bear card, isolated child, no duplicate replies',()=>{const c=fresh(),x=G.recordEmotion(c,draft({listener:G.listeners[2]}),today,time);a.ok(G.replyEmotion(c,x.id,{sentence:0}));a.equal(G.replyEmotion(c,x.id,{sentence:1}),false);a.equal(G.replyEmotion(fresh(),x.id,{sentence:0}),false);a.equal(c.mailbox[0].sourceId,x.id);});
test('creation-time boundary and 12-month rollover remove details and linked stories/replies',()=>{const c=fresh(),x=G.recordEmotion(c,draft(),today,time);c.records.push({id:'story',sourceId:x.id,date:today,kind:'emotion',text:'private'});a.ok(G.replyEmotion(c,x.id,{content:'private reply'}));G.maintainEmotions(c,ms+30*86400000-1);a.equal(c.emotions.length,1);G.maintainEmotions(c,ms+30*86400000);a.equal(c.emotions.length,0);a.equal(c.records.length,0);a.equal(c.mailbox.length,0);a.equal(c.emotionTrends[0].count,1);a.doesNotMatch(JSON.stringify(c.emotionTrends),/private|有人拿|04:00/);G.maintainEmotions(c,Date.parse('2027-10-01T00:00:00+08:00'));a.equal(c.emotionTrends.length,0);});
test('decline, hide, reapply and idempotent approval; old backups never revive deleted events',()=>{const c=fresh(),x=G.recordEmotion(c,draft(),today,time),backup=JSON.parse(JSON.stringify(c));a.ok(G.requestEmotionDeletion(c,x.id));a.ok(G.decideEmotionDeletion(c,x.id,false));a.ok(G.hideEmotion(c,x.id,true));a.ok(G.requestEmotionDeletion(c,x.id));a.ok(G.decideEmotionDeletion(c,x.id,true));a.ok(G.decideEmotionDeletion(c,x.id,true));G.mergeEmotionPolicy(backup,c,ms);a.equal(backup.emotions.length,0);a.ok(backup.emotionDeleted.includes(x.id));});
test('already aggregated event approval removes entire affected summary and import cannot resurrect it',()=>{const c=fresh(),x=G.recordEmotion(c,draft(),today,time);G.maintainEmotions(c,ms+30*86400000);const old=JSON.parse(JSON.stringify(c));a.ok(G.removeEmotion(c,x.id));a.equal(c.emotionTrends.length,0);G.mergeEmotionPolicy(old,c,ms+30*86400000);a.equal(old.emotionTrends.length,0);a.equal(old.emotions.length,0);});
test('expired current event cannot return through a pre-expiry backup or double count',()=>{const c=fresh(),x=G.recordEmotion(c,draft(),today,time),old=JSON.parse(JSON.stringify(c));G.maintainEmotions(c,ms+30*86400000);G.mergeEmotionPolicy(old,c,ms+30*86400000);a.equal(old.emotions.length,0);a.equal(old.emotionExpired.length,1);a.equal(old.emotionTrends.length,0);});
test('legacy timestamp fallback removes orphan emotion stories and keeps non-emotion records',()=>{const c=fresh();c.emotions.push({id:'legacy',date:'2020-01-01',mood:'生氣'});c.records.push({id:'private-old',date:'2020-01-01',kind:'emotion',text:'old private'},{id:'task',date:'2020-01-01',kind:'task',text:'keep'});G.maintainEmotions(c,ms);a.deepEqual(c.records.map(x=>x.id),['task']);});

test('pre-expiry archive with sourceless legacy emotion story is fully scrubbed',()=>{const c=fresh();c.emotions.push({id:'legacy-event',date:'2026-09-01',mood:'難過',createdAt:'2026-09-01T00:00:00Z'});c.records.push({id:'legacy-story',kind:'emotion',date:'2026-09-01',text:'sensitive cause'});const archive=JSON.parse(JSON.stringify(c));G.maintainEmotions(c,ms);G.mergeEmotionPolicy(archive,c,ms);a.equal(archive.records.filter(x=>x.kind==='emotion').length,0);});
test('hidden declined event can be restored after reapplication',()=>{const c=fresh(),x=G.recordEmotion(c,draft(),today,time);G.requestEmotionDeletion(c,x.id);G.decideEmotionDeletion(c,x.id,false);G.hideEmotion(c,x.id,true);G.requestEmotionDeletion(c,x.id);a.equal(G.hideEmotion(c,x.id,false),true);a.equal(x.hidden,false);});
