const test=require('node:test'),a=require('node:assert/strict'),G=require('../spec-model');
const make=()=>G.fresh().children.brother;
test('upgrade keeps historical assets, reservations and independent children',()=>{const old=require('../model').fresh();delete old.specVersion;old.children.brother.stars=800;old.children.brother.savings=200;old.children.brother.goal='ice';const s=G.upgrade(old);a.equal(s.children.brother.stars,800);a.equal(s.children.brother.savings,200);a.equal(s.children.sister.stars,0);a.deepEqual(G.upgrade(s),s);a.equal(s.children.brother.wishCards,3)});
test('weekly and monthly boundaries, Monday, month and year rollover',()=>{const c=make();c.tasks.push({...c.tasks[0],id:'weekly',type:'每週'},{...c.tasks[0],id:'monthly',type:'每月'});a.ok(G.complete(c,'weekly','2026-12-31'));a.equal(G.complete(c,'weekly','2027-01-03'),null);a.ok(G.complete(c,'weekly','2027-01-04'));a.ok(G.complete(c,'monthly','2026-12-31'));a.ok(G.complete(c,'monthly','2027-01-01'));a.equal(G.complete(c,'monthly','2027-01-15'),null);a.equal(G.stats(c,c.tasks.find(t=>t.id==='weekly')).best,2)});
test('undo reclaims snapshot once, preserves peak, refuses parents and spent funds',()=>{const c=make(),x=G.complete(c,'brush');a.equal(c.growth,15);const peak=c.worldPeak;a.equal(G.undo(c,x.id).ok,true);a.equal(c.stars+c.coins+c.growth,0);a.equal(c.worldPeak,peak);a.equal(G.undo(c,x.id).ok,false);const y=G.complete(c,'side');G.approveTask(c,y.id);a.equal(G.undo(c,y.id).ok,false);const z=G.complete(c,'brush');c.stars=0;a.equal(G.undo(c,z.id).ok,false)});
test('medals and fixed chest grants are idempotent without extra badge stars',()=>{const c=make(),t=c.tasks[0];for(let i=0;i<100;i++)G.complete(c,t.id,G.plusDays('2026-01-01',i));a.equal(c.medals.length,4);a.equal(c.chests.length,2);const before=c.stars;G.milestones(c,t);a.equal(c.stars,before);const big=c.chests.find(b=>b.size==='big');a.ok(G.openChest(c,big.id));a.equal(c.stars,before+100);a.equal(c.wishCards,4);a.equal(G.openChest(c,big.id),false);a.equal(G.stats(c,t).best,100)});
test('deposit bounds, simple bonus, early exit, cap, one-time savings chest',()=>{const c=make();c.stars=10000;const d=G.deposit(c,200,6,'2026-01-01');a.equal(d.bonus,12);a.equal(G.available(c),9800);a.equal(G.deposit(c,250,1),false);a.equal(G.deposit(c,200,13),false);a.equal(G.deposit(c,5000,1),false);const s=G.settle(c,d.id,'2026-02-12');a.equal(s.awarded,12);a.equal(c.stars,10012);a.equal(G.settle(c,d.id),false);const x=G.deposit(c,200,4,'2026-01-01');G.settle(c,x.id,'2026-01-02');a.equal(c.stars,10012);a.equal(c.chests.filter(x=>x.id==='savings-once').length,1)});
test('vouchers require confirmation, can refund only unused; snapshots retained',()=>{const c=make();c.stars=1000;const r=G.requestReward(c,'ice',G.rewardPresets);a.equal(r.status,'pending');a.equal(c.stars,1000);a.ok(G.resolveReward(c,r.id,true));a.equal(c.stars,600);a.ok(G.refund(c,r.id));a.equal(c.stars,1000);a.equal(G.refund(c,r.id),false);c.settings.requireApproval=false;const x=G.requestReward(c,'ice',G.rewardPresets);a.equal(x.status,'voucher');G.useVoucher(c,x.id);a.equal(G.refund(c,x.id),false)});
test('one wish at a time, reserved funds cannot spend twice, usage frees next card',()=>{const c=make();c.stars=1000;const w=G.makeWish(c,'腳踏車','想練習','🚲');a.equal(c.wishCards,2);a.equal(G.makeWish(c,'第二個','原因','🎁'),false);G.approveWish(c,w.id,800);G.saveForGoal(c,800);a.equal(G.available(c),200);a.equal(G.requestReward(c,'ice',G.rewardPresets),false);a.ok(G.redeemWish(c));a.equal(c.stars,200);a.equal(G.redeemWish(c),false);G.useVoucher(c,c.redemptions[0].id);a.ok(G.makeWish(c,'書','想閱讀','📚'))});
test('moods: yesterday-only backfill, once daily, short flow, neutral exit and bounded retry',()=>{const c=make();const base={date:'2026-10-04',mood:'難過',intensity:3,cause:'其他事情',loop_count:0};a.ok(G.recordEmotion(c,base,'2026-10-05'));a.equal(G.recordEmotion(c,base,'2026-10-05'),false);a.equal(G.recordEmotion(c,{...base,date:'2026-10-03'},'2026-10-05'),false);a.ok(G.recordEmotion(c,{...base,date:'2026-10-05',mood:'開心'},'2026-10-05'));a.equal(c.stars+c.growth,0);const n=make();a.ok(G.recordEmotion(n,{...base,date:'2026-10-05',need:'抱抱',strategy:'先這樣就好',exit_type:'neutral',loop_count:2},'2026-10-05'));a.equal(G.recordEmotion(make(),{...base,date:'2026-10-05',loop_count:3},'2026-10-05'),false)});
test('seen gives growth only, age effort and independent caps',()=>{const c=make();G.seen(c,'主動幫忙','善良','阿嬤');a.equal(c.growth,20);a.equal(c.stars,0);a.equal(G.limits(c,'每週'),3);const young=G.fresh().children.little;a.equal(G.limits(young,'每週'),2);a.equal(G.effort(young,1).stars,15);a.equal(G.effort(c,1).stars,10)});

test('wish transfers change available balance, persist ledger and never inflate earned budget',()=>{const c=make();c.stars=55;c.goal='test-goal';a.ok(G.saveForGoal(c,20));a.equal(G.available(c),35);a.equal(c.savings,20);a.equal(G.saveForGoal(c,36),false);a.equal(G.starLedger(c).at(-1).amount,-20);const copy=JSON.parse(JSON.stringify(c));a.equal(G.available(copy),35);a.ok(G.releaseSavings(copy));a.equal(G.available(copy),55);a.equal(G.starLedger(copy).at(-1).amount,20);a.equal(G.releaseSavings(copy),false);a.equal(G.monthEarned(copy),0);a.equal(copy.stars,55)});
