const {chromium}=require('playwright'),http=require('node:http'),fs=require('node:fs'),path=require('node:path'),a=require('node:assert/strict'),G=require('../spec-model');
(async()=>{const root=path.resolve(__dirname,'..');const server=http.createServer((q,s)=>{const f=q.url.split('?')[0].slice(1)||'index.html';if(!['index.html','model.js','spec-model.js','app.js','learning.js','spec-app.js','style.css'].includes(f)){s.writeHead(404);s.end();return;}s.setHeader('Content-Type',f.endsWith('.js')?'text/javascript':f.endsWith('.css')?'text/css':'text/html;charset=utf-8');s.end(fs.readFileSync(path.join(root,f)));});await new Promise(r=>server.listen(0,'127.0.0.1',r));let browser;try{browser=await chromium.launch({headless:true,channel:'msedge'});const ctx=await browser.newContext({viewport:{width:1180,height:820}}),seed=G.fresh();seed.specVersion=1;delete seed.parent;for(const [id,c] of Object.entries(seed.children)){delete c.mailbox;delete c.characterEvents;delete c.characterBadges;delete c.legacyScenery;delete c.settings.characterThresholds;c.stars=1000;c.coins=100;c.growth=100;c.worldPeak=100;c.records.push({id:'seen-'+id,date:G.day(),kind:'seen',title:'主動幫忙',skill:'善良',text:id+' 的具體故事',author:'阿嬤'});G.complete(c,'side');c.emotions.push({id:'mood-'+id,date:G.day(),mood:'難過',intensity:2,cause:'事情有點難',need:'有人陪我',strategy:'找大人說',parentTip:'先陪著，讓孩子知道可以求助。'});}
await ctx.addInitScript(data=>{if(!localStorage.getItem('sync-seeded')){localStorage.setItem('kids-growth-v02',JSON.stringify(data));localStorage.setItem('sync-seeded','1');}},seed);
const p=await ctx.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(process.env.TEST_URL||'http://127.0.0.1:'+server.address().port);const click=s=>p.locator(s).click(),store=()=>p.evaluate(()=>JSON.parse(localStorage.getItem('kids-growth-v02')));const login=async()=>{await click('[data-action="parent"]');await p.locator('#pin').fill('1234');await p.locator('#pin-form button.primary').click();};const leave=async(id='brother')=>{await click('[data-action="parent"]');await click('[data-child="'+id+'"]');};
a.equal((await store()).specVersion,2);a.equal((await store()).children.brother.mailbox.length,1);a.equal((await store()).children.brother.growth,100);a.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('kids-growth-v02-before-spec-030')).specVersion),1);
await login();a.deepEqual(await p.locator('[data-home-section]').evaluateAll(xs=>xs.map(x=>x.dataset.homeSection)),['todos','care','seen','summary','tip']);a.equal(await p.locator('[data-approve-task]').count(),3);a.equal(await p.locator('.balance').count(),0);
await click('[data-approve-task][data-owner="sister"]');let s=await store();a.equal(s.children.sister.completions[0].status,'approved');a.equal(s.children.brother.completions[0].status,'pending');a.equal(s.children.little.completions[0].status,'pending');
await click('[data-care][data-owner="little"]');a.match(await p.locator('dialog').innerText(),/弟弟/);a.match(await p.locator('dialog').innerText(),/先陪著/);await click('[data-action="close"]');
await click('[data-response="seen-sister"][data-owner="sister"]');await p.locator('#response-content').fill('我看見你慢慢試，謝謝你願意分享。');await p.locator('#response-form button.primary').click();s=await store();a.equal(s.children.sister.mailbox.length,2);a.equal(s.children.brother.mailbox.length,1);a.equal(s.children.little.mailbox.length,1);a.equal(s.children.sister.mailbox.at(-1).sourceId,'seen-sister');
await click('[data-quick-record]');await p.locator('#quick-child').selectOption('little');await click('[data-quick-kind="seen"]');await p.locator('#seen-author').fill('爸爸');await p.locator('#seen-tag').selectOption('感謝');await p.locator('#seen-text').fill('你主動謝謝陪你練習的人。');await p.locator('#spec-seen-form button.primary').click();s=await store();a.equal(s.children.little.mailbox.length,2);a.equal(s.children.little.growth,120);a.equal(s.children.little.characterEvents.at(-1).tag,'感謝');
await click('[data-quick-record]');await p.locator('#quick-child').selectOption('sister');await click('[data-quick-kind="achievement"]');await p.locator('#achievement-title').fill('第一次自己準備');await p.locator('#achievement-text').fill('記得帶水壺。');await p.locator('#achievement-form button.primary').click();a.equal((await store()).children.sister.mailbox.length,3);
await click('[data-quick-record]');await p.locator('#quick-child').selectOption('little');await click('[data-quick-kind="task"]');await p.locator('#task-name').fill('主動道謝');await p.locator('#task-skill').selectOption('品格與關懷');await p.locator('#task-value').selectOption('感謝');await p.locator('#effort').selectOption('2');a.equal(await p.locator('#task-stars').inputValue(),'0');a.equal(await p.locator('#task-coins').inputValue(),'3');await p.locator('#spec-task-form button.primary').click();await click('[data-s="save-task-preview"]');const task=(await store()).children.little.tasks.at(-1);a.equal(task.valueTag,'感謝');
await click('[data-parent-tab="manage"]');a.equal(await p.locator('#character-settings').count(),0);
await leave('little');await click('[data-s-task="'+task.id+'"]');await click('[data-s-complete="'+task.id+'"]');await click('[data-s="reward-after-learn"]');await click('[data-action="close"]');s=await store();a.equal(s.children.little.stars,1000);a.equal(s.children.little.coins,103);a.equal(s.children.little.growth,150);a.equal(s.children.little.characterEvents.filter(e=>e.source==='practice').length,1);
await click('nav [data-page="accumulation"]');a.match(await p.locator('#view').innerText(),/正在生活裡練習/);await click('nav [data-page="world"]');a.match(await p.locator('.world-summary').innerText(),/初來到小島/);await click('[data-s="mailbox"]');a.equal(await p.locator('[data-card]').count(),2);const card=(await store()).children.little.mailbox.at(-1);await click('[data-card="'+card.id+'"]');a.match(await p.locator('dialog').innerText(),/爸爸/);a.match(await p.locator('dialog').innerText(),/已讀/);a.ok((await store()).children.little.mailbox.at(-1).readAt);const read=(await store()).children.little.mailbox.at(-1).readAt;await click('[data-action="close"]');await p.reload();await click('[data-child="little"]');a.equal((await store()).children.little.mailbox.at(-1).readAt,read);
await login();await click('[data-parent-tab="manage"]');const snapshot=await store();await p.locator('#import-file').setInputFiles({name:'valid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(snapshot))});await click('[data-s="import-confirm"]');a.equal((await store()).children.little.mailbox.at(-1).readAt,read);const bad=structuredClone(snapshot);bad.children.little.mailbox[0].childId='sister';await p.locator('#import-file').setInputFiles({name:'bad.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(bad))});a.deepEqual(await store(),snapshot);
await click('[data-parent-tab="today"]');for(const size of [[1180,820],[390,844],[320,568]]){await p.setViewportSize({width:size[0],height:size[1]});a.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'parent overflow');}await p.setViewportSize({width:1180,height:820});await p.screenshot({path:path.join(root,'tests/sync-parent.png'),fullPage:true});await leave('sister');for(const pg of ['today','growth','accumulation','reward','world']){await click('nav [data-page="'+pg+'"]');a.doesNotMatch(await p.locator('#app').innerText(),/NT\$|10⭐＝/);await p.setViewportSize({width:390,height:844});a.ok(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),pg+' overflow');}await click('[data-s="mailbox"]');a.equal(await p.locator('[data-card]').count(),3);a.doesNotMatch(await p.locator('dialog').innerText(),/主動謝謝陪/);await p.screenshot({path:path.join(root,'tests/sync-mailbox.png'),fullPage:true});a.deepEqual(errors,[]);console.log('PASS: v1 migration, 3-child inbox targeting, ordered home, emotion care, responses, quick records, character practice/hidden stages, persistent mailbox reads, roundtrip and invalid import, responsive UI');
}finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
